import type { CompileResult } from './types';
import type { RecipeSpec } from '@superapp/core';
import { compileStyleVars, compileStyleCss, compileOverlayPositionCss, compileCustomCss, normalizeStyle } from './style-compiler';

const SECTION_KEY_PREFIX = 'sections/superapp-popup-';

export function compileThemePopup(spec: Extract<RecipeSpec, { type: 'theme.popup' }>, themeId: string): CompileResult {
  const slugged = slug(spec.name);
  const sectionKey = `${SECTION_KEY_PREFIX}${slugged}.liquid`;
  const cssFile = `superapp-popup-${slugged}.css`;
  const jsFile = `superapp-popup-${slugged}.js`;
  const cssKey = `assets/${cssFile}`;
  const jsKey = `assets/${jsFile}`;
  const style = normalizeStyle(spec.style);
  const styleVars = compileStyleVars(style);
  const styleCss = compileStyleCss(style, '.superapp-popup__panel');
  const overlayCss = compileOverlayPositionCss(style, '.superapp-popup', '.superapp-popup__panel');

  const liquid = `
{% comment %} Generated by SuperApp. Do not edit directly. {% endcomment %}
{{ '${cssFile}' | asset_url | stylesheet_tag }}
<div class="superapp-popup" data-trigger="${escapeJson(spec.config.trigger)}" data-frequency="${escapeJson(spec.config.frequency)}" hidden>
  <div class="superapp-popup__backdrop" data-superapp-close></div>
  <div class="superapp-popup__panel" role="dialog" aria-modal="true" aria-label="${escapeHtml(spec.config.title)}">
    <button class="superapp-popup__close" type="button" data-superapp-close aria-label="Close">×</button>
    <h3 class="superapp-popup__title">${escapeHtml(spec.config.title)}</h3>
    ${spec.config.body ? `<p class="superapp-popup__body">${escapeHtml(spec.config.body)}</p>` : ''}
    ${
      spec.config.ctaText && spec.config.ctaUrl
        ? `<a class="superapp-popup__cta" href="${escapeHtml(spec.config.ctaUrl)}">${escapeHtml(spec.config.ctaText)}</a>`
        : ''
    }
  </div>
</div>

<script>
(function(){
  var root = document.currentScript && document.currentScript.previousElementSibling;
  if(!root) return;
  var trigger = root.getAttribute('data-trigger');
  var freq = root.getAttribute('data-frequency');
  var key = 'superapp_popup_' + ${JSON.stringify(slugged)};
  function canShow(){
    try{
      var last = localStorage.getItem(key);
      if(!last) return true;
      var t = parseInt(last,10);
      if(Number.isNaN(t)) return true;
      var now = Date.now();
      var day = 24*60*60*1000;
      var week = 7*day;
      if(freq === 'EVERY_VISIT') return true;
      if(freq === 'ONCE_PER_DAY') return now - t > day;
      if(freq === 'ONCE_PER_WEEK') return now - t > week;
      return true;
    }catch(e){ return true; }
  }
  function markShown(){ try{ localStorage.setItem(key, String(Date.now())); }catch(e){} }
  function open(){ root.hidden = false; markShown(); }
  function close(){ root.hidden = true; }
  root.addEventListener('click', function(e){ if(e.target && e.target.hasAttribute('data-superapp-close')) close(); });
  if(!canShow()) return;
  if(trigger === 'ON_LOAD') { window.requestAnimationFrame(open); return; }
  if(trigger === 'ON_SCROLL_50') {
    var done = false;
    window.addEventListener('scroll', function(){
      if(done) return;
      var sc = (window.scrollY || 0) / Math.max(1, (document.documentElement.scrollHeight - window.innerHeight));
      if(sc >= 0.5){ done = true; open(); }
    }, { passive: true });
    return;
  }
  if(trigger === 'ON_EXIT_INTENT') {
    var done = false;
    document.addEventListener('mouseout', function(e){
      if(done) return;
      if(e.clientY <= 0){ done = true; open(); }
    });
    return;
  }
})();
</script>

{% schema %}
${schemaJson(spec)}
{% endschema %}
`.trim();

  const css = `
.superapp-popup__panel {
${styleVars.split('\n').map((l) => '  ' + l).join('\n')}
}
${overlayCss}
.superapp-popup[hidden]{ display:none; }
.superapp-popup__backdrop { position:absolute; inset:0; background: var(--sa-backdrop); }
${styleCss}
.superapp-popup__close { position:absolute; top: 8px; right: 10px; border:0; background:transparent; font-size: 22px; cursor:pointer; }
.superapp-popup__title { margin: 0 0 10px; font-size: 1.25em; font-weight: var(--sa-fw); }
.superapp-popup__body { margin: 0 0 12px; opacity: .85; }
.superapp-popup__cta { display:inline-block; padding: 10px 14px; border: 1px solid currentColor; text-decoration:none; border-radius: var(--sa-radius); background: var(--sa-btn-bg, transparent); color: var(--sa-btn-text, var(--sa-text)); }
@media (max-width: 749px) { .superapp-popup { display: ${style.responsive.hideOnMobile ? 'none' : 'block'}; } }
@media (min-width: 750px) { .superapp-popup { display: ${style.responsive.hideOnDesktop ? 'none' : 'block'}; } }
${compileCustomCss(style, '.superapp-popup')}
`.trim();

  const js = `/* reserved */`;

  return {
    ops: [
      { kind: 'THEME_ASSET_UPSERT', themeId, key: sectionKey, value: liquid },
      { kind: 'THEME_ASSET_UPSERT', themeId, key: cssKey, value: css },
      { kind: 'THEME_ASSET_UPSERT', themeId, key: jsKey, value: js },
      { kind: 'AUDIT', action: 'compile.theme.popup', details: JSON.stringify({ sectionKey, cssKey, jsKey }) },
    ],
    compiledJson: JSON.stringify({ sectionKey, cssKey, jsKey }),
  };
}

function slug(input: string) {
  return input.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '').slice(0, 40);
}

function escapeJson(input: string) {
  return input.replace(/\\/g, '\\\\').replace(/"/g, '\"');
}

function escapeHtml(input: string) {
  return input
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function schemaJson(spec: Extract<RecipeSpec, { type: 'theme.popup' }>): string {
  const schema: Record<string, unknown> = {
    name: spec.name,
    settings: [],
    presets: [{ name: spec.name }],
  };
  if (spec.placement?.enabled_on) schema.enabled_on = spec.placement.enabled_on;
  else if (spec.placement?.disabled_on) schema.disabled_on = spec.placement.disabled_on;
  return JSON.stringify(schema);
}
