import type { CompileResult } from './types';
import type { RecipeSpec } from '@superapp/core';
import { compileStyleVars, compileStyleCss, compileCustomCss, normalizeStyle } from './style-compiler';

const SECTION_KEY_PREFIX = 'sections/superapp-notification-bar-';

export function compileNotificationBar(spec: Extract<RecipeSpec, { type: 'theme.notificationBar' }>, themeId: string): CompileResult {
  const slugged = slug(spec.name);
  const sectionKey = `${SECTION_KEY_PREFIX}${slugged}.liquid`;
  const cssFile = `superapp-notification-bar-${slugged}.css`;
  const cssKey = `assets/${cssFile}`;
  const style = normalizeStyle(spec.style);
  const styleVars = compileStyleVars(style);
  const styleCss = compileStyleCss(style, '.superapp-note');

  const liquid = `
{% comment %} Generated by SuperApp. Do not edit directly. {% endcomment %}
{{ '${cssFile}' | asset_url | stylesheet_tag }}
<div class="superapp-note" data-dismissible="${spec.config.dismissible ? '1' : '0'}">
  <div class="superapp-note__inner">
    <span class="superapp-note__msg">${escapeHtml(spec.config.message)}</span>
    ${
      spec.config.linkText && spec.config.linkUrl
        ? `<a class="superapp-note__link" href="${escapeHtml(spec.config.linkUrl)}">${escapeHtml(spec.config.linkText)}</a>`
        : ''
    }
    ${
      spec.config.dismissible
        ? `<button class="superapp-note__close" type="button" aria-label="Dismiss">×</button>`
        : ''
    }
  </div>
</div>

<script>
(function(){
  var el = document.currentScript && document.currentScript.previousElementSibling;
  if(!el) return;
  var close = el.querySelector('.superapp-note__close');
  if(!close) return;
  var key = 'superapp_note_' + ${JSON.stringify(slugged)};
  try{ if(localStorage.getItem(key) === '1'){ el.remove(); return; } }catch(e){}
  close.addEventListener('click', function(){
    try{ localStorage.setItem(key, '1'); }catch(e){}
    el.remove();
  });
})();
</script>

{% schema %}
{
  "name": "${escapeJson(spec.name)}",
  "settings": [],
  "presets": [{ "name": "${escapeJson(spec.name)}" }]
}
{% endschema %}
`.trim();

  const css = `
.superapp-note {
${styleVars.split('\n').map((l) => '  ' + l).join('\n')}
}
${styleCss}
.superapp-note { position: sticky; top: 0; z-index: var(--sa-z); }
.superapp-note__inner { display:flex; gap: var(--sa-gap); align-items:center; justify-content: center; }
.superapp-note__link { color: var(--sa-text); text-decoration: underline; }
.superapp-note__close { margin-left: 8px; border: 0; background: transparent; color: inherit; font-size: 18px; cursor: pointer; }
@media (max-width: 749px) { .superapp-note { display: ${style.responsive.hideOnMobile ? 'none' : 'block'}; } }
@media (min-width: 750px) { .superapp-note { display: ${style.responsive.hideOnDesktop ? 'none' : 'block'}; } }
${compileCustomCss(style, '.superapp-note')}
`.trim();

  return {
    ops: [
      { kind: 'THEME_ASSET_UPSERT', themeId, key: sectionKey, value: liquid },
      { kind: 'THEME_ASSET_UPSERT', themeId, key: cssKey, value: css },
      { kind: 'AUDIT', action: 'compile.theme.notificationBar', details: JSON.stringify({ sectionKey, cssKey }) },
    ],
    compiledJson: JSON.stringify({ sectionKey, cssKey }),
  };
}

function slug(input: string) {
  return input.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '').slice(0, 40);
}

function escapeJson(input: string) {
  return input.replace(/\\/g, '\\\\').replace(/"/g, '\"');
}

function escapeHtml(input: string) {
  return input
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}
