import type { CompileResult } from './types';
import type { RecipeSpec } from '@superapp/core';
import { compileStyleVars, compileStyleCss, compileCustomCss, normalizeStyle } from './style-compiler';

const SECTION_KEY_PREFIX = 'sections/superapp-banner-';

export function compileThemeBanner(spec: Extract<RecipeSpec, { type: 'theme.banner' }>, themeId: string): CompileResult {
  const slugged = slug(spec.name);
  const sectionKey = `${SECTION_KEY_PREFIX}${slugged}.liquid`;
  const cssFile = `superapp-banner-${slugged}.css`;
  const cssKey = `assets/${cssFile}`;
  const style = normalizeStyle(spec.style);
  const styleVars = compileStyleVars(style);
  const styleCss = compileStyleCss(style, '.superapp-banner');

  const liquid = `
{% comment %} Generated by SuperApp. Do not edit directly. {% endcomment %}
{{ '${cssFile}' | asset_url | stylesheet_tag }}
<section class="superapp-banner" role="region" aria-label="{{ section.settings.heading | escape }}">
  <div class="superapp-banner__inner">
    <div class="superapp-banner__content">
      <h2 class="superapp-banner__heading">{{ section.settings.heading | escape }}</h2>
      {% if section.settings.subheading != blank %}
        <p class="superapp-banner__subheading">{{ section.settings.subheading | escape }}</p>
      {% endif %}
      {% if section.settings.cta_text != blank and section.settings.cta_url != blank %}
        <a class="superapp-banner__cta" href="{{ section.settings.cta_url }}">{{ section.settings.cta_text | escape }}</a>
      {% endif %}
    </div>
    {% if section.settings.image_url != blank %}
      <img class="superapp-banner__image" src="{{ section.settings.image_url | escape }}" alt="" loading="lazy" width="800" height="400">
    {% endif %}
  </div>
</section>

{% schema %}
${schemaJson(spec)}
{% endschema %}
`.trim();

  const css = `
.superapp-banner {
${styleVars.split('\n').map((l) => '  ' + l).join('\n')}
}
${styleCss}
.superapp-banner__inner { display:flex; gap: var(--sa-gap); align-items:center; }
.superapp-banner__content { max-width: 720px; }
.superapp-banner__heading { margin: 0 0 8px; font-size: 1.25em; line-height: var(--sa-lh); font-weight: var(--sa-fw); }
.superapp-banner__subheading { margin: 0 0 12px; opacity: 0.85; }
.superapp-banner__cta { display:inline-block; padding: 10px 14px; border: 1px solid currentColor; text-decoration:none; border-radius: var(--sa-radius); background: var(--sa-btn-bg, transparent); color: var(--sa-btn-text, var(--sa-text)); }
.superapp-banner__image { max-width: 420px; height: auto; border-radius: var(--sa-radius); }
@media (max-width: 900px) { .superapp-banner__inner { flex-direction: column; align-items:flex-start; } .superapp-banner__image{ max-width:100%; } }
@media (max-width: 749px) { .superapp-banner { display: ${style.responsive.hideOnMobile ? 'none' : 'block'}; } }
@media (min-width: 750px) { .superapp-banner { display: ${style.responsive.hideOnDesktop ? 'none' : 'block'}; } }
${compileCustomCss(style, '.superapp-banner')}
`.trim();

  return {
    ops: [
      { kind: 'THEME_ASSET_UPSERT', themeId, key: sectionKey, value: liquid },
      { kind: 'THEME_ASSET_UPSERT', themeId, key: cssKey, value: css },
      { kind: 'AUDIT', action: 'compile.theme.banner', details: JSON.stringify({ sectionKey, cssKey }) },
    ],
    compiledJson: JSON.stringify({ sectionKey, cssKey }),
  };
}

function slug(input: string) {
  return input.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '').slice(0, 40);
}

function escapeJson(input: string) {
  return input.replace(/\\/g, '\\\\').replace(/"/g, '\"');
}

function schemaJson(spec: Extract<RecipeSpec, { type: 'theme.banner' }>): string {
  const schema: Record<string, unknown> = {
    name: spec.name,
    settings: [
      { type: 'text', id: 'heading', label: 'Heading', default: spec.config.heading },
      { type: 'text', id: 'subheading', label: 'Subheading', default: spec.config.subheading ?? '' },
      { type: 'text', id: 'cta_text', label: 'CTA text', default: spec.config.ctaText ?? '' },
      { type: 'url', id: 'cta_url', label: 'CTA link', default: spec.config.ctaUrl ?? '' },
      { type: 'text', id: 'image_url', label: 'Image URL', default: spec.config.imageUrl ?? '' },
    ],
    presets: [{ name: spec.name }],
  };
  if (spec.placement?.enabled_on) {
    schema.enabled_on = spec.placement.enabled_on;
  } else if (spec.placement?.disabled_on) {
    schema.disabled_on = spec.placement.disabled_on;
  }
  return JSON.stringify(schema);
}
