import type { CompileResult } from './types';
import type { RecipeSpec } from '@superapp/core';
import { compileStyleVars, compileCustomCss, normalizeStyle } from './style-compiler';

const SECTION_KEY_PREFIX = 'sections/superapp-effect-';

export function compileThemeEffect(spec: Extract<RecipeSpec, { type: 'theme.effect' }>, themeId: string): CompileResult {
  const slugged = slug(spec.name);
  const sectionKey = `${SECTION_KEY_PREFIX}${slugged}.liquid`;
  const cssFile = `superapp-effect-${slugged}.css`;
  const cssKey = `assets/${cssFile}`;
  const style = normalizeStyle(spec.style);
  const styleVars = compileStyleVars(style);
  const reducedMotion = style.accessibility.reducedMotion ?? true;
  const effectKind = spec.config.effectKind;
  const intensity = spec.config.intensity ?? 'medium';
  const speed = spec.config.speed ?? 'normal';

  const particleCount = intensity === 'low' ? 30 : intensity === 'high' ? 80 : 50;
  const durationSec = speed === 'slow' ? 12 : speed === 'fast' ? 6 : 9;

  const liquid = `
{% comment %} Generated by SuperApp. Do not edit directly. theme.effect overlay. {% endcomment %}
{{ '${cssFile}' | asset_url | stylesheet_tag }}
<div class="superapp-effect" role="presentation" aria-hidden="true">
  <div class="superapp-effect__overlay">
{% for i in (1..${particleCount}) %}
    <div class="superapp-effect__particle superapp-effect__particle--${effectKind}" style="--i: {{ i }}; --total: ${particleCount};"></div>
{% endfor %}
  </div>
</div>

{% schema %}
${schemaJson(spec)}
{% endschema %}
`.trim();

  const fallAnimation =
    effectKind === 'snowfall'
      ? `
@keyframes superapp-effect-fall {
  0% { transform: translateY(-10vh) translateX(0); opacity: 0.9; }
  100% { transform: translateY(100vh) translateX(5vw); opacity: 0.7; }
}`
      : `
@keyframes superapp-effect-fall {
  0% { transform: translateY(-10vh) translateX(0) rotate(0deg); opacity: 1; }
  100% { transform: translateY(100vh) translateX(15vw) rotate(720deg); opacity: 0.8; }
}`;

  const particleCss =
    effectKind === 'snowfall'
      ? `
  width: 8px;
  height: 8px;
  border-radius: 50%;
  background: rgba(255, 255, 255, 0.9);
  box-shadow: 0 0 6px rgba(255,255,255,0.8);`
      : `
  width: 10px;
  height: 10px;
  border-radius: 2px;
  background: hsl(calc(var(--i) * 37), 80%, 60%);`;

  const animationRule = reducedMotion
    ? `
.superapp-effect__particle { animation: none; opacity: 0.3; }`
    : `
.superapp-effect__particle {
  animation: superapp-effect-fall ${durationSec}s linear infinite;
  animation-delay: calc(-1s * (var(--i) / var(--total)) * ${durationSec});
}`;

  const css = `
.superapp-effect {
  position: fixed;
  inset: 0;
  pointer-events: none;
  z-index: var(--sa-z, 1000);
}
.superapp-effect__overlay {
  position: absolute;
  inset: 0;
  overflow: hidden;
}
.superapp-effect {
${styleVars.split('\n').map((l) => '  ' + l).join('\n')}
}
.superapp-effect__particle {
  position: absolute;
  left: calc((var(--i) / var(--total)) * 100%);
  top: -20px;
${particleCss}
}
${fallAnimation}
${animationRule}
@media (max-width: 749px) { .superapp-effect { display: ${style.responsive.hideOnMobile ? 'none' : 'block'}; } }
@media (min-width: 750px) { .superapp-effect { display: ${style.responsive.hideOnDesktop ? 'none' : 'block'}; } }
@media (prefers-reduced-motion: reduce) {
  .superapp-effect__particle { animation: none !important; opacity: 0.25; }
}
${compileCustomCss(style, '.superapp-effect')}
`.trim();

  return {
    ops: [
      { kind: 'THEME_ASSET_UPSERT', themeId, key: sectionKey, value: liquid },
      { kind: 'THEME_ASSET_UPSERT', themeId, key: cssKey, value: css },
      { kind: 'AUDIT', action: 'compile.theme.effect', details: JSON.stringify({ sectionKey, cssKey }) },
    ],
    compiledJson: JSON.stringify({ sectionKey, cssKey }),
  };
}

function slug(input: string) {
  return input.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '').slice(0, 40);
}

function schemaJson(spec: Extract<RecipeSpec, { type: 'theme.effect' }>): string {
  const schema: Record<string, unknown> = {
    name: spec.name,
    settings: [
      { type: 'text', id: 'effect_kind', label: 'Effect kind', default: spec.config.effectKind },
      { type: 'text', id: 'intensity', label: 'Intensity', default: spec.config.intensity ?? 'medium' },
      { type: 'text', id: 'speed', label: 'Speed', default: spec.config.speed ?? 'normal' },
    ],
    presets: [{ name: spec.name }],
  };
  if (spec.placement?.enabled_on) {
    schema.enabled_on = spec.placement.enabled_on;
  } else if (spec.placement?.disabled_on) {
    schema.disabled_on = spec.placement.disabled_on;
  }
  return JSON.stringify(schema);
}
