import type { TemplateEntry } from '../types.js';
import { THEME_PLACEABLE_TEMPLATES } from '../../allowed-values.js';

/**
 * App-embed-on-body overlay sections (activation: 'overlay' | 'global').
 *
 * These are the site-wide, script-injected storefront layer that Privy / Justuno /
 * ProveSource / Swym / Appikon ship as a theme app EMBED (rendered into the page BODY,
 * not a per-page block): centered modal popups, corner flyouts/toasts, sticky bars,
 * spin-to-win wheels, floating action buttons, and social-proof pops. Each is authored
 * as one `theme.section` with `config.activation: 'overlay'` (dimmed-modal / corner
 * overlays) or `'global'` (persistent site-wide bars/floating widgets), the repeatable
 * content in `config.blocks[]`, and a full storefront `style` object grounded in each
 * app's real visual_patterns (corner anchors, dimmed backdrops, per-breakpoint hide).
 *
 * Honesty: overlay copy/behavior reflects the REAL apps' controls (trigger tokens,
 * frequency caps, corner positions, form fields). The live app-embed EMIT path is a
 * pending storefront build (034 plan gap #7); these specs are valid + authorable today
 * and compile to the app-block/metaobject model — they do not imply a shipped site-wide
 * emit. No fabricated targets/kinds/enums; every value resolves against recipe.ts +
 * allowed-values.ts as they stand.
 */
export const EMB_BODY_TEMPLATES: TemplateEntry[] = [
  // 01 — Privy centered email-capture popup with coupon reveal (exit-intent).
  {
    id: 'EMB-BODY-01',
    name: 'Privy Email Popup — Coupon Reveal',
    description: 'Site-wide centered modal popup that captures email and reveals a discount code, fired on exit intent with a dimmed backdrop — the classic Privy welcome-offer overlay.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'popup',
    tags: ['privy', 'popup', 'email-capture', 'overlay', 'coupon', 'exit-intent'],
    spec: {
      type: 'theme.section',
      name: 'Privy Email Popup — Coupon Reveal',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'popup',
        activation: 'overlay',
        title: 'Get 10% off your first order',
        subtitle: 'Join the list — we will send your code instantly.',
        layout: { layout: 'stacked' },
        trigger: 'ON_EXIT_INTENT',
        frequency: 'ONCE_PER_SESSION',
        showOnPages: 'ALL',
        maxShowsPerDay: 1,
        showCloseButton: true,
        countdownEnabled: false,
        fields: {
          emailFieldEnabled: true,
          emailPlaceholder: 'you@email.com',
          consentText: 'By signing up you agree to receive email marketing.',
          ctaLabel: 'Reveal my code',
          successMessage: 'Your code is WELCOME10 — copied to your clipboard.',
          couponCode: 'WELCOME10',
          dismissLabel: 'No thanks',
        },
        blocks: [
          { kind: 'field', text: 'Email address', fields: { input: 'email', required: true } },
          { kind: 'field', text: 'Phone (optional)', fields: { input: 'phone', required: false } },
        ],
      },
      placement: { enabled_on: { templates: ['index', 'product', 'collection'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'overlay', anchor: 'center', offsetX: 0, offsetY: 0, width: 'narrow', zIndex: 'modal' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: 'LG', weight: 'bold', lineHeight: 'normal', align: 'center' },
        colors: { overlayBackdrop: '#000000', overlayBackdropOpacity: 0.6, seed: '#7c3aed' },
        shape: { radius: 'lg', borderWidth: 'none', shadow: 'lg', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'base', easing: 'enter' },
        pack: 'bold',
      },
    },
  },

  // 02 — Privy top announcement / free-shipping bar (persistent, site-wide).
  {
    id: 'EMB-BODY-02',
    name: 'Privy Free-Shipping Bar',
    description: 'Persistent site-wide announcement bar pinned to the top of every page, promoting a free-shipping threshold — Privy\'s dismissible free-shipping / announcement bar embed.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'announcement',
    tags: ['privy', 'announcement-bar', 'free-shipping', 'global', 'promo', 'sticky'],
    spec: {
      type: 'theme.section',
      name: 'Privy Free-Shipping Bar',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'notification-bar',
        activation: 'global',
        title: 'Free shipping on orders over $50',
        layout: { layout: 'stacked' },
        trigger: 'ON_LOAD',
        frequency: 'EVERY_VISIT',
        showOnPages: 'ALL',
        fields: {
          message: 'Free shipping on orders over $50 — shop now.',
          ctaLabel: 'Shop bestsellers',
          ctaUrl: 'https://example.com/collections/best-sellers',
          dismissible: true,
          position: 'top',
        },
        blocks: [
          { kind: 'message', text: 'Free shipping on orders over $50', url: 'https://example.com/collections/best-sellers' },
        ],
      },
      placement: { enabled_on: { groups: ['header'] } },
      style: {
        layout: { mode: 'sticky', anchor: 'top', offsetX: 0, offsetY: 0, width: 'full', zIndex: 'sticky' },
        spacing: { padding: 'tight', margin: 'none', gap: 'tight', density: 'compact' },
        typography: { size: 'SM', weight: 'medium', lineHeight: 'normal', align: 'center' },
        colors: { text: '#ffffff', background: '#111827', overlayBackdropOpacity: 0.45, seed: '#e07856' },
        shape: { radius: 'none', borderWidth: 'none', shadow: 'none' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        pack: 'luxe',
      },
    },
  },

  // 03 — Privy spin-to-win wheel (gamified email capture overlay).
  {
    id: 'EMB-BODY-03',
    name: 'Privy Spin-to-Win Wheel',
    description: 'Gamified site-wide overlay with a prize wheel of coupon slices that requires an email to spin — Privy\'s spin-to-win email-capture display with per-slice odds.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'game',
    tags: ['privy', 'spin-to-win', 'gamified', 'overlay', 'email-capture', 'coupon'],
    spec: {
      type: 'theme.section',
      name: 'Privy Spin-to-Win Wheel',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'popup',
        activation: 'overlay',
        title: 'Spin to win a discount',
        subtitle: 'Enter your email for one spin.',
        layout: { layout: 'stacked' },
        trigger: 'TIMED',
        frequency: 'ONCE_PER_WEEK',
        showOnPages: 'HOMEPAGE',
        maxShowsPerDay: 1,
        showCloseButton: true,
        countdownEnabled: false,
        fields: {
          emailFieldEnabled: true,
          emailPlaceholder: 'Enter your email to spin',
          ctaLabel: 'Spin the wheel',
          dismissLabel: 'Maybe later',
          timedDelaySeconds: 5,
        },
        blocks: [
          { kind: 'slice', text: '10% off', fields: { couponCode: 'SPIN10', oddsWeight: 30 } },
          { kind: 'slice', text: '15% off', fields: { couponCode: 'SPIN15', oddsWeight: 20 } },
          { kind: 'slice', text: 'Free shipping', fields: { couponCode: 'SPINSHIP', oddsWeight: 20 } },
          { kind: 'slice', text: '5% off', fields: { couponCode: 'SPIN5', oddsWeight: 25 } },
          { kind: 'slice', text: 'No luck — try again', fields: { couponCode: '', oddsWeight: 5 } },
        ],
      },
      placement: { enabled_on: { templates: ['index'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'overlay', anchor: 'center', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'modal' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: 'XL', weight: 'bold', lineHeight: 'normal', align: 'center' },
        colors: { overlayBackdrop: '#000000', overlayBackdropOpacity: 0.65, seed: '#d97706' },
        shape: { radius: 'xl', borderWidth: 'none', shadow: 'lg', elevation: 'glow' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'slow', easing: 'enter' },
        pack: 'bold',
      },
    },
  },

  // 04 — Justuno exit-intent lightbox popup with discount.
  {
    id: 'EMB-BODY-04',
    name: 'Justuno Exit-Intent Lightbox',
    description: 'Center lightbox popup with a dark overlay that fires on exit intent to present a discount and email form — Justuno\'s layered-canvas lightbox promotion.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'popup',
    tags: ['justuno', 'popup', 'exit-intent', 'overlay', 'lightbox', 'email-capture'],
    spec: {
      type: 'theme.section',
      name: 'Justuno Exit-Intent Lightbox',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'popup',
        activation: 'overlay',
        title: 'Wait — take 15% off',
        subtitle: 'Before you go, grab a code for your cart.',
        layout: { layout: 'stacked' },
        trigger: 'ON_EXIT_INTENT',
        frequency: 'ONCE_PER_DAY',
        showOnPages: 'ALL',
        maxShowsPerDay: 1,
        showCloseButton: true,
        countdownEnabled: false,
        fields: {
          emailFieldEnabled: true,
          emailPlaceholder: 'Email for your code',
          ctaLabel: 'Get 15% off',
          clickAction: 'submit-form',
          dismissLabel: 'No thanks, I\'ll pay full price',
          couponCode: 'STAY15',
        },
        blocks: [
          { kind: 'field', text: 'Email', fields: { input: 'email', required: true } },
        ],
      },
      placement: { enabled_on: { templates: ['cart', 'product', 'collection'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'overlay', anchor: 'center', offsetX: 0, offsetY: 0, width: 'narrow', zIndex: 'modal' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: 'LG', weight: 'bold', lineHeight: 'normal', align: 'center' },
        colors: { overlayBackdrop: '#0f172a', overlayBackdropOpacity: 0.7, seed: '#2563eb' },
        shape: { radius: 'md', borderWidth: 'none', shadow: 'lg', elevation: 'soft' },
        responsive: { hideOnMobile: true, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'fast', easing: 'enter' },
        pack: 'bold',
      },
    },
  },

  // 05 — Justuno corner slide-in / flyout email capture.
  {
    id: 'EMB-BODY-05',
    name: 'Justuno Corner Slide-In',
    description: 'Bottom-corner slide-in flyout capturing email after a scroll trigger, non-blocking so shopping continues — Justuno\'s corner-anchored slide-in promotion.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'flyout',
    tags: ['justuno', 'flyout', 'slide-in', 'overlay', 'email-capture', 'scroll'],
    spec: {
      type: 'theme.section',
      name: 'Justuno Corner Slide-In',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'floatingWidget',
        activation: 'overlay',
        title: 'Save 10% today',
        subtitle: 'Sign up and we\'ll email your code.',
        layout: { layout: 'stacked' },
        trigger: 'ON_SCROLL_50',
        frequency: 'ONCE_PER_SESSION',
        showOnPages: 'ALL',
        fields: {
          emailFieldEnabled: true,
          emailPlaceholder: 'you@email.com',
          ctaLabel: 'Send my code',
          clickAction: 'submit-form',
          dismissible: true,
          corner: 'bottom-right',
        },
        blocks: [
          { kind: 'field', text: 'Email', fields: { input: 'email', required: true } },
        ],
      },
      placement: { enabled_on: { templates: ['index', 'product', 'collection', 'blog', 'article'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'floating', anchor: 'bottom', offsetX: -24, offsetY: -24, width: 'narrow', zIndex: 'overlay' },
        spacing: { padding: 'medium', margin: 'none', gap: 'tight', density: 'comfortable' },
        typography: { size: 'MD', weight: 'medium', lineHeight: 'normal', align: 'left' },
        colors: { overlayBackdropOpacity: 0.45, seed: '#2563eb' },
        shape: { radius: 'lg', borderWidth: 'thin', shadow: 'md', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'base', easing: 'enter' },
        pack: 'bold',
      },
    },
  },

  // 06 — Justuno gamified "mystery offer" tab teaser (persistent floating trigger).
  {
    id: 'EMB-BODY-06',
    name: 'Justuno Offer Tab Teaser',
    description: 'Persistent floating side-tab teaser that stays docked at the screen edge and opens an offer frame on click — Justuno\'s minimized "tab" trigger for a promotion.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'tab',
    tags: ['justuno', 'floating-tab', 'teaser', 'global', 'promo', 'click'],
    spec: {
      type: 'theme.section',
      name: 'Justuno Offer Tab Teaser',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'floatingWidget',
        activation: 'global',
        title: 'Unlock your offer',
        layout: { layout: 'stacked' },
        trigger: 'ON_CLICK',
        frequency: 'EVERY_VISIT',
        showOnPages: 'ALL',
        fields: {
          teaserLabel: 'Offers',
          ctaLabel: 'Open offer',
          clickAction: 'link-to-frame',
          corner: 'left',
        },
        blocks: [
          { kind: 'message', text: 'Tap to reveal today\'s deal' },
        ],
      },
      placement: { enabled_on: { templates: ['index', 'product', 'collection'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'floating', anchor: 'left', offsetX: 0, offsetY: 0, width: 'auto', zIndex: 'overlay' },
        spacing: { padding: 'tight', margin: 'none', gap: 'none', density: 'compact' },
        typography: { size: 'SM', weight: 'bold', lineHeight: 'normal', align: 'center' },
        colors: { text: '#ffffff', background: '#7c3aed', overlayBackdropOpacity: 0.45, seed: '#7c3aed' },
        shape: { radius: 'md', borderWidth: 'none', shadow: 'md', elevation: 'soft' },
        responsive: { hideOnMobile: true, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'fast', easing: 'standard' },
        pack: 'bold',
      },
    },
  },

  // 07 — ProveSource sales-pop toast (social proof stream).
  {
    id: 'EMB-BODY-07',
    name: 'ProveSource Sales Pop Toast',
    description: 'Corner social-proof toast that streams recent-purchase notifications with an avatar and location line, looped and auto-dismissed — ProveSource\'s Stream sales pop.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'notification',
    tags: ['provesource', 'social-proof', 'toast', 'global', 'sales-pop', 'fomo'],
    spec: {
      type: 'theme.section',
      name: 'ProveSource Sales Pop Toast',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'floatingWidget',
        activation: 'global',
        title: 'Recent purchases',
        layout: { layout: 'stacked' },
        trigger: 'ON_LOAD',
        frequency: 'EVERY_VISIT',
        showOnPages: 'ALL',
        fields: {
          corner: 'bottom-left',
          delayBeforeFirstSeconds: 3,
          delayBetweenSeconds: 5,
          displayForSeconds: 6,
          loop: true,
          randomOrder: true,
          showMapIcon: true,
        },
        blocks: [
          { kind: 'message', text: 'Maya from Austin, TX just bought the Everyday Tote', imageUrl: 'https://cdn.example.com/proof/avatar-1.jpg', url: 'https://example.com/products/everyday-tote' },
          { kind: 'message', text: 'Devon from Seattle, WA just bought the Trail Bottle', imageUrl: 'https://cdn.example.com/proof/avatar-2.jpg', url: 'https://example.com/products/trail-bottle' },
          { kind: 'message', text: 'Priya from Denver, CO just bought the Wool Beanie', imageUrl: 'https://cdn.example.com/proof/avatar-3.jpg', url: 'https://example.com/products/wool-beanie' },
        ],
      },
      placement: { enabled_on: { templates: ['index', 'product', 'collection'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'floating', anchor: 'bottom', offsetX: 24, offsetY: -24, width: 'narrow', zIndex: 'overlay' },
        spacing: { padding: 'tight', margin: 'none', gap: 'tight', density: 'compact' },
        typography: { size: 'SM', weight: 'normal', lineHeight: 'normal', align: 'left' },
        colors: { overlayBackdropOpacity: 0.45, seed: '#10b981' },
        shape: { radius: 'full', borderWidth: 'thin', shadow: 'md', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'base', easing: 'enter' },
        pack: 'luxe',
      },
    },
  },

  // 08 — ProveSource live-visitor counter pill (persistent badge).
  {
    id: 'EMB-BODY-08',
    name: 'ProveSource Live Visitor Counter',
    description: 'Compact corner pill showing a live "X people are viewing" count as social proof, pinned site-wide — ProveSource\'s Live-visitors notification.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'counter',
    tags: ['provesource', 'social-proof', 'live-visitors', 'global', 'counter', 'fomo'],
    spec: {
      type: 'theme.section',
      name: 'ProveSource Live Visitor Counter',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'floatingWidget',
        activation: 'global',
        title: 'Live viewers',
        layout: { layout: 'stacked' },
        trigger: 'ON_LOAD',
        frequency: 'EVERY_VISIT',
        showOnPages: 'PRODUCT',
        fields: {
          corner: 'bottom-right',
          messageTemplate: '{{count}} people are viewing this right now',
          window: '24h',
          minimumLimit: 3,
          displayForSeconds: 8,
        },
        blocks: [
          { kind: 'stat', text: '{{count}}', fields: { label: 'viewing now', metric: 'live_visitors', window: '24h' } },
        ],
      },
      placement: { enabled_on: { templates: ['product'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'floating', anchor: 'bottom', offsetX: -24, offsetY: -24, width: 'auto', zIndex: 'overlay' },
        spacing: { padding: 'tight', margin: 'none', gap: 'none', density: 'compact' },
        typography: { size: 'XS', weight: 'medium', lineHeight: 'tight', align: 'left' },
        colors: { overlayBackdropOpacity: 0.45, seed: '#10b981' },
        shape: { radius: 'full', borderWidth: 'thin', shadow: 'sm', elevation: 'border' },
        responsive: { hideOnMobile: true, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'fast', easing: 'enter' },
        pack: 'luxe',
      },
    },
  },

  // 09 — Swym wishlist launch-point floating button (persistent FAB).
  {
    id: 'EMB-BODY-09',
    name: 'Swym Wishlist Floating Button',
    description: 'Persistent floating heart button pinned to a screen corner with a saved-item counter that opens the wishlist page or drawer — Swym\'s Launch Point floating button.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'wishlist',
    tags: ['swym', 'wishlist', 'floating-button', 'global', 'launch-point', 'save-for-later'],
    spec: {
      type: 'theme.section',
      name: 'Swym Wishlist Floating Button',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'floatingWidget',
        activation: 'global',
        title: 'Wishlist',
        layout: { layout: 'stacked' },
        trigger: 'ON_LOAD',
        frequency: 'EVERY_VISIT',
        showOnPages: 'ALL',
        fields: {
          icon: 'heart',
          showItemCounter: true,
          corner: 'bottom-right',
          clickAction: 'open-wishlist',
          launchPointLabel: 'My wishlist',
        },
        blocks: [
          { kind: 'message', text: 'View saved items' },
        ],
      },
      placement: { enabled_on: { templates: ['index', 'product', 'collection', 'cart'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'floating', anchor: 'bottom', offsetX: -20, offsetY: -20, width: 'auto', zIndex: 'sticky' },
        spacing: { padding: 'tight', margin: 'none', gap: 'none', density: 'compact' },
        typography: { size: 'SM', weight: 'medium', lineHeight: 'normal', align: 'center' },
        colors: { text: '#ffffff', background: '#e11d48', overlayBackdropOpacity: 0.45, seed: '#e11d48' },
        shape: { radius: 'full', borderWidth: 'none', shadow: 'md', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'fast', easing: 'standard' },
        pack: 'bold',
      },
    },
  },

  // 10 — Appikon back-in-stock "Notify Me" overlay form.
  {
    id: 'EMB-BODY-10',
    name: 'Appikon Notify-Me Overlay',
    description: 'Overlay signup form for out-of-stock variants that captures email (and phone for SMS) to join the restock waitlist — Appikon\'s "Notify Me When Available" popup.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'back-in-stock',
    tags: ['appikon', 'back-in-stock', 'notify-me', 'overlay', 'waitlist', 'product'],
    spec: {
      type: 'theme.section',
      name: 'Appikon Notify-Me Overlay',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'popup',
        activation: 'overlay',
        title: 'Notify me when available',
        subtitle: 'We\'ll email you the moment this is back in stock.',
        layout: { layout: 'stacked' },
        trigger: 'ON_CLICK',
        frequency: 'EVERY_VISIT',
        showOnPages: 'PRODUCT',
        maxShowsPerDay: 1,
        showCloseButton: true,
        countdownEnabled: false,
        fields: {
          emailFieldEnabled: true,
          emailPlaceholder: 'you@email.com',
          phoneFieldEnabled: true,
          phonePlaceholder: 'Phone for SMS (optional)',
          ctaLabel: 'Notify me',
          successMessage: 'You\'re on the list — we\'ll alert you when it restocks.',
          variantLevel: true,
        },
        blocks: [
          { kind: 'field', text: 'Email', fields: { input: 'email', required: true } },
          { kind: 'field', text: 'Phone', fields: { input: 'phone', required: false } },
        ],
      },
      placement: { enabled_on: { templates: ['product', 'collection'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'overlay', anchor: 'center', offsetX: 0, offsetY: 0, width: 'narrow', zIndex: 'modal' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: 'MD', weight: 'medium', lineHeight: 'normal', align: 'left' },
        colors: { overlayBackdrop: '#000000', overlayBackdropOpacity: 0.55, seed: '#4f46e5' },
        shape: { radius: 'lg', borderWidth: 'none', shadow: 'lg', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'base', easing: 'enter' },
        pack: 'luxe',
      },
    },
  },

  // 11 — Wheelio/Privy-class scratch-card discount popup (email-gated reveal, exit-intent).
  {
    id: 'EMB-BODY-11',
    name: 'Wheelio Scratch-Card Coupon Popup',
    description: 'Gamified site-wide overlay with a scratch-off panel that reveals a discount code, gated behind an email capture and fired on exit intent — the Wheelio/Privy scratch-card email-capture display. The email is required before the panel unlocks, so the code is only revealed to opted-in shoppers.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'game',
    tags: ['wheelio', 'privy', 'scratch-card', 'gamified', 'overlay', 'email-capture', 'coupon', 'exit-intent'],
    spec: {
      type: 'theme.section',
      name: 'Wheelio Scratch-Card Coupon Popup',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'popup',
        activation: 'overlay',
        title: 'Scratch to reveal your discount',
        subtitle: 'Enter your email, then scratch the panel for a surprise code.',
        layout: { layout: 'stacked' },
        trigger: 'ON_EXIT_INTENT',
        frequency: 'ONCE_PER_SESSION',
        showOnPages: 'ALL',
        maxShowsPerDay: 1,
        showCloseButton: true,
        countdownEnabled: false,
        fields: {
          emailFieldEnabled: true,
          emailPlaceholder: 'Enter your email to play',
          consentText: 'By playing you agree to receive email marketing.',
          ctaLabel: 'Reveal my prize',
          scratchHint: 'Scratch the silver panel to reveal your code.',
          successMessage: 'Your code is copied to your clipboard — apply it at checkout.',
          dismissLabel: 'No thanks, I\'ll pay full price',
        },
        blocks: [
          { kind: 'scratch', text: 'Mystery 15% off', fields: { couponCode: 'SCRATCH15' } },
          { kind: 'field', text: 'Email address', fields: { input: 'email', required: true } },
        ],
      },
      placement: { enabled_on: { templates: ['index', 'product', 'collection'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'overlay', anchor: 'center', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'modal' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: 'XL', weight: 'bold', lineHeight: 'normal', align: 'center' },
        colors: { overlayBackdrop: '#000000', overlayBackdropOpacity: 0.65, seed: '#db2777' },
        shape: { radius: 'xl', borderWidth: 'none', shadow: 'lg', elevation: 'glow' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'base', easing: 'enter' },
        pack: 'bold',
      },
    },
  },

  // 12 — First-order welcome scratch card (no email gate, immediate reveal, timed).
  {
    id: 'EMB-BODY-12',
    name: 'Welcome Scratch Card — First Order',
    description: 'A refined first-visit welcome overlay with a scratch-off panel that reveals a welcome discount with no email gate — the shopper simply scratches to unlock the code, fired after a short delay on the homepage. Optimized for a low-friction first-order incentive.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'game',
    tags: ['scratch-card', 'gamified', 'overlay', 'welcome-offer', 'first-order', 'coupon', 'no-email'],
    spec: {
      type: 'theme.section',
      name: 'Welcome Scratch Card — First Order',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'popup',
        activation: 'overlay',
        title: 'A little welcome gift',
        subtitle: 'Scratch the panel to unlock your first-order discount.',
        layout: { layout: 'stacked' },
        trigger: 'TIMED',
        frequency: 'ONCE_PER_SESSION',
        showOnPages: 'HOMEPAGE',
        maxShowsPerDay: 1,
        showCloseButton: true,
        countdownEnabled: false,
        fields: {
          emailFieldEnabled: false,
          ctaLabel: 'Reveal my gift',
          scratchHint: 'Scratch to reveal your welcome code.',
          successMessage: 'Your welcome code is copied — apply it at checkout.',
          dismissLabel: 'Maybe later',
          timedDelaySeconds: 6,
        },
        blocks: [
          { kind: 'scratch', text: 'Welcome — 10% off', fields: { couponCode: 'WELCOME10' } },
        ],
      },
      placement: { enabled_on: { templates: ['index'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'overlay', anchor: 'center', offsetX: 0, offsetY: 0, width: 'narrow', zIndex: 'modal' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: 'LG', weight: 'medium', lineHeight: 'normal', align: 'center' },
        colors: { overlayBackdrop: '#0f172a', overlayBackdropOpacity: 0.55, seed: '#0f766e' },
        shape: { radius: 'lg', borderWidth: 'none', shadow: 'lg', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'base', easing: 'enter' },
        pack: 'luxe',
      },
    },
  },

  // 13 — Holiday/sale multi-prize spin-to-win wheel (6 slices incl. one no-prize, email-gated).
  {
    id: 'EMB-BODY-13',
    name: 'Holiday Spin-to-Win Wheel — Multi-Prize',
    description: 'A festive multi-prize spin-to-win overlay with six weighted coupon slices (including an honest no-prize wedge) that requires an email to spin — a holiday/sale edition of the gamified email-capture wheel. Rarer high-value prizes carry lower odds; the empty slice is a genuine try-again with no code.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'game',
    tags: ['privy', 'spin-to-win', 'gamified', 'overlay', 'email-capture', 'coupon', 'holiday', 'sale', 'multi-prize'],
    spec: {
      type: 'theme.section',
      name: 'Holiday Spin-to-Win Wheel — Multi-Prize',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'popup',
        activation: 'overlay',
        title: 'Spin for your holiday deal',
        subtitle: 'Enter your email for one spin — six prizes on the wheel.',
        layout: { layout: 'stacked' },
        trigger: 'TIMED',
        frequency: 'ONCE_PER_WEEK',
        showOnPages: 'ALL',
        maxShowsPerDay: 1,
        showCloseButton: true,
        countdownEnabled: false,
        fields: {
          emailFieldEnabled: true,
          emailPlaceholder: 'Enter your email to spin',
          consentText: 'By signing up you agree to receive email marketing.',
          ctaLabel: 'Spin the wheel',
          successMessage: 'Your holiday code is copied to your clipboard — apply it at checkout.',
          dismissLabel: 'Maybe later',
          timedDelaySeconds: 5,
        },
        blocks: [
          { kind: 'slice', text: '25% off', fields: { couponCode: 'HOLIDAY25', oddsWeight: 10 } },
          { kind: 'slice', text: '20% off', fields: { couponCode: 'HOLIDAY20', oddsWeight: 15 } },
          { kind: 'slice', text: '15% off', fields: { couponCode: 'HOLIDAY15', oddsWeight: 20 } },
          { kind: 'slice', text: 'Free shipping', fields: { couponCode: 'HOLIDAYSHIP', oddsWeight: 20 } },
          { kind: 'slice', text: '10% off', fields: { couponCode: 'HOLIDAY10', oddsWeight: 25 } },
          { kind: 'slice', text: 'No luck — try again', fields: { couponCode: '', oddsWeight: 10 } },
        ],
      },
      placement: { enabled_on: { templates: ['index', 'collection'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'overlay', anchor: 'center', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'modal' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: 'XL', weight: 'bold', lineHeight: 'normal', align: 'center' },
        colors: { overlayBackdrop: '#000000', overlayBackdropOpacity: 0.7, seed: '#b91c1c' },
        shape: { radius: 'xl', borderWidth: 'none', shadow: 'lg', elevation: 'glow' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'slow', easing: 'enter' },
        pack: 'bold',
      },
    },
  },
];
