/**
 * themeblock-content-page-fullsection — 22 FULL-SECTION theme.section app-block
 * designs for the content-page templates (page / blog / article / password / 404).
 *
 * These are the landing/marketing full-width sections a merchant drops onto a
 * custom page, a blog index, an article body, the coming-soon (password) page, or
 * a 404 — hero bands, countdown launch sections, and inline opt-in captures. They
 * are grounded in the real controls of the corpus page-builders + capture apps:
 *   - PageFly / GemPages     → hero / rich-content / feature / CTA landing sections,
 *                              slot-published into page / blog / article templates.
 *   - Hextom Countdown Bar   → launch/flash-sale countdown sections (message-before,
 *                              live timer, message-after, CTA), page/password/404.
 *   - Privy / Omnisend / Klaviyo → inline (non-overlay) email/SMS opt-in capture
 *                              sections with consent + coupon-reveal copy.
 *
 * Authoring model (spec 032 §A.6): the app ships ONE theme app-extension app-block;
 * the section's repeatable content lives in `spec.config.blocks[]` (each a
 * `{ kind, text?, imageUrl?, url?, fields? }`), `config.layout.layout` selects the
 * grid variant, and `config.fields` holds section-level knobs. Every spec parses
 * against `RecipeSpecSchema` (`theme.section` member). No overlay/app-embed activation
 * is used here — these are in-body full sections (`activation: 'section'`), matching
 * the deployable app-block surface. Placement templates are a subset of
 * `THEME_PLACEABLE_TEMPLATES` (page / blog / article / password / 404 / index).
 *
 * HONESTY: capture-form sections DECLARE their fields as content (a real inline form
 * the app-block renders); they do NOT imply a live email/SMS send — that is a separate
 * messaging surface. Countdown sections render a client-side timer over an ISO end in
 * `fields`; no discount is applied by the section (mirrors the real Hextom bar).
 */
import type { TemplateEntry } from '../types.js';
import { THEME_PLACEABLE_TEMPLATES } from '../../allowed-values.js';

/** Local alias so placement arrays stay terse + type-safe against the manifest. */
type PlaceableTemplate = (typeof THEME_PLACEABLE_TEMPLATES)[number];
const on = (...templates: PlaceableTemplate[]) => ({ enabled_on: { templates } });

export const TBLK_PAGE_TEMPLATES: TemplateEntry[] = [
  // ── 01 — Split landing hero (PageFly hero-banner archetype) ─────────────────
  {
    id: 'TBLK-PAGE-01',
    name: 'Landing Hero — Split Copy + Visual',
    description: 'Full-bleed split hero for a custom landing page: headline, sub-copy, and a primary CTA beside a lifestyle image.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'hero',
    tags: ['section', 'pagefly', 'landing', 'hero', 'page', 'cta'],
    spec: {
      type: 'theme.section',
      name: 'Landing Hero — Split Copy + Visual',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'hero',
        activation: 'section',
        title: 'Built for the way you actually shop',
        subtitle: 'Meet the collection everyone is talking about — designed to last, priced to move.',
        layout: { layout: 'columns', columns: 2 },
        fields: {
          mediaSide: 'right',
          primaryCtaLabel: 'Shop the drop',
          primaryCtaUrl: 'https://example.com/collections/new',
          eyebrow: 'New arrivals',
          heroImageUrl: 'https://cdn.example.com/pages/hero-split.jpg',
        },
        blocks: [
          // 4 trust badges → clean 2×2 within the copy column (columns:2 is the copy|image split).
          { kind: 'feature', text: 'Free 2-day shipping over $50', fields: { icon: 'truck' } },
          { kind: 'feature', text: '30-day easy returns', fields: { icon: 'return' } },
          { kind: 'feature', text: 'Carbon-neutral delivery', fields: { icon: 'leaf' } },
          { kind: 'feature', text: 'Secure checkout, always', fields: { icon: 'lock' } },
        ],
      },
      placement: on('page', 'index'),
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'full', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'loose', density: 'comfortable' },
        typography: { size: '2XL', weight: 'bold', lineHeight: 'tight', align: 'left' },
        colors: { seed: '#6d28d9', overlayBackdropOpacity: 0.45 },
        shape: { radius: 'lg', borderWidth: 'none', shadow: 'sm', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'base', easing: 'enter' },
        pack: 'bold',
      },
    },
  },

  // ── 02 — Centered ambient-gradient hero ─────────────────────────────────────
  {
    id: 'TBLK-PAGE-02',
    name: 'Landing Hero — Centered Ambient Gradient',
    description: 'Centered, gradient-backdrop landing hero with a bold headline and single CTA — for brand or campaign pages.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'hero',
    tags: ['section', 'gempages', 'landing', 'hero', 'page'],
    spec: {
      type: 'theme.section',
      name: 'Landing Hero — Centered Ambient Gradient',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'hero',
        activation: 'section',
        title: 'The upgrade you have been waiting for',
        subtitle: 'One product. Zero compromises. Now shipping worldwide.',
        layout: { layout: 'stacked' },
        fields: {
          alignment: 'center',
          primaryCtaLabel: 'Get yours',
          primaryCtaUrl: 'https://example.com/products/flagship',
          secondaryCtaLabel: 'Watch the film',
          secondaryCtaUrl: 'https://example.com/pages/story',
          backgroundStyle: 'gradient',
        },
        blocks: [],
      },
      placement: on('page', 'index'),
      style: {
        layout: { mode: 'inline', anchor: 'center', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'airy' },
        typography: { size: '2XL', weight: 'bold', lineHeight: 'tight', align: 'center' },
        colors: { text: '#f8fafc', background: '#0b1020', seed: '#22d3ee', overlayBackdropOpacity: 0.45 },
        shape: { radius: 'xl', borderWidth: 'none', shadow: 'lg', elevation: 'glow' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'slow', easing: 'enter' },
        pack: 'bold',
      },
    },
  },

  // ── 03 — Photo-overlay hero ─────────────────────────────────────────────────
  {
    id: 'TBLK-PAGE-03',
    name: 'Landing Hero — Photo Overlay',
    description: 'Full-bleed photo hero with a dark overlay and centered headline + CTA, for editorial campaign landing pages.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'hero',
    tags: ['section', 'pagefly', 'landing', 'hero', 'page', 'editorial'],
    spec: {
      type: 'theme.section',
      name: 'Landing Hero — Photo Overlay',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'hero',
        activation: 'section',
        title: 'Made to be worn everywhere',
        subtitle: 'The autumn edit, in stores and online now.',
        layout: { layout: 'stacked' },
        fields: {
          heroImageUrl: 'https://cdn.example.com/pages/hero-overlay.jpg',
          overlay: true,
          primaryCtaLabel: 'Explore the edit',
          primaryCtaUrl: 'https://example.com/collections/autumn',
          minHeight: 'tall',
        },
        blocks: [],
      },
      placement: on('page', 'index'),
      style: {
        layout: { mode: 'inline', anchor: 'center', offsetX: 0, offsetY: 0, width: 'full', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: '2XL', weight: 'bold', lineHeight: 'tight', align: 'center' },
        colors: { text: '#ffffff', background: '#1c1917', overlayBackdrop: '#000000', overlayBackdropOpacity: 0.45, seed: '#a16207' },
        shape: { radius: 'none', borderWidth: 'none', shadow: 'none', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'base', easing: 'enter' },
        pack: 'luxe',
      },
    },
  },

  // ── 04 — Rich-text "About" story section ────────────────────────────────────
  {
    id: 'TBLK-PAGE-04',
    name: 'About Story — Two-Column Rich Text',
    description: 'Two-column brand-story section for an About page: heading with a longer narrative body and a supporting image.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'text',
    tags: ['section', 'pagefly', 'about', 'rich-text', 'page', 'story'],
    spec: {
      type: 'theme.section',
      name: 'About Story — Two-Column Rich Text',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'rich-text',
        activation: 'section',
        title: 'Our story started in a garage',
        subtitle: 'Ten years, three cities, one obsession with getting it right.',
        layout: { layout: 'columns', columns: 2 },
        fields: {
          body: 'We build products the slow way — testing every material until it earns its place. What began as a weekend experiment now ships to more than 40 countries, and the values have not budged.',
          imageUrl: 'https://cdn.example.com/pages/about-workshop.jpg',
          imageSide: 'left',
        },
        blocks: [],
      },
      placement: on('page', 'article'),
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'loose', density: 'airy' },
        typography: { size: 'MD', weight: 'normal', lineHeight: 'relaxed', align: 'left' },
        colors: { seed: '#0f766e', overlayBackdropOpacity: 0.45 },
        shape: { radius: 'md', borderWidth: 'none', shadow: 'none', elevation: 'border' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        pack: 'luxe',
      },
    },
  },

  // ── 05 — Feature grid (3-up value props) ────────────────────────────────────
  {
    id: 'TBLK-PAGE-05',
    name: 'Feature Grid — 3-Up Value Props',
    description: 'Three-column feature grid of icon + heading + copy blocks for a landing or About page.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'feature',
    tags: ['section', 'gempages', 'landing', 'feature', 'page', 'grid'],
    spec: {
      type: 'theme.section',
      name: 'Feature Grid — 3-Up Value Props',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'feature',
        activation: 'section',
        title: 'Why thousands switched',
        subtitle: 'The three things every review keeps mentioning.',
        layout: { layout: 'grid', columns: 3 },
        fields: { showIcons: true },
        blocks: [
          { kind: 'feature', text: 'Sourced from recycled ocean plastic, certified end-to-end.', imageUrl: 'https://cdn.example.com/pages/feat-eco.svg', fields: { heading: 'Genuinely sustainable', icon: 'leaf' } },
          { kind: 'feature', text: 'Independently stress-tested to 3x the industry standard.', imageUrl: 'https://cdn.example.com/pages/feat-durable.svg', fields: { heading: 'Built to outlast', icon: 'shield' } },
          { kind: 'feature', text: 'A real human answers within an hour, seven days a week.', imageUrl: 'https://cdn.example.com/pages/feat-support.svg', fields: { heading: 'Support that shows up', icon: 'chat' } },
        ],
      },
      placement: on('page', 'index'),
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: 'MD', weight: 'medium', lineHeight: 'normal', align: 'center' },
        colors: { seed: '#2563eb', overlayBackdropOpacity: 0.45 },
        shape: { radius: 'lg', borderWidth: 'thin', shadow: 'sm', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        pack: 'luxe',
      },
    },
  },

  // ── 06 — Feature bento grid ─────────────────────────────────────────────────
  {
    id: 'TBLK-PAGE-06',
    name: 'Feature Bento — Mixed-Size Tiles',
    description: 'Mixed-size bento grid of feature tiles for a product-story landing page, each tile a reorderable block.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'bento',
    tags: ['section', 'pagefly', 'landing', 'feature', 'page', 'bento'],
    spec: {
      type: 'theme.section',
      name: 'Feature Bento — Mixed-Size Tiles',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'feature',
        activation: 'section',
        title: 'Everything, in one place',
        layout: { layout: 'grid', columns: 3 },
        fields: { bento: true },
        blocks: [
          { kind: 'feature', text: 'The centerpiece: our fastest-charging cell yet.', imageUrl: 'https://cdn.example.com/pages/bento-1.jpg', fields: { span: 'wide', heading: 'All-day battery' } },
          { kind: 'feature', text: 'Water-resistant to 50m.', fields: { span: 'tall', heading: 'Take it anywhere' } },
          { kind: 'feature', text: 'Swappable bands in nine colors.', fields: { heading: 'Make it yours' } },
          { kind: 'feature', text: 'Setup in under a minute.', fields: { heading: 'Zero friction' } },
        ],
      },
      placement: on('page', 'index'),
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'wide', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: 'LG', weight: 'bold', lineHeight: 'normal', align: 'left' },
        colors: { seed: '#7c3aed', overlayBackdropOpacity: 0.45 },
        shape: { radius: 'xl', borderWidth: 'none', shadow: 'md', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        pack: 'bold',
      },
    },
  },

  // ── 07 — CTA band ───────────────────────────────────────────────────────────
  {
    id: 'TBLK-PAGE-07',
    name: 'CTA Band — Full-Width Conversion',
    description: 'Full-width call-to-action band with a headline and single primary button to close a landing page.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'cta',
    tags: ['section', 'gempages', 'landing', 'cta', 'page', 'conversion'],
    spec: {
      type: 'theme.section',
      name: 'CTA Band — Full-Width Conversion',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'cta',
        activation: 'section',
        title: 'Ready when you are',
        subtitle: 'Join 40,000 happy customers today.',
        layout: { layout: 'stacked' },
        fields: {
          primaryCtaLabel: 'Start now',
          primaryCtaUrl: 'https://example.com/collections/all',
          alignment: 'center',
        },
        blocks: [],
      },
      placement: on('page', 'index', 'blog'),
      style: {
        layout: { mode: 'inline', anchor: 'center', offsetX: 0, offsetY: 0, width: 'full', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: 'XL', weight: 'bold', lineHeight: 'tight', align: 'center' },
        colors: { text: '#ffffff', background: '#111827', seed: '#f59e0b', overlayBackdropOpacity: 0.45 },
        shape: { radius: 'lg', borderWidth: 'none', shadow: 'md', elevation: 'glow' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'fast', easing: 'standard' },
        pack: 'bold',
      },
    },
  },

  // ── 08 — Countdown launch section (Hextom archetype) ────────────────────────
  {
    id: 'TBLK-PAGE-08',
    name: 'Launch Countdown — Full Section',
    description: 'Full-width launch countdown section with message-before, a live timer over an ISO end, message-after, and a CTA.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'countdown',
    tags: ['section', 'hextom', 'countdown', 'urgency', 'page', 'launch'],
    spec: {
      type: 'theme.section',
      name: 'Launch Countdown — Full Section',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'countdown',
        activation: 'section',
        title: 'The drop goes live in',
        subtitle: 'Set your reminder — quantities are limited.',
        layout: { layout: 'stacked' },
        fields: {
          messageBefore: 'Launching in',
          messageAfter: 'Sale is live — shop before it sells out.',
          endsAt: '2026-12-01T09:00:00Z',
          timerStyle: 'square-tiles',
          showLabels: true,
          timezoneBasis: 'customerLocal',
          ctaLabel: 'Notify me',
          ctaUrl: 'https://example.com/pages/launch',
        },
        blocks: [],
      },
      placement: on('page', 'index'),
      style: {
        layout: { mode: 'inline', anchor: 'center', offsetX: 0, offsetY: 0, width: 'full', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: 'XL', weight: 'bold', lineHeight: 'tight', align: 'center' },
        colors: { text: '#f8fafc', background: '#111827', seed: '#ef4444', overlayBackdropOpacity: 0.45 },
        shape: { radius: 'md', borderWidth: 'none', shadow: 'md', elevation: 'glow' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'base', easing: 'standard' },
        pack: 'bold',
      },
    },
  },

  // ── 09 — Flash-sale countdown with offer tiles ──────────────────────────────
  {
    id: 'TBLK-PAGE-09',
    name: 'Flash Sale Countdown — Offer Tiles',
    description: 'Flash-sale countdown section with a live timer plus a row of reorderable offer tiles for a promo landing page.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'countdown',
    tags: ['section', 'hextom', 'countdown', 'flash-sale', 'page', 'promo'],
    spec: {
      type: 'theme.section',
      name: 'Flash Sale Countdown — Offer Tiles',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'countdown',
        activation: 'section',
        title: '48-hour flash sale',
        subtitle: 'When the timer hits zero, the prices go back up.',
        layout: { layout: 'grid', columns: 3 },
        fields: {
          endsAt: '2026-11-30T23:59:59Z',
          timerStyle: 'flip-clock',
          showLabels: true,
          messageAfter: 'The flash sale has ended.',
        },
        blocks: [
          { kind: 'feature', text: 'Up to 40% off outerwear', url: 'https://example.com/collections/outerwear', fields: { badge: '40% OFF' } },
          { kind: 'feature', text: 'Buy 2 get 1 on basics', url: 'https://example.com/collections/basics', fields: { badge: 'B2G1' } },
          { kind: 'feature', text: 'Free shipping, no minimum', url: 'https://example.com/collections/all', fields: { badge: 'FREE SHIP' } },
        ],
      },
      placement: on('page', 'index'),
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'wide', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: 'LG', weight: 'bold', lineHeight: 'tight', align: 'center' },
        colors: { seed: '#ea580c', overlayBackdropOpacity: 0.45 },
        shape: { radius: 'lg', borderWidth: 'thin', shadow: 'sm', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'fast', easing: 'standard' },
        pack: 'bold',
      },
    },
  },

  // ── 10 — Inline newsletter opt-in (Privy archetype) ─────────────────────────
  {
    id: 'TBLK-PAGE-10',
    name: 'Newsletter Opt-In — Inline Capture',
    description: 'Inline (non-overlay) email opt-in section with an email field, consent line, and coupon-reveal copy for a landing page.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'newsletter',
    tags: ['section', 'privy', 'newsletter', 'opt-in', 'page', 'email'],
    spec: {
      type: 'theme.section',
      name: 'Newsletter Opt-In — Inline Capture',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'newsletter',
        activation: 'section',
        title: 'Get 10% off your first order',
        subtitle: 'Join the list for early access and members-only drops.',
        layout: { layout: 'stacked' },
        fields: {
          emailPlaceholder: 'you@example.com',
          submitLabel: 'Unlock 10% off',
          consentText: 'By subscribing you agree to receive marketing emails. Unsubscribe anytime.',
          successMessage: 'You are in — check your inbox for the code.',
          captureChannel: 'email',
        },
        blocks: [],
      },
      placement: on('page', 'blog', 'index'),
      style: {
        layout: { mode: 'inline', anchor: 'center', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: 'LG', weight: 'medium', lineHeight: 'normal', align: 'center' },
        colors: { seed: '#0ea5e9', overlayBackdropOpacity: 0.45 },
        shape: { radius: 'lg', borderWidth: 'none', shadow: 'sm', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        pack: 'bold',
      },
    },
  },

  // ── 11 — Split-image newsletter with benefit list ───────────────────────────
  {
    id: 'TBLK-PAGE-11',
    name: 'Newsletter Opt-In — Split Image + Benefits',
    description: 'Split newsletter section: an email capture beside an image, with a reorderable list of subscriber benefits.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'newsletter',
    tags: ['section', 'omnisend', 'newsletter', 'opt-in', 'page', 'email'],
    spec: {
      type: 'theme.section',
      name: 'Newsletter Opt-In — Split Image + Benefits',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'newsletter',
        activation: 'section',
        title: 'The best of us, in your inbox',
        subtitle: 'One thoughtful email a week. No spam, ever.',
        layout: { layout: 'columns', columns: 2 },
        fields: {
          imageUrl: 'https://cdn.example.com/pages/newsletter-split.jpg',
          imageSide: 'left',
          emailPlaceholder: 'Enter your email',
          submitLabel: 'Subscribe',
          consentText: 'You can unsubscribe at any time.',
          captureChannel: 'email',
        },
        blocks: [
          // 4 benefits → clean 2×2 beside the image (columns:2 is the image|form split).
          { kind: 'feature', text: 'Early access to every new drop', fields: { icon: 'star' } },
          { kind: 'feature', text: 'Subscriber-only pricing', fields: { icon: 'tag' } },
          { kind: 'feature', text: 'Styling tips from our team', fields: { icon: 'sparkle' } },
          { kind: 'feature', text: 'First to know about restocks', fields: { icon: 'bell' } },
        ],
      },
      placement: on('page', 'blog', 'index'),
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'loose', density: 'airy' },
        typography: { size: 'MD', weight: 'normal', lineHeight: 'relaxed', align: 'left' },
        colors: { seed: '#059669', overlayBackdropOpacity: 0.45 },
        shape: { radius: 'lg', borderWidth: 'thin', shadow: 'none', elevation: 'border' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        pack: 'luxe',
      },
    },
  },

  // ── 12 — Email + SMS opt-in (Klaviyo/Omnisend dual capture) ──────────────────
  {
    id: 'TBLK-PAGE-12',
    name: 'Opt-In — Email + SMS Dual Capture',
    description: 'Inline dual-consent capture section with email and phone fields plus separate marketing-consent lines.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'newsletter',
    tags: ['section', 'klaviyo', 'opt-in', 'sms', 'page', 'consent'],
    spec: {
      type: 'theme.section',
      name: 'Opt-In — Email + SMS Dual Capture',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'newsletter',
        activation: 'section',
        title: 'Never miss a restock',
        subtitle: 'Choose how you want to hear from us.',
        layout: { layout: 'stacked' },
        fields: {
          emailPlaceholder: 'Email address',
          phonePlaceholder: 'Mobile number',
          submitLabel: 'Keep me posted',
          emailConsentText: 'I agree to receive marketing emails.',
          smsConsentText: 'I agree to receive recurring marketing texts. Msg & data rates may apply.',
          captureChannel: 'email_sms',
        },
        blocks: [],
      },
      placement: on('page', 'blog', 'index'),
      style: {
        layout: { mode: 'inline', anchor: 'center', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: 'MD', weight: 'medium', lineHeight: 'normal', align: 'center' },
        colors: { seed: '#7c3aed', overlayBackdropOpacity: 0.45 },
        shape: { radius: 'lg', borderWidth: 'none', shadow: 'sm', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        pack: 'luxe',
      },
    },
  },

  // ── 13 — Coming-soon / password hero ────────────────────────────────────────
  {
    id: 'TBLK-PAGE-13',
    name: 'Coming Soon — Password Page Hero',
    description: 'Coming-soon hero for the password (storefront-locked) page: brand headline, teaser copy, and a launch date line.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'hero',
    tags: ['section', 'gempages', 'coming-soon', 'password', 'launch', 'hero'],
    spec: {
      type: 'theme.section',
      name: 'Coming Soon — Password Page Hero',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'hero',
        activation: 'section',
        title: 'Something good is on the way',
        subtitle: 'Our store opens soon. Be the first to know.',
        layout: { layout: 'stacked' },
        fields: {
          alignment: 'center',
          launchDateLabel: 'Opening November 2026',
          backgroundStyle: 'gradient',
          logoUrl: 'https://cdn.example.com/pages/logo-mark.svg',
        },
        blocks: [],
      },
      placement: on('password'),
      style: {
        layout: { mode: 'inline', anchor: 'center', offsetX: 0, offsetY: 0, width: 'full', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'airy' },
        typography: { size: '2XL', weight: 'bold', lineHeight: 'tight', align: 'center' },
        colors: { text: '#f8fafc', background: '#0f0f14', seed: '#e879f9', overlayBackdropOpacity: 0.45 },
        shape: { radius: 'none', borderWidth: 'none', shadow: 'none', elevation: 'glow' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'slow', easing: 'enter' },
        pack: 'bold',
      },
    },
  },

  // ── 14 — Coming-soon opt-in + countdown (password) ──────────────────────────
  {
    id: 'TBLK-PAGE-14',
    name: 'Coming Soon — Opt-In + Countdown',
    description: 'Password-page launch section combining a countdown to open date with an inline email waitlist capture.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'countdown',
    tags: ['section', 'privy', 'coming-soon', 'password', 'countdown', 'opt-in'],
    spec: {
      type: 'theme.section',
      name: 'Coming Soon — Opt-In + Countdown',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'countdown',
        activation: 'section',
        title: 'We open in',
        subtitle: 'Join the waitlist for launch-day early access.',
        layout: { layout: 'stacked' },
        fields: {
          endsAt: '2026-11-15T08:00:00Z',
          timerStyle: 'circle-tiles',
          showLabels: true,
          emailPlaceholder: 'Email for early access',
          submitLabel: 'Join the waitlist',
          consentText: 'We will only email you about the launch.',
          captureChannel: 'email',
        },
        blocks: [],
      },
      placement: on('password'),
      style: {
        layout: { mode: 'inline', anchor: 'center', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: 'XL', weight: 'bold', lineHeight: 'tight', align: 'center' },
        colors: { seed: '#6366f1', overlayBackdropOpacity: 0.45 },
        shape: { radius: 'lg', borderWidth: 'none', shadow: 'sm', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'base', easing: 'standard' },
        pack: 'bold',
      },
    },
  },

  // ── 15 — 404 "lost" recovery section ────────────────────────────────────────
  {
    id: 'TBLK-PAGE-15',
    name: '404 — Friendly Recovery',
    description: 'Full-section 404 with a friendly headline, a search prompt, and reorderable quick-link cards back into the store.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'error',
    tags: ['section', 'pagefly', '404', 'recovery', 'page', 'navigation'],
    spec: {
      type: 'theme.section',
      name: '404 — Friendly Recovery',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'custom',
        activation: 'section',
        title: 'This page took a wrong turn',
        subtitle: 'Let us get you back to the good stuff.',
        layout: { layout: 'grid', columns: 3 },
        fields: {
          showSearch: true,
          searchPlaceholder: 'Search the store',
        },
        blocks: [
          { kind: 'feature', text: 'Shop best sellers', url: 'https://example.com/collections/best-sellers', fields: { icon: 'fire' } },
          { kind: 'feature', text: 'Browse new arrivals', url: 'https://example.com/collections/new', fields: { icon: 'sparkle' } },
          { kind: 'feature', text: 'Back to home', url: 'https://example.com/', fields: { icon: 'home' } },
        ],
      },
      placement: on('404'),
      style: {
        layout: { mode: 'inline', anchor: 'center', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: 'XL', weight: 'bold', lineHeight: 'tight', align: 'center' },
        colors: { seed: '#f43f5e', overlayBackdropOpacity: 0.45 },
        shape: { radius: 'lg', borderWidth: 'thin', shadow: 'sm', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        pack: 'luxe',
      },
    },
  },

  // ── 16 — 404 with product recommendations ───────────────────────────────────
  {
    id: 'TBLK-PAGE-16',
    name: '404 — Recover with Recommendations',
    description: 'A 404 recovery section that surfaces recommended products from a chosen collection so a dead link still converts.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'error',
    tags: ['section', 'pagefly', '404', 'recommendation', 'page', 'conversion'],
    spec: {
      type: 'theme.section',
      name: '404 — Recover with Recommendations',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'custom',
        activation: 'section',
        title: 'Page not found — but these are',
        subtitle: 'A few things our customers love.',
        layout: { layout: 'grid', columns: 4 },
        fields: { headingCta: 'Back to home', headingCtaUrl: 'https://example.com/' },
        recommendation: {
          manualVariantGids: [],
          collectionRandom: false,
          excludeTags: [],
          hideCartProducts: false,
          strategy: 'collection',
          collectionGid: 'gid://shopify/Collection/1234567890',
          productLimit: 4,
          fallback: 'related',
        },
        blocks: [],
      },
      placement: on('404'),
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'wide', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: 'LG', weight: 'medium', lineHeight: 'normal', align: 'center' },
        colors: { seed: '#2563eb', overlayBackdropOpacity: 0.45 },
        shape: { radius: 'lg', borderWidth: 'thin', shadow: 'sm', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        pack: 'luxe',
      },
    },
  },

  // ── 17 — Blog featured / editorial banner ───────────────────────────────────
  {
    id: 'TBLK-PAGE-17',
    name: 'Blog Featured Banner — Editorial',
    description: 'Editorial banner for the top of a blog index: a featured-story headline, deck, and read CTA over an image.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'article',
    tags: ['section', 'gempages', 'blog', 'editorial', 'featured', 'banner'],
    spec: {
      type: 'theme.section',
      name: 'Blog Featured Banner — Editorial',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'banner',
        activation: 'section',
        title: 'The field guide to slow fashion',
        subtitle: 'A five-part series on buying less and loving it more.',
        layout: { layout: 'stacked' },
        fields: {
          heroImageUrl: 'https://cdn.example.com/blog/featured.jpg',
          overlay: true,
          readLabel: 'Read the series',
          readUrl: 'https://example.com/blogs/journal/slow-fashion',
          eyebrow: 'Featured',
        },
        blocks: [],
      },
      placement: on('blog', 'index'),
      style: {
        layout: { mode: 'inline', anchor: 'center', offsetX: 0, offsetY: 0, width: 'full', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'airy' },
        typography: { size: '2XL', weight: 'bold', lineHeight: 'tight', align: 'center' },
        colors: { text: '#ffffff', background: '#1c1917', overlayBackdrop: '#000000', overlayBackdropOpacity: 0.4, seed: '#a16207' },
        shape: { radius: 'md', borderWidth: 'none', shadow: 'none', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'base', easing: 'enter' },
        pack: 'luxe',
      },
    },
  },

  // ── 18 — Article CTA / mid-article opt-in ───────────────────────────────────
  {
    id: 'TBLK-PAGE-18',
    name: 'Article Inline CTA — Subscribe to Read More',
    description: 'Inline call-to-action block for placement inside an article body: subscribe prompt with an email field.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'newsletter',
    tags: ['section', 'omnisend', 'article', 'opt-in', 'blog', 'inline'],
    spec: {
      type: 'theme.section',
      name: 'Article Inline CTA — Subscribe to Read More',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'newsletter',
        activation: 'section',
        title: 'Enjoying this?',
        subtitle: 'Get the next chapter straight to your inbox.',
        layout: { layout: 'stacked' },
        fields: {
          emailPlaceholder: 'you@example.com',
          submitLabel: 'Send me more',
          consentText: 'Unsubscribe anytime.',
          captureChannel: 'email',
          compact: true,
        },
        blocks: [],
      },
      placement: on('article', 'blog'),
      style: {
        layout: { mode: 'inline', anchor: 'center', offsetX: 0, offsetY: 0, width: 'narrow', zIndex: 'base' },
        spacing: { padding: 'medium', margin: 'medium', gap: 'tight', density: 'comfortable' },
        typography: { size: 'MD', weight: 'medium', lineHeight: 'normal', align: 'center' },
        colors: { seed: '#0ea5e9', overlayBackdropOpacity: 0.45 },
        shape: { radius: 'lg', borderWidth: 'thin', shadow: 'none', elevation: 'border' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        pack: 'luxe',
      },
    },
  },

  // ── 19 — FAQ accordion section ──────────────────────────────────────────────
  {
    id: 'TBLK-PAGE-19',
    name: 'FAQ — Accordion',
    description: 'FAQ accordion section for a support or landing page — each question a reorderable block with question/answer.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'faq',
    tags: ['section', 'pagefly', 'faq', 'accordion', 'page', 'support'],
    spec: {
      type: 'theme.section',
      name: 'FAQ — Accordion',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'faq',
        activation: 'section',
        title: 'Frequently asked questions',
        subtitle: 'Everything you need before you buy.',
        layout: { layout: 'stacked' },
        fields: { singleOpen: true },
        blocks: [
          { kind: 'faq-item', text: 'How long does shipping take?', fields: { answer: 'Orders ship within 24 hours and arrive in 2-5 business days.' } },
          { kind: 'faq-item', text: 'What is your return policy?', fields: { answer: 'Free returns within 30 days, no questions asked.' } },
          { kind: 'faq-item', text: 'Do you ship internationally?', fields: { answer: 'Yes — we ship to over 40 countries with duties calculated at checkout.' } },
          { kind: 'faq-item', text: 'Can I change my order after buying?', fields: { answer: 'Contact us within an hour and we will do our best to update it.' } },
        ],
      },
      placement: on('page', 'article'),
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'tight', density: 'comfortable' },
        typography: { size: 'MD', weight: 'medium', lineHeight: 'normal', align: 'left' },
        colors: { seed: '#0f766e', overlayBackdropOpacity: 0.45 },
        shape: { radius: 'md', borderWidth: 'thin', shadow: 'none', elevation: 'border' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        pack: 'luxe',
      },
    },
  },

  // ── 20 — Testimonials wall ──────────────────────────────────────────────────
  {
    id: 'TBLK-PAGE-20',
    name: 'Testimonials — Wall of Love',
    description: 'Grid "wall of love" testimonial section for a landing or About page — each quote a reorderable card block.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'reviews',
    tags: ['section', 'gempages', 'testimonials', 'social-proof', 'page', 'grid'],
    spec: {
      type: 'theme.section',
      name: 'Testimonials — Wall of Love',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'testimonials',
        activation: 'section',
        title: 'Loved by 40,000 customers',
        subtitle: 'Do not just take our word for it.',
        // 4 quote cards → balanced 2×2 wall (was columns:3, which orphaned the 4th).
        layout: { layout: 'grid', columns: 2 },
        fields: { showStars: true },
        blocks: [
          { kind: 'review-card', text: 'Honestly the best purchase I have made all year.', fields: { author: 'Maya R.', rating: 5 } },
          { kind: 'review-card', text: 'Shipping was fast and the quality is unreal.', fields: { author: 'Devon K.', rating: 5 } },
          { kind: 'review-card', text: 'Bought one, then immediately bought two more as gifts.', fields: { author: 'Priya S.', rating: 5 } },
          { kind: 'review-card', text: 'Customer service actually replied in minutes. Rare these days.', fields: { author: 'Sam T.', rating: 4 } },
        ],
      },
      placement: on('page', 'index'),
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'wide', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: 'MD', weight: 'normal', lineHeight: 'relaxed', align: 'left' },
        colors: { seed: '#f59e0b', overlayBackdropOpacity: 0.45 },
        shape: { radius: 'lg', borderWidth: 'none', shadow: 'sm', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        pack: 'luxe',
      },
    },
  },

  // ── 21 — Steps / how-it-works ───────────────────────────────────────────────
  {
    id: 'TBLK-PAGE-21',
    name: 'How It Works — Numbered Steps',
    description: 'Numbered how-it-works section for a landing or About page — each step a reorderable block with a heading + copy.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'steps',
    tags: ['section', 'pagefly', 'how-it-works', 'steps', 'page', 'onboarding'],
    spec: {
      type: 'theme.section',
      name: 'How It Works — Numbered Steps',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'feature',
        activation: 'section',
        title: 'How it works',
        subtitle: 'From order to doorstep in three simple steps.',
        layout: { layout: 'grid', columns: 3 },
        fields: { numbered: true },
        blocks: [
          { kind: 'step', text: 'Pick your plan and personalize it in under a minute.', fields: { step: 1, heading: 'Choose' } },
          { kind: 'step', text: 'We build and quality-check your order by hand.', fields: { step: 2, heading: 'We craft' } },
          { kind: 'step', text: 'It ships carbon-neutral and lands in days.', fields: { step: 3, heading: 'You enjoy' } },
        ],
      },
      placement: on('page', 'index'),
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: 'MD', weight: 'medium', lineHeight: 'normal', align: 'center' },
        colors: { seed: '#6366f1', overlayBackdropOpacity: 0.45 },
        shape: { radius: 'lg', borderWidth: 'thin', shadow: 'sm', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        pack: 'luxe',
      },
    },
  },

  // ── 22 — Contact split section ──────────────────────────────────────────────
  {
    id: 'TBLK-PAGE-22',
    name: 'Contact — Split Info + Form Prompt',
    description: 'Split contact section for a Contact page: business hours and support links beside a get-in-touch prompt.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'contact',
    tags: ['section', 'gempages', 'contact', 'support', 'page', 'split'],
    spec: {
      type: 'theme.section',
      name: 'Contact — Split Info + Form Prompt',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'custom',
        activation: 'section',
        title: 'Get in touch',
        subtitle: 'Real humans, fast replies — seven days a week.',
        layout: { layout: 'columns', columns: 2 },
        fields: {
          hoursLabel: 'Mon-Sun, 8am-8pm ET',
          emailPlaceholder: 'you@example.com',
          messagePlaceholder: 'How can we help?',
          submitLabel: 'Send message',
        },
        blocks: [
          // 4 contact channels → clean 2×2 beside the form prompt (columns:2 is the info|form split).
          { kind: 'feature', text: 'Email us', url: 'https://example.com/pages/contact', fields: { icon: 'mail', value: 'help@example.com' } },
          { kind: 'feature', text: 'Live chat', url: 'https://example.com/pages/chat', fields: { icon: 'chat', value: 'Average reply under 5 min' } },
          { kind: 'feature', text: 'Help center', url: 'https://example.com/pages/help', fields: { icon: 'book', value: 'Browse 200+ articles' } },
          { kind: 'feature', text: 'Call us', url: 'https://example.com/pages/contact', fields: { icon: 'phone', value: '+1 (555) 012-3456' } },
        ],
      },
      placement: on('page'),
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'loose', density: 'comfortable' },
        typography: { size: 'MD', weight: 'normal', lineHeight: 'relaxed', align: 'left' },
        colors: { seed: '#0ea5e9', overlayBackdropOpacity: 0.45 },
        shape: { radius: 'lg', borderWidth: 'thin', shadow: 'none', elevation: 'border' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        pack: 'luxe',
      },
    },
  },
];
