import type { TemplateEntry } from '../types.js';
import { THEME_PLACEABLE_TEMPLATES } from '../../allowed-values.js';

/**
 * TBLK-IDX — full-section `theme.section` app-block designs for the HOME template
 * (`index`). Surface family = index-fullsection (034 surface-coverage plan,
 * theme-extension-blocks lib): hero / feature-bento / social-proof full-width
 * sections a merchant drops onto the homepage.
 *
 * DUAL-MODE (033/034): every entry is authored ONCE as a `theme.section`. In the
 * shipped app-block path it renders as a `$app:superapp_module` metaobject through
 * the theme app extension (generic branch reads `config.kind` +
 * `config.blocks[].{kind,text,imageUrl,url}` + `config.layout.layout`). The SAME spec
 * also compiles to a native `sections/superapp-<slug>.liquid` file (DeployTarget
 * `mode: 'native_section'`, flag+exemption gated) — so these full-section designs
 * back BOTH the theme-extension-blocks lib and the native-sections lib. Nothing here
 * is app-block-only; they are the reorderable, homepage-hero class of section.
 *
 * The reorderable content lives in `config.blocks[]` (the modular-blocks model, §A.6):
 * `kind` is the block type slug, `text`/`imageUrl`/`url` are renderer-first-class,
 * everything richer goes in the per-block `fields` bag. `config.layout.layout` selects
 * the layout VARIANT (`stacked | grid | columns | carousel | masonry`) so the same
 * tokens ship multiple moods. `style` is grounded in the six design-vocabulary §4 style
 * packs (Apple HIG Clean, Editorial Wellness, Bold DTC, Minimal Luxe, Playful Commerce,
 * Tech Utility) layered over placeholder brand colors — the live compiler reseeds these
 * from the merchant's extracted palette at generation time.
 *
 * HONESTY: `imageUrl`/`url` are placeholder `https://` CDN URLs (Zod `.url()`); a
 * merchant/brand-extraction step replaces them. Copy is grounded in the real corpus
 * (loox.md social-proof "wall of love" + trust badge patterns, fera.md floating badge /
 * overall-rating banner / testimonial carousel, design-vocabulary §2 section catalog) —
 * no invented targets, kinds, or enum values; every field resolves against the
 * `theme.section` RecipeSpec member (recipe.ts:338-399) and the StorefrontStyle schema.
 */

const IDX = ['index'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][];

export const TBLK_IDX_TEMPLATES: TemplateEntry[] = [
  // ── HERO (5) ──────────────────────────────────────────────────────────────
  {
    id: 'TBLK-IDX-01',
    name: 'Hero — Split Copy / Visual',
    description: 'Full-width homepage hero split into a copy column and a product-visual column, with a primary and secondary CTA.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'hero',
    tags: ['section', 'hero', 'index', 'homepage', 'cta'],
    spec: {
      type: 'theme.section',
      name: 'Hero — Split Copy / Visual',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'hero',
        activation: 'section',
        title: 'Built for the way you actually shop',
        subtitle: 'Thoughtful essentials, delivered fast. Free returns, always.',
        layout: { layout: 'columns', columns: 2 },
        fields: {
          eyebrow: 'New season',
          primaryCtaLabel: 'Shop the collection',
          primaryCtaUrl: 'https://example.com/collections/all',
          secondaryCtaLabel: 'Our story',
          secondaryCtaUrl: 'https://example.com/pages/about',
          mediaSide: 'right',
          mediaUrl: 'https://cdn.example.com/hero/split-visual.jpg',
        },
        blocks: [],
      },
      placement: { enabled_on: { templates: IDX } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'full', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'loose', density: 'comfortable' },
        typography: { size: '2XL', weight: 'bold', lineHeight: 'tight', align: 'left' },
        colors: { overlayBackdropOpacity: 0.45 },
        shape: { radius: 'lg', borderWidth: 'none', shadow: 'sm', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'base', easing: 'enter' },
      },
    },
  },

  {
    id: 'TBLK-IDX-02',
    name: 'Hero — Centered Statement',
    description: 'Centered, editorial homepage hero: big light-weight display headline over a single CTA, generous whitespace.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'hero',
    tags: ['section', 'hero', 'index', 'homepage', 'editorial'],
    spec: {
      type: 'theme.section',
      name: 'Hero — Centered Statement',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'hero',
        activation: 'section',
        title: 'Made to last a lifetime',
        subtitle: 'Slow-made goods for a considered home.',
        layout: { layout: 'stacked' },
        fields: {
          eyebrow: 'Est. 2014',
          primaryCtaLabel: 'Explore',
          primaryCtaUrl: 'https://example.com/collections/new',
          align: 'center',
        },
        blocks: [],
      },
      placement: { enabled_on: { templates: IDX } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'airy' },
        typography: { size: '2XL', weight: 'normal', lineHeight: 'tight', align: 'center' },
        colors: { overlayBackdropOpacity: 0.45, seed: '#8b6f47' },
        shape: { radius: 'sm', borderWidth: 'none', shadow: 'none', elevation: 'border' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'slow', easing: 'standard' },
      },
    },
  },

  {
    id: 'TBLK-IDX-03',
    name: 'Hero — Photo Overlay',
    description: 'Full-bleed photo homepage hero with a text overlay and scrim, headline + CTA anchored bottom-left.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'hero',
    tags: ['section', 'hero', 'index', 'homepage', 'photo-overlay'],
    spec: {
      type: 'theme.section',
      name: 'Hero — Photo Overlay',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'hero',
        activation: 'section',
        title: 'Drop 04 is live',
        subtitle: 'Limited run. Once it is gone, it is gone.',
        layout: { layout: 'stacked' },
        fields: {
          backgroundImageUrl: 'https://cdn.example.com/hero/fullbleed-drop.jpg',
          primaryCtaLabel: 'Shop the drop',
          primaryCtaUrl: 'https://example.com/collections/drop-04',
          overlayAnchor: 'bottom-left',
        },
        blocks: [],
      },
      placement: { enabled_on: { templates: IDX } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'full', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: '2XL', weight: 'bold', lineHeight: 'tight', align: 'left' },
        colors: { text: '#ffffff', background: '#0a0a0a', overlayBackdrop: '#000000', overlayBackdropOpacity: 0.4, seed: '#f43f5e' },
        shape: { radius: 'md', borderWidth: 'none', shadow: 'lg', elevation: 'glow' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'base', easing: 'enter' },
      },
    },
  },

  {
    id: 'TBLK-IDX-04',
    name: 'Hero — Ambient Gradient',
    description: 'Centered homepage hero on a soft ambient-gradient background with a rounded pill CTA.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'hero',
    tags: ['section', 'hero', 'index', 'homepage', 'gradient', 'playful'],
    spec: {
      type: 'theme.section',
      name: 'Hero — Ambient Gradient',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'hero',
        activation: 'section',
        title: 'Little things, big smiles',
        subtitle: 'Everyday joy, wrapped and ready to ship.',
        layout: { layout: 'stacked' },
        fields: {
          gradientFrom: '#fce7f3',
          gradientTo: '#ede9fe',
          primaryCtaLabel: 'Start shopping',
          primaryCtaUrl: 'https://example.com/collections/all',
          align: 'center',
        },
        blocks: [],
      },
      placement: { enabled_on: { templates: IDX } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'full', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: 'XL', weight: 'bold', lineHeight: 'normal', align: 'center' },
        colors: { overlayBackdropOpacity: 0.45, seed: '#a855f7' },
        shape: { radius: 'full', borderWidth: 'none', shadow: 'md', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'base', easing: 'standard' },
      },
    },
  },
  // ── FEATURE BENTO / VALUE-PROP (5) ─────────────────────────────────────────
  {
    id: 'TBLK-IDX-06',
    name: 'Feature Bento — Mixed Tiles',
    description: 'Bento grid of mixed-size feature tiles for the homepage, each block a value-prop with icon, heading and body.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'grid',
    tags: ['section', 'feature', 'bento', 'index', 'homepage'],
    spec: {
      type: 'theme.section',
      name: 'Feature Bento — Mixed Tiles',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'feature',
        activation: 'section',
        title: 'Why shoppers choose us',
        subtitle: 'Everything you would expect, and a few things you would not.',
        layout: { layout: 'grid', columns: 3 },
        fields: { featuredBlockIndex: 0 },
        blocks: [
          { kind: 'feature', text: 'Free carbon-neutral shipping on every order over $50, no code needed.', imageUrl: 'https://cdn.example.com/bento/shipping.jpg', fields: { heading: 'Free, fast shipping', icon: 'truck', span: 'large' } },
          { kind: 'feature', text: '60-day returns, prepaid label in the box.', fields: { heading: 'Easy returns', icon: 'refresh' } },
          { kind: 'feature', text: 'Real humans, 7 days a week.', fields: { heading: 'Human support', icon: 'chat' } },
          { kind: 'feature', text: 'Recycled and responsibly sourced materials across the range.', fields: { heading: 'Made responsibly', icon: 'leaf' } },
        ],
      },
      placement: { enabled_on: { templates: IDX } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: 'LG', weight: 'medium', lineHeight: 'normal', align: 'left' },
        colors: { overlayBackdropOpacity: 0.45, seed: '#2563eb' },
        shape: { radius: 'lg', borderWidth: 'thin', shadow: 'sm', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'base', easing: 'enter' },
      },
    },
  },

  {
    id: 'TBLK-IDX-07',
    name: 'Value Props — Three Column',
    description: 'Three-column value-prop row for the homepage: shipping, guarantee, support. Clean columns with icons.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'columns',
    tags: ['section', 'feature', 'value-props', 'index', 'homepage'],
    spec: {
      type: 'theme.section',
      name: 'Value Props — Three Column',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'feature',
        activation: 'section',
        title: 'The details that matter',
        layout: { layout: 'columns', columns: 3 },
        fields: {},
        blocks: [
          { kind: 'feature', text: 'Ships in 24 hours from our own warehouse.', fields: { heading: 'Ships next day', icon: 'bolt' } },
          { kind: 'feature', text: 'Lifetime warranty on every product we make.', fields: { heading: 'Lifetime warranty', icon: 'shield' } },
          { kind: 'feature', text: 'Talk to a specialist, not a script.', fields: { heading: 'Expert support', icon: 'headset' } },
        ],
      },
      placement: { enabled_on: { templates: IDX } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'medium', margin: 'none', gap: 'medium', density: 'compact' },
        typography: { size: 'MD', weight: 'medium', lineHeight: 'normal', align: 'center' },
        colors: { overlayBackdropOpacity: 0.45, seed: '#0ea5e9' },
        shape: { radius: 'md', borderWidth: 'thin', shadow: 'none', elevation: 'border' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'fast', easing: 'standard' },
      },
    },
  },

  {
    id: 'TBLK-IDX-08',
    name: 'Feature Bento — Editorial',
    description: 'Editorial bento grid pairing lifestyle imagery with short prose for a brand-story homepage section.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'grid',
    tags: ['section', 'feature', 'bento', 'index', 'editorial', 'homepage'],
    spec: {
      type: 'theme.section',
      name: 'Feature Bento — Editorial',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'feature',
        activation: 'section',
        title: 'A quieter kind of quality',
        subtitle: 'How we think about the things we make.',
        layout: { layout: 'masonry', columns: 2 },
        fields: {},
        blocks: [
          { kind: 'feature', text: 'Every piece is cut and finished by hand in small batches.', imageUrl: 'https://cdn.example.com/bento/atelier.jpg', fields: { heading: 'Small-batch craft', span: 'large' } },
          { kind: 'feature', text: 'We source natural fibers that soften with time.', imageUrl: 'https://cdn.example.com/bento/fibers.jpg', fields: { heading: 'Honest materials' } },
          { kind: 'feature', text: 'Designed to be repaired, not replaced.', fields: { heading: 'Built to mend' } },
        ],
      },
      placement: { enabled_on: { templates: IDX } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'loose', density: 'airy' },
        typography: { size: 'LG', weight: 'normal', lineHeight: 'relaxed', align: 'left' },
        colors: { overlayBackdropOpacity: 0.45 },
        shape: { radius: 'sm', borderWidth: 'none', shadow: 'sm', elevation: 'border' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'slow', easing: 'standard' },
      },
    },
  },
  {
    id: 'TBLK-IDX-10',
    name: 'Feature Bento — Playful Tiles',
    description: 'Friendly, rounded bento tiles with pastel fills for a homepage benefits section.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'grid',
    tags: ['section', 'feature', 'bento', 'index', 'homepage', 'playful'],
    spec: {
      type: 'theme.section',
      name: 'Feature Bento — Playful Tiles',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'feature',
        activation: 'section',
        title: 'Good stuff, made simple',
        layout: { layout: 'grid', columns: 2 },
        fields: {},
        blocks: [
          { kind: 'feature', text: 'Pick a plan, skip or cancel anytime.', fields: { heading: 'Flexible subscriptions', icon: 'calendar', tint: '#fef3c7' } },
          { kind: 'feature', text: 'Earn points on every order and unlock perks.', fields: { heading: 'Rewards that add up', icon: 'gift', tint: '#dbeafe' } },
          { kind: 'feature', text: 'Refer a friend, you both get $10.', fields: { heading: 'Share the love', icon: 'heart', tint: '#fce7f3' } },
          { kind: 'feature', text: 'Free samples tucked into every box.', fields: { heading: 'Little extras', icon: 'sparkles', tint: '#dcfce7' } },
        ],
      },
      placement: { enabled_on: { templates: IDX } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: 'LG', weight: 'bold', lineHeight: 'normal', align: 'left' },
        colors: { overlayBackdropOpacity: 0.45, seed: '#a855f7' },
        shape: { radius: 'xl', borderWidth: 'none', shadow: 'md', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'base', easing: 'standard' },
      },
    },
  },

  // ── SOCIAL PROOF (8) ───────────────────────────────────────────────────────
  {
    id: 'TBLK-IDX-11',
    name: 'Social Proof — Wall of Love',
    description: 'Photo-review "wall of love" grid for the homepage — verified-buyer star cards with media thumbnails. Grounded in Loox review-wall UGC pattern.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'reviews',
    tags: ['section', 'social-proof', 'reviews', 'index', 'ugc', 'wall-of-love'],
    spec: {
      type: 'theme.section',
      name: 'Social Proof — Wall of Love',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'reviews',
        activation: 'section',
        title: 'Loved by thousands',
        subtitle: 'Real photos from verified buyers.',
        layout: { layout: 'grid', columns: 3 },
        fields: { showVerifiedBadge: true, starColor: '#f5a623' },
        blocks: [
          { kind: 'review-card', text: 'Exactly as pictured — obsessed.', imageUrl: 'https://cdn.example.com/reviews/r1.jpg', fields: { author: 'Maya R.', rating: 5, verified: true } },
          { kind: 'review-card', text: 'Fast shipping and great quality.', imageUrl: 'https://cdn.example.com/reviews/r2.jpg', fields: { author: 'Devon K.', rating: 5, verified: true } },
          { kind: 'review-card', text: 'Bought two, gifting one.', imageUrl: 'https://cdn.example.com/reviews/r3.jpg', fields: { author: 'Priya S.', rating: 4, verified: true } },
          { kind: 'review-card', text: 'The photos do not do it justice.', imageUrl: 'https://cdn.example.com/reviews/r4.jpg', fields: { author: 'Sam T.', rating: 5, verified: true } },
          { kind: 'review-card', text: 'Came back for a second one already.', imageUrl: 'https://cdn.example.com/reviews/r5.jpg', fields: { author: 'Alex W.', rating: 5, verified: true } },
          { kind: 'review-card', text: 'Worth every penny.', imageUrl: 'https://cdn.example.com/reviews/r6.jpg', fields: { author: 'Jordan L.', rating: 5, verified: true } },
        ],
      },
      placement: { enabled_on: { templates: IDX } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: 'LG', weight: 'bold', lineHeight: 'normal', align: 'center' },
        colors: { overlayBackdropOpacity: 0.45, seed: '#f5a623' },
        shape: { radius: 'lg', borderWidth: 'thin', shadow: 'sm', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'base', easing: 'enter' },
      },
    },
  },

  {
    id: 'TBLK-IDX-12',
    name: 'Social Proof — Testimonial Carousel',
    description: 'Curated best-reviews testimonial slider for the homepage, one quote per slide with attribution. Grounded in Fera/Loox testimonial-carousel pattern.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'reviews',
    tags: ['section', 'social-proof', 'testimonials', 'index', 'carousel', 'homepage'],
    spec: {
      type: 'theme.section',
      name: 'Social Proof — Testimonial Carousel',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'reviews',
        activation: 'section',
        title: 'What people are saying',
        layout: { layout: 'carousel' },
        fields: { autoAdvance: true, showStars: true, starColor: '#f5a623' },
        blocks: [
          { kind: 'review-card', text: 'I have tried them all — nothing else comes close.', fields: { author: 'Robin C.', rating: 5, location: 'Austin, TX' } },
          { kind: 'review-card', text: 'Genuinely changed my daily routine.', fields: { author: 'Nadia H.', rating: 5, location: 'Toronto, CA' } },
          { kind: 'review-card', text: 'Support went above and beyond for my order.', fields: { author: 'Marcus D.', rating: 5, location: 'London, UK' } },
        ],
      },
      placement: { enabled_on: { templates: IDX } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'airy' },
        typography: { size: 'XL', weight: 'normal', lineHeight: 'relaxed', align: 'center' },
        colors: { overlayBackdropOpacity: 0.45, seed: '#8b6f47' },
        shape: { radius: 'md', borderWidth: 'none', shadow: 'none', elevation: 'border' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'slow', easing: 'standard' },
      },
    },
  },

  {
    id: 'TBLK-IDX-13',
    name: 'Social Proof — Single Spotlight',
    description: 'Single hero-quote spotlight for the homepage: one big testimonial with reviewer photo and star row.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'reviews',
    tags: ['section', 'social-proof', 'testimonials', 'index', 'spotlight', 'editorial'],
    spec: {
      type: 'theme.section',
      name: 'Social Proof — Single Spotlight',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'reviews',
        activation: 'section',
        title: 'In their words',
        layout: { layout: 'stacked' },
        fields: { showStars: true, starColor: '#111827' },
        blocks: [
          { kind: 'review-card', text: 'This is the first brand I have recommended to every friend without a second thought. The quality is the kind you feel the moment you open the box.', imageUrl: 'https://cdn.example.com/reviews/spotlight.jpg', fields: { author: 'Elena V.', rating: 5, role: 'Verified buyer' } },
        ],
      },
      placement: { enabled_on: { templates: IDX } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'narrow', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'airy' },
        typography: { size: 'XL', weight: 'normal', lineHeight: 'relaxed', align: 'center' },
        colors: { overlayBackdropOpacity: 0.45 },
        shape: { radius: 'sm', borderWidth: 'none', shadow: 'none', elevation: 'border' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'slow', easing: 'enter' },
      },
    },
  },

  {
    id: 'TBLK-IDX-14',
    name: 'Social Proof — Rating Banner',
    description: 'Full-width overall store-rating banner for the homepage: aggregate stars, average score and review count. Grounded in Fera overall-rating banner.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'badge',
    tags: ['section', 'social-proof', 'rating', 'index', 'homepage', 'trust'],
    spec: {
      type: 'theme.section',
      name: 'Social Proof — Rating Banner',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'trust-badge',
        activation: 'section',
        title: 'Rated 4.9 out of 5 by 8,000+ shoppers',
        layout: { layout: 'stacked' },
        fields: { averageRating: 4.9, reviewCount: 8191, starColor: '#f5a623', showStars: true },
        blocks: [],
      },
      placement: { enabled_on: { templates: IDX } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'full', zIndex: 'base' },
        spacing: { padding: 'medium', margin: 'none', gap: 'tight', density: 'compact' },
        typography: { size: 'LG', weight: 'medium', lineHeight: 'normal', align: 'center' },
        colors: { overlayBackdropOpacity: 0.45, seed: '#f5a623' },
        shape: { radius: 'md', borderWidth: 'thin', shadow: 'none', elevation: 'border' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'fast', easing: 'standard' },
      },
    },
  },

  {
    id: 'TBLK-IDX-15',
    name: 'Social Proof — Trust Badge Row',
    description: 'Row of trust marks for the homepage: guarantees, secure checkout, free returns. Grounded in Loox aggregate trust-badge pattern.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'badge',
    tags: ['section', 'social-proof', 'trust', 'index', 'homepage', 'badges'],
    spec: {
      type: 'theme.section',
      name: 'Social Proof — Trust Badge Row',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'trust-badge',
        activation: 'section',
        title: 'Shop with confidence',
        layout: { layout: 'columns', columns: 4 },
        fields: {},
        blocks: [
          { kind: 'badge', text: '30-day money-back guarantee', fields: { icon: 'shield-check' } },
          { kind: 'badge', text: 'Secure SSL checkout', fields: { icon: 'lock' } },
          { kind: 'badge', text: 'Free returns & exchanges', fields: { icon: 'refresh' } },
          { kind: 'badge', text: '1M+ orders shipped', fields: { icon: 'package' } },
        ],
      },
      placement: { enabled_on: { templates: IDX } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'medium', margin: 'none', gap: 'medium', density: 'compact' },
        typography: { size: 'SM', weight: 'medium', lineHeight: 'normal', align: 'center' },
        colors: { overlayBackdropOpacity: 0.45, seed: '#0ea5e9' },
        shape: { radius: 'md', borderWidth: 'thin', shadow: 'none', elevation: 'border' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'fast', easing: 'standard' },
      },
    },
  },

  {
    id: 'TBLK-IDX-16',
    name: 'Social Proof — Logo Marquee',
    description: 'Scroll-velocity logo/press marquee for the homepage: "as seen in" press and retail-partner logos. Grounded in design-vocabulary logo/trust marquee.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'marquee',
    tags: ['section', 'social-proof', 'logos', 'index', 'marquee', 'press'],
    spec: {
      type: 'theme.section',
      name: 'Social Proof — Logo Marquee',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'trust-badge',
        activation: 'section',
        title: 'As seen in',
        layout: { layout: 'carousel' },
        fields: { scrollVelocity: true, grayscale: true },
        blocks: [
          { kind: 'logo', imageUrl: 'https://cdn.example.com/press/logo-1.png', url: 'https://example.com/press', fields: { alt: 'Vogue' } },
          { kind: 'logo', imageUrl: 'https://cdn.example.com/press/logo-2.png', fields: { alt: 'Forbes' } },
          { kind: 'logo', imageUrl: 'https://cdn.example.com/press/logo-3.png', fields: { alt: 'TechCrunch' } },
          { kind: 'logo', imageUrl: 'https://cdn.example.com/press/logo-4.png', fields: { alt: 'GQ' } },
          { kind: 'logo', imageUrl: 'https://cdn.example.com/press/logo-5.png', fields: { alt: 'Wired' } },
        ],
      },
      placement: { enabled_on: { templates: IDX } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'full', zIndex: 'base' },
        spacing: { padding: 'medium', margin: 'none', gap: 'loose', density: 'comfortable' },
        typography: { size: 'XS', weight: 'medium', lineHeight: 'normal', align: 'center' },
        colors: { overlayBackdropOpacity: 0.45 },
        shape: { radius: 'none', borderWidth: 'none', shadow: 'none', elevation: 'border' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'slow', easing: 'standard' },
      },
    },
  },

  {
    id: 'TBLK-IDX-17',
    name: 'Social Proof — Stats Row',
    description: 'Animated stats row for the homepage: units sold, happy customers, average rating as big-number counters. Grounded in design-vocabulary stats row.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'stats',
    tags: ['section', 'social-proof', 'stats', 'index', 'homepage', 'counters'],
    spec: {
      type: 'theme.section',
      name: 'Social Proof — Stats Row',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'trust-badge',
        activation: 'section',
        title: 'The numbers speak for themselves',
        layout: { layout: 'columns', columns: 3 },
        fields: { animateCounters: true },
        blocks: [
          { kind: 'stat', text: 'Orders shipped', fields: { value: '1.2M+', prefix: '', suffix: '' } },
          { kind: 'stat', text: 'Five-star reviews', fields: { value: '8,000', suffix: '+' } },
          { kind: 'stat', text: 'Average rating', fields: { value: '4.9', suffix: '/5' } },
        ],
      },
      placement: { enabled_on: { templates: IDX } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: '2XL', weight: 'bold', lineHeight: 'tight', align: 'center' },
        colors: { overlayBackdropOpacity: 0.45, seed: '#f43f5e' },
        shape: { radius: 'lg', borderWidth: 'none', shadow: 'none', elevation: 'border' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'base', easing: 'enter' },
      },
    },
  },

  {
    id: 'TBLK-IDX-18',
    name: 'Social Proof — UGC Masonry Gallery',
    description: 'Site-wide UGC photo/video masonry gallery for the homepage, each tile linking to the source review. Grounded in Loox/Fera media-gallery pattern.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'gallery',
    tags: ['section', 'social-proof', 'ugc', 'index', 'gallery', 'masonry'],
    spec: {
      type: 'theme.section',
      name: 'Social Proof — UGC Masonry Gallery',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'reviews',
        activation: 'section',
        title: 'From our community',
        subtitle: 'Tag us to be featured.',
        layout: { layout: 'masonry', columns: 4 },
        fields: { lightbox: true, showStars: true, starColor: '#f5a623' },
        blocks: [
          { kind: 'review-card', imageUrl: 'https://cdn.example.com/ugc/u1.jpg', url: 'https://example.com/products/one', fields: { author: '@leah.makes', rating: 5 } },
          { kind: 'review-card', imageUrl: 'https://cdn.example.com/ugc/u2.jpg', url: 'https://example.com/products/two', fields: { author: '@studio.noon', rating: 5 } },
          { kind: 'review-card', imageUrl: 'https://cdn.example.com/ugc/u3.jpg', fields: { author: '@ok.daniel', rating: 4 } },
          { kind: 'review-card', imageUrl: 'https://cdn.example.com/ugc/u4.jpg', fields: { author: '@moss.and.co', rating: 5 } },
          { kind: 'review-card', imageUrl: 'https://cdn.example.com/ugc/u5.jpg', fields: { author: '@field.notes', rating: 5 } },
          { kind: 'review-card', imageUrl: 'https://cdn.example.com/ugc/u6.jpg', fields: { author: '@hey.marta', rating: 5 } },
        ],
      },
      placement: { enabled_on: { templates: IDX } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'full', zIndex: 'base' },
        spacing: { padding: 'medium', margin: 'none', gap: 'tight', density: 'comfortable' },
        typography: { size: 'MD', weight: 'medium', lineHeight: 'normal', align: 'center' },
        colors: { overlayBackdropOpacity: 0.45, seed: '#f5a623' },
        shape: { radius: 'md', borderWidth: 'none', shadow: 'sm', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'base', easing: 'enter' },
      },
    },
  },
];
