import type { RecipeSpec } from './recipe.js';
import type { TemplateEntry } from './templates.js';
import { THEME_PLACEABLE_TEMPLATES } from './allowed-values.js';

export const PART4_TEMPLATES: TemplateEntry[] = [
  // ═══════════════════════════════════════════════════════════════════
  // Category 12: Loyalty & Referrals (LOY-100 to LOY-108)
  // ═══════════════════════════════════════════════════════════════════

  {
    id: 'LOY-100',
    name: 'Theme Loyalty Widget',
    description: 'Storefront banner promoting loyalty rewards on every purchase.',
    category: 'STOREFRONT_UI',
    type: 'theme.banner',
    icon: 'banner',
    tags: ['loyalty', 'widget', 'rewards', 'storefront'],
    spec: {
      type: 'theme.banner',
      name: 'Theme Loyalty Widget',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        heading: 'Earn Rewards on Every Purchase',
        subheading: 'Join our loyalty program and start earning points today.',
        ctaText: 'Learn More',
        ctaUrl: 'https://example.com/rewards',
        enableAnimation: false,
      },
      placement: { enabled_on: { templates: ['index', 'product'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'medium', margin: 'none', gap: 'medium' },
        typography: { size: 'MD', weight: 'bold', lineHeight: 'normal', align: 'center' },
        colors: { text: '#ffffff', background: '#7c3aed', buttonBg: '#ffffff', buttonText: '#7c3aed' },
        shape: { radius: 'md', borderWidth: 'none', shadow: 'sm' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
      },
    } as RecipeSpec,
  },
  {
    id: 'LOY-101',
    name: 'Account Loyalty Dashboard',
    description: 'Full loyalty dashboard page in customer account showing points, tier, and rewards.',
    category: 'CUSTOMER_ACCOUNT',
    type: 'customerAccount.blocks',
    icon: 'customer',
    tags: ['loyalty', 'dashboard', 'account', 'points'],
    spec: {
      type: 'customerAccount.blocks',
      name: 'Account Loyalty Dashboard',
      category: 'CUSTOMER_ACCOUNT',
      requires: ['CUSTOMER_ACCOUNT_UI'],
      config: {
        target: 'customer-account.page.render',
        title: 'Loyalty Dashboard',
        blocks: [
          { kind: 'BADGE', content: 'Gold Member', tone: 'success' },
          { kind: 'TEXT', content: 'You have 2,500 loyalty points. Redeem them for exclusive rewards.' },
          { kind: 'LINK', content: 'View Rewards Catalog', url: 'https://example.com/rewards' },
        ],
        b2bOnly: false,
      },
    } as RecipeSpec,
  },
  {
    id: 'LOY-102',
    name: 'Order Status Loyalty Earned',
    description: 'Show loyalty points earned for a specific order on the order status page.',
    category: 'CUSTOMER_ACCOUNT',
    type: 'customerAccount.blocks',
    icon: 'customer',
    tags: ['loyalty', 'order-status', 'points', 'earned'],
    spec: {
      type: 'customerAccount.blocks',
      name: 'Order Status Loyalty Earned',
      category: 'CUSTOMER_ACCOUNT',
      requires: ['CUSTOMER_ACCOUNT_UI'],
      config: {
        target: 'customer-account.order-status.block.render',
        title: 'Points Earned',
        blocks: [
          { kind: 'BADGE', content: '+150 Points', tone: 'success' },
          { kind: 'TEXT', content: 'You earned 150 loyalty points with this order.' },
        ],
        b2bOnly: false,
      },
    } as RecipeSpec,
  },
  {
    id: 'LOY-103',
    name: 'Orders Index Loyalty Promo',
    description: 'Announcement banner on orders list promoting loyalty bonus events.',
    category: 'CUSTOMER_ACCOUNT',
    type: 'customerAccount.blocks',
    icon: 'customer',
    tags: ['loyalty', 'orders', 'promo', 'announcement'],
    spec: {
      type: 'customerAccount.blocks',
      name: 'Orders Index Loyalty Promo',
      category: 'CUSTOMER_ACCOUNT',
      requires: ['CUSTOMER_ACCOUNT_UI'],
      config: {
        target: 'customer-account.order-index.announcement.render',
        title: 'Loyalty Bonus',
        blocks: [
          { kind: 'TEXT', content: 'Double points this weekend on all orders!' },
          { kind: 'LINK', content: 'Shop Now', url: 'https://example.com/collections/all' },
        ],
        b2bOnly: false,
      },
    } as RecipeSpec,
  },
  {
    id: 'LOY-104',
    name: 'POS Loyalty Lookup',
    description: 'Display customer loyalty points and tier at the POS counter.',
    category: 'ADMIN_UI',
    type: 'pos.extension',
    icon: 'pos',
    tags: ['pos', 'loyalty', 'points', 'lookup'],
    spec: {
      type: 'pos.extension',
      name: 'POS Loyalty Lookup',
      category: 'ADMIN_UI',
      requires: [],
      config: {
        target: 'pos.customer-details.block.render',
        label: 'Loyalty Points',
        blockKind: 'block',
      },
    } as RecipeSpec,
  },
  {
    id: 'LOY-105',
    name: 'POS Loyalty Redeem Action',
    description: 'Staff action to redeem loyalty points for a cart line item at POS.',
    category: 'ADMIN_UI',
    type: 'pos.extension',
    icon: 'pos',
    tags: ['pos', 'loyalty', 'redeem', 'action'],
    spec: {
      type: 'pos.extension',
      name: 'POS Loyalty Redeem Action',
      category: 'ADMIN_UI',
      requires: [],
      config: {
        target: 'pos.cart.line-item-details.action.render',
        label: 'Redeem Points',
        blockKind: 'action',
      },
    } as RecipeSpec,
  },
  {
    id: 'LOY-106',
    name: 'Admin Customer Loyalty Card',
    description: 'Show loyalty points and tier info on the customer details page in admin.',
    category: 'ADMIN_UI',
    type: 'admin.block',
    icon: 'admin',
    tags: ['admin', 'loyalty', 'customer', 'points'],
    spec: {
      type: 'admin.block',
      name: 'Admin Customer Loyalty Card',
      category: 'ADMIN_UI',
      requires: [],
      config: {
        target: 'admin.customer-details.block.render',
        label: 'Loyalty Info',
      },
    } as RecipeSpec,
  },
  {
    id: 'LOY-107',
    name: 'Flow Points Award Automation',
    description: 'Automatically tag customers and log points when an order is created.',
    category: 'FLOW',
    type: 'flow.automation',
    icon: 'flow',
    tags: ['flow', 'loyalty', 'points', 'automation'],
    spec: {
      type: 'flow.automation',
      name: 'Flow Points Award Automation',
      category: 'FLOW',
      requires: [],
      config: {
        trigger: 'SHOPIFY_WEBHOOK_ORDER_CREATED',
        steps: [
          { kind: 'TAG_CUSTOMER', tag: 'points-awarded' },
          { kind: 'WRITE_TO_STORE', storeKey: 'loyalty-points', payloadMapping: { customerId: '{{customer.id}}', orderId: '{{order.id}}' } },
        ],
      },
    } as RecipeSpec,
  },
  {
    id: 'LOY-108',
    name: 'Referral Overlay',
    description: 'Floating referral CTA widget shown sitewide to encourage sharing.',
    category: 'STOREFRONT_UI',
    type: 'theme.floatingWidget',
    icon: 'widget',
    tags: ['referral', 'overlay', 'floating', 'sharing'],
    spec: {
      type: 'theme.floatingWidget',
      name: 'Referral Overlay',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        variant: 'custom',
        label: 'Refer & Earn',
        anchor: 'bottom_right',
        offsetX: 24,
        offsetY: 24,
        onClick: 'open_url',
        url: 'https://example.com/referral',
        hideOnMobile: false,
        hideOnDesktop: false,
      },
      style: {
        layout: { mode: 'floating', anchor: 'bottom', offsetX: 24, offsetY: 24, width: 'auto', zIndex: 'overlay' },
        spacing: { padding: 'medium', margin: 'none', gap: 'tight' },
        typography: { size: 'SM', weight: 'bold', lineHeight: 'normal', align: 'center' },
        colors: { text: '#ffffff', background: '#7c3aed', buttonBg: '#ffffff', buttonText: '#7c3aed' },
        shape: { radius: 'full', borderWidth: 'none', shadow: 'lg' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
      },
    } as RecipeSpec,
  },

  // ═══════════════════════════════════════════════════════════════════
  // Category 13: Analytics & Attribution (ANA-109 to ANA-117)
  // ═══════════════════════════════════════════════════════════════════

  {
    id: 'ANA-109',
    name: 'Full Funnel Pixel Pack',
    description: 'Track the complete purchase funnel from page view to checkout completed.',
    category: 'INTEGRATION',
    type: 'analytics.pixel',
    icon: 'analytics',
    tags: ['analytics', 'pixel', 'funnel', 'full-funnel'],
    spec: {
      type: 'analytics.pixel',
      name: 'Full Funnel Pixel Pack',
      category: 'INTEGRATION',
      requires: [],
      config: {
        events: ['page_viewed', 'product_viewed', 'product_added_to_cart', 'checkout_started', 'checkout_completed'],
      },
    } as RecipeSpec,
  },
  {
    id: 'ANA-110',
    name: 'Product View Quality Tracker',
    description: 'Track product views to measure engagement and build remarketing audiences.',
    category: 'INTEGRATION',
    type: 'analytics.pixel',
    icon: 'analytics',
    tags: ['analytics', 'product', 'engagement', 'views'],
    spec: {
      type: 'analytics.pixel',
      name: 'Product View Quality Tracker',
      category: 'INTEGRATION',
      requires: [],
      config: {
        events: ['product_viewed'],
      },
    } as RecipeSpec,
  },
  {
    id: 'ANA-111',
    name: 'Search Intent Tracker',
    description: 'Capture search queries and outcomes to optimize product discovery.',
    category: 'INTEGRATION',
    type: 'analytics.pixel',
    icon: 'analytics',
    tags: ['analytics', 'search', 'intent', 'discovery'],
    spec: {
      type: 'analytics.pixel',
      name: 'Search Intent Tracker',
      category: 'INTEGRATION',
      requires: [],
      config: {
        events: ['search_submitted'],
      },
    } as RecipeSpec,
  },
  {
    id: 'ANA-112',
    name: 'Checkout Form Submit Tracker',
    description: 'Track checkout form submissions at each step for drop-off analysis.',
    category: 'INTEGRATION',
    type: 'analytics.pixel',
    icon: 'analytics',
    tags: ['analytics', 'checkout', 'form', 'drop-off'],
    spec: {
      type: 'analytics.pixel',
      name: 'Checkout Form Submit Tracker',
      category: 'INTEGRATION',
      requires: [],
      config: {
        events: ['checkout_contact_info_submitted', 'checkout_shipping_info_submitted', 'payment_info_submitted'],
      },
    } as RecipeSpec,
  },
  {
    id: 'ANA-113',
    name: 'Cart Health Tracker',
    description: 'Monitor cart activity including views, adds, and removes for conversion insights.',
    category: 'INTEGRATION',
    type: 'analytics.pixel',
    icon: 'analytics',
    tags: ['analytics', 'cart', 'health', 'conversion'],
    spec: {
      type: 'analytics.pixel',
      name: 'Cart Health Tracker',
      category: 'INTEGRATION',
      requires: [],
      config: {
        events: ['cart_viewed', 'product_added_to_cart', 'product_removed_from_cart'],
      },
    } as RecipeSpec,
  },
  {
    id: 'ANA-114',
    name: 'Collection Engagement Tracker',
    description: 'Track collection page views for merchandising and remarketing optimization.',
    category: 'INTEGRATION',
    type: 'analytics.pixel',
    icon: 'analytics',
    tags: ['analytics', 'collection', 'engagement', 'remarketing'],
    spec: {
      type: 'analytics.pixel',
      name: 'Collection Engagement Tracker',
      category: 'INTEGRATION',
      requires: [],
      config: {
        events: ['collection_viewed'],
      },
    } as RecipeSpec,
  },
  {
    id: 'ANA-115',
    name: 'Extension Error Monitor',
    description: 'Monitor UI extension errors to detect and alert on failures.',
    category: 'INTEGRATION',
    type: 'analytics.pixel',
    icon: 'analytics',
    tags: ['analytics', 'error', 'monitor', 'extension'],
    spec: {
      type: 'analytics.pixel',
      name: 'Extension Error Monitor',
      category: 'INTEGRATION',
      requires: [],
      config: {
        events: ['ui_extension_errored'],
      },
    } as RecipeSpec,
  },
  {
    id: 'ANA-116',
    name: 'Checkout Completed Tracker',
    description: 'Track checkout completions including post-purchase upsell page triggers.',
    category: 'INTEGRATION',
    type: 'analytics.pixel',
    icon: 'analytics',
    tags: ['analytics', 'checkout', 'completed', 'purchase'],
    spec: {
      type: 'analytics.pixel',
      name: 'Checkout Completed Tracker',
      category: 'INTEGRATION',
      requires: [],
      config: {
        events: ['checkout_completed'],
      },
    } as RecipeSpec,
  },
  {
    id: 'ANA-117',
    name: 'Analytics Loader',
    description: 'Global page view tracker to load analytics SDK via theme embed.',
    category: 'INTEGRATION',
    type: 'analytics.pixel',
    icon: 'analytics',
    tags: ['analytics', 'loader', 'embed', 'page-view'],
    spec: {
      type: 'analytics.pixel',
      name: 'Analytics Loader',
      category: 'INTEGRATION',
      requires: [],
      config: {
        events: ['page_viewed'],
      },
    } as RecipeSpec,
  },

  // ═══════════════════════════════════════════════════════════════════
  // Category 14: Automation & Ops (OPS-118 to OPS-126)
  // ═══════════════════════════════════════════════════════════════════

  {
    id: 'OPS-118',
    name: 'Flow Order Paid Notify Slack',
    description: 'Send a Slack notification when a new order is created.',
    category: 'FLOW',
    type: 'flow.automation',
    icon: 'flow',
    tags: ['flow', 'order', 'slack', 'notification'],
    spec: {
      type: 'flow.automation',
      name: 'Flow Order Paid Notify Slack',
      category: 'FLOW',
      requires: [],
      config: {
        trigger: 'SHOPIFY_WEBHOOK_ORDER_CREATED',
        steps: [
          { kind: 'SEND_SLACK_MESSAGE', channel: '#orders', text: 'New order received: {{order.name}} for {{order.total_price}}' },
        ],
      },
    } as RecipeSpec,
  },
  {
    id: 'OPS-119',
    name: 'Flow High-Value Order Tag',
    description: 'Automatically tag high-value orders for priority processing.',
    category: 'FLOW',
    type: 'flow.automation',
    icon: 'flow',
    tags: ['flow', 'order', 'tag', 'high-value'],
    spec: {
      type: 'flow.automation',
      name: 'Flow High-Value Order Tag',
      category: 'FLOW',
      requires: [],
      config: {
        trigger: 'SHOPIFY_WEBHOOK_ORDER_CREATED',
        steps: [
          { kind: 'TAG_ORDER', tags: 'high-value' },
        ],
      },
    } as RecipeSpec,
  },
  {
    id: 'OPS-120',
    name: 'Admin Run Automation Link',
    description: 'Quick action block on order details to trigger automation workflows.',
    category: 'ADMIN_UI',
    type: 'admin.block',
    icon: 'admin',
    tags: ['admin', 'automation', 'order', 'action'],
    spec: {
      type: 'admin.block',
      name: 'Admin Run Automation Link',
      category: 'ADMIN_UI',
      requires: [],
      config: {
        target: 'admin.order-details.block.render',
        label: 'Run Automation',
      },
    } as RecipeSpec,
  },
  {
    id: 'OPS-121',
    name: 'Admin Segmentation Templates',
    description: 'Provide customer segment templates for marketing operations in admin.',
    category: 'ADMIN_UI',
    type: 'admin.block',
    icon: 'admin',
    tags: ['admin', 'segmentation', 'templates', 'marketing'],
    spec: {
      type: 'admin.block',
      name: 'Admin Segmentation Templates',
      category: 'ADMIN_UI',
      requires: [],
      config: {
        target: 'admin.customer-details.block.render',
        label: 'Segment Templates',
      },
    } as RecipeSpec,
  },
  {
    id: 'OPS-122',
    name: 'Admin Validation Settings Console',
    description: 'Merchant settings UI for configuring cart and checkout validation rules.',
    category: 'ADMIN_UI',
    type: 'admin.block',
    icon: 'admin',
    tags: ['admin', 'validation', 'settings', 'rules'],
    spec: {
      type: 'admin.block',
      name: 'Admin Validation Settings Console',
      category: 'ADMIN_UI',
      requires: [],
      config: {
        target: 'admin.order-details.block.render',
        label: 'Validation Rules',
      },
    } as RecipeSpec,
  },
  {
    id: 'OPS-123',
    name: 'POS Home Staff Toolkit',
    description: 'Entry tile on POS home screen launching a staff operations hub.',
    category: 'ADMIN_UI',
    type: 'pos.extension',
    icon: 'pos',
    tags: ['pos', 'staff', 'toolkit', 'home'],
    spec: {
      type: 'pos.extension',
      name: 'POS Home Staff Toolkit',
      category: 'ADMIN_UI',
      requires: [],
      config: {
        target: 'pos.home.tile.render',
        label: 'Staff Toolkit',
        blockKind: 'tile',
      },
    } as RecipeSpec,
  },
  {
    id: 'OPS-124',
    name: 'POS Receipt Footer Campaign',
    description: 'Add survey link or promo QR code to POS receipt footer.',
    category: 'ADMIN_UI',
    type: 'pos.extension',
    icon: 'pos',
    tags: ['pos', 'receipt', 'campaign', 'promo'],
    spec: {
      type: 'pos.extension',
      name: 'POS Receipt Footer Campaign',
      category: 'ADMIN_UI',
      requires: [],
      config: {
        target: 'pos.receipt-footer.block.render',
        label: 'Receipt Promo',
        blockKind: 'block',
      },
    } as RecipeSpec,
  },
  {
    id: 'OPS-125',
    name: 'Purchase Options Blueprint',
    description: 'Scaffold a checkout UI extension for subscription and preorder workflows.',
    category: 'ADMIN_UI',
    type: 'platform.extensionBlueprint',
    icon: 'blueprint',
    tags: ['blueprint', 'purchase-options', 'subscription', 'preorder'],
    spec: {
      type: 'platform.extensionBlueprint',
      name: 'Purchase Options Blueprint',
      category: 'ADMIN_UI',
      requires: [],
      config: {
        surface: 'CHECKOUT_UI',
        goal: 'Extend purchase options card with subscription and preorder workflows',
        suggestedFiles: ['src/PurchaseOptions.tsx', 'src/hooks/useSubscription.ts'],
      },
    } as RecipeSpec,
  },
  {
    id: 'OPS-126',
    name: 'Subscription Link Blueprint',
    description: 'Scaffold a theme app extension for subscription management links.',
    category: 'ADMIN_UI',
    type: 'platform.extensionBlueprint',
    icon: 'blueprint',
    tags: ['blueprint', 'subscription', 'link', 'theme'],
    spec: {
      type: 'platform.extensionBlueprint',
      name: 'Subscription Link Blueprint',
      category: 'ADMIN_UI',
      requires: [],
      config: {
        surface: 'THEME_APP_EXTENSION',
        goal: 'Add subscription management link to admin order cards and storefront',
        suggestedFiles: ['blocks/subscription-link.liquid', 'assets/subscription.js'],
      },
    } as RecipeSpec,
  },

  // ═══════════════════════════════════════════════════════════════════
  // Coverage completeness: additional templates for all RecipeSpec types
  // ═══════════════════════════════════════════════════════════════════

  {
    id: 'EFF-127',
    name: 'Winter Snowfall Effect',
    description: 'Full-viewport snowfall overlay for seasonal or winter theme decoration.',
    category: 'STOREFRONT_UI',
    type: 'theme.effect',
    icon: 'banner',
    tags: ['effect', 'snowfall', 'winter', 'decoration'],
    spec: {
      type: 'theme.effect',
      name: 'Winter Snowfall Effect',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        effectKind: 'snowfall',
        intensity: 'medium',
        speed: 'normal',
        startTrigger: 'page_load',
        durationSeconds: 0,
        overlayPlacement: 'full_screen',
        reducedMotion: true,
      },
      placement: { enabled_on: { templates: ['index', 'product', 'collection'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'overlay', anchor: 'top', offsetX: 0, offsetY: 0, width: 'full', zIndex: 'overlay' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
      },
    } as RecipeSpec,
  },
  {
    id: 'EFF-128',
    name: 'Confetti Celebration Effect',
    description: 'Confetti burst overlay for product launches, sales, or celebrations.',
    category: 'STOREFRONT_UI',
    type: 'theme.effect',
    icon: 'banner',
    tags: ['effect', 'confetti', 'celebration', 'launch'],
    spec: {
      type: 'theme.effect',
      name: 'Confetti Celebration Effect',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        effectKind: 'confetti',
        intensity: 'high',
        speed: 'fast',
        startTrigger: 'page_load',
        durationSeconds: 5,
        overlayPlacement: 'full_screen',
        reducedMotion: true,
      },
      placement: { enabled_on: { templates: ['index'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'overlay', anchor: 'top', offsetX: 0, offsetY: 0, width: 'full', zIndex: 'overlay' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
      },
    } as RecipeSpec,
  },
  {
    id: 'PRX-129',
    name: 'Store Locator Widget',
    description: 'App Proxy powered store locator page for finding nearby locations.',
    category: 'STOREFRONT_UI',
    type: 'proxy.widget',
    icon: 'widget',
    tags: ['proxy', 'store-locator', 'widget', 'location'],
    spec: {
      type: 'proxy.widget',
      name: 'Store Locator Widget',
      category: 'STOREFRONT_UI',
      requires: ['APP_PROXY'],
      config: {
        widgetId: 'store-locator',
        mode: 'HTML',
        title: 'Find a Store',
        message: 'Use our store locator to find the nearest retail location.',
      },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium' },
        typography: { size: 'MD', weight: 'normal', lineHeight: 'normal', align: 'center' },
        colors: { text: '#1e293b', background: '#ffffff' },
        shape: { radius: 'md', borderWidth: 'thin', shadow: 'sm' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
      },
    } as RecipeSpec,
  },
  {
    id: 'PRX-130',
    name: 'Referral Program Page',
    description: 'App Proxy page for a customer referral program with sharing options.',
    category: 'STOREFRONT_UI',
    type: 'proxy.widget',
    icon: 'widget',
    tags: ['proxy', 'referral', 'widget', 'sharing'],
    spec: {
      type: 'proxy.widget',
      name: 'Referral Program Page',
      category: 'STOREFRONT_UI',
      requires: ['APP_PROXY'],
      config: {
        widgetId: 'referral-program',
        mode: 'HTML',
        title: 'Refer a Friend',
        message: 'Share your link and earn rewards when friends make a purchase.',
      },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium' },
        typography: { size: 'MD', weight: 'normal', lineHeight: 'normal', align: 'center' },
        colors: { text: '#1e293b', background: '#eff6ff', buttonBg: '#2563eb', buttonText: '#ffffff' },
        shape: { radius: 'lg', borderWidth: 'none', shadow: 'sm' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
      },
    } as RecipeSpec,
  },
  {
    id: 'PPO-131',
    name: 'Post-Purchase Upsell Offer',
    description: 'One-click upsell offer shown after payment on the post-purchase page.',
    category: 'STOREFRONT_UI',
    type: 'postPurchase.offer',
    icon: 'checkout',
    tags: ['post-purchase', 'upsell', 'offer', 'one-click'],
    spec: {
      type: 'postPurchase.offer',
      name: 'Post-Purchase Upsell Offer',
      category: 'STOREFRONT_UI',
      requires: ['CHECKOUT_UI_INFO_SHIP_PAY'],
      config: {
        offerTitle: 'Add this to your order',
        message: 'Get 15% off this popular add-on. One-click to add it now.',
      },
    } as RecipeSpec,
  },
  {
    id: 'PPO-132',
    name: 'Post-Purchase Extended Warranty',
    description: 'Offer an extended warranty or protection plan after checkout.',
    category: 'STOREFRONT_UI',
    type: 'postPurchase.offer',
    icon: 'checkout',
    tags: ['post-purchase', 'warranty', 'protection', 'offer'],
    spec: {
      type: 'postPurchase.offer',
      name: 'Post-Purchase Extended Warranty',
      category: 'STOREFRONT_UI',
      requires: ['CHECKOUT_UI_INFO_SHIP_PAY'],
      config: {
        offerTitle: 'Protect your purchase',
        message: 'Add a 2-year extended warranty for peace of mind.',
      },
    } as RecipeSpec,
  },
  {
    id: 'CKU-133',
    name: 'Checkout Upsell Add-On',
    description: 'Offer a discounted add-on product at checkout to increase AOV.',
    category: 'STOREFRONT_UI',
    type: 'checkout.upsell',
    icon: 'checkout',
    tags: ['checkout', 'upsell', 'aov', 'add-on'],
    spec: {
      type: 'checkout.upsell',
      name: 'Checkout Upsell Add-On',
      category: 'STOREFRONT_UI',
      requires: ['CHECKOUT_UI_INFO_SHIP_PAY'],
      config: {
        offerTitle: 'Add this for 20% off!',
        productVariantGid: 'gid://shopify/ProductVariant/0000000000',
        discountPercent: 20,
      },
    } as RecipeSpec,
  },
  {
    id: 'CKU-134',
    name: 'Checkout Upsell Gift Card',
    description: 'Suggest a gift card purchase at checkout for gifting occasions.',
    category: 'STOREFRONT_UI',
    type: 'checkout.upsell',
    icon: 'checkout',
    tags: ['checkout', 'upsell', 'gift-card', 'gifting'],
    spec: {
      type: 'checkout.upsell',
      name: 'Checkout Upsell Gift Card',
      category: 'STOREFRONT_UI',
      requires: ['CHECKOUT_UI_INFO_SHIP_PAY'],
      config: {
        offerTitle: 'Add a gift card?',
        productVariantGid: 'gid://shopify/ProductVariant/0000000001',
        discountPercent: 0,
      },
    } as RecipeSpec,
  },
  {
    id: 'INT-135',
    name: 'ERP Order Sync',
    description: 'Sync new order data to an external ERP system via HTTP integration.',
    category: 'INTEGRATION',
    type: 'integration.httpSync',
    icon: 'integration',
    tags: ['integration', 'erp', 'sync', 'order'],
    spec: {
      type: 'integration.httpSync',
      name: 'ERP Order Sync',
      category: 'INTEGRATION',
      requires: [],
      config: {
        connectorId: 'erp-connector',
        endpointPath: '/api/orders/ingest',
        trigger: 'SHOPIFY_WEBHOOK_ORDER_CREATED',
        payloadMapping: { orderId: '{{order.id}}', total: '{{order.total_price}}' },
      },
    } as RecipeSpec,
  },
  {
    id: 'INT-136',
    name: 'CRM Customer Sync',
    description: 'Push new customer data to an external CRM via HTTP on creation.',
    category: 'INTEGRATION',
    type: 'integration.httpSync',
    icon: 'integration',
    tags: ['integration', 'crm', 'sync', 'customer'],
    spec: {
      type: 'integration.httpSync',
      name: 'CRM Customer Sync',
      category: 'INTEGRATION',
      requires: [],
      config: {
        connectorId: 'crm-connector',
        endpointPath: '/api/customers/sync',
        trigger: 'SHOPIFY_WEBHOOK_CUSTOMER_CREATED',
        payloadMapping: { customerId: '{{customer.id}}', email: '{{customer.email}}' },
      },
    } as RecipeSpec,
  },
  {
    id: 'VAL-137',
    name: 'Cart Max Quantity Validation',
    description: 'Block checkout when any SKU quantity exceeds the allowed maximum.',
    category: 'FUNCTION',
    type: 'functions.cartAndCheckoutValidation',
    icon: 'validation',
    tags: ['validation', 'cart', 'quantity', 'limit'],
    spec: {
      type: 'functions.cartAndCheckoutValidation',
      name: 'Cart Max Quantity Validation',
      category: 'FUNCTION',
      requires: ['VALIDATION_FUNCTION'],
      config: {
        rules: [
          {
            when: { maxQuantityPerSku: 10 },
            errorMessage: 'You can order a maximum of 10 units per item.',
          },
        ],
      },
    } as RecipeSpec,
  },
  {
    id: 'VAL-138',
    name: 'Country Block Validation',
    description: 'Block checkout from restricted countries for compliance.',
    category: 'FUNCTION',
    type: 'functions.cartAndCheckoutValidation',
    icon: 'validation',
    tags: ['validation', 'country', 'block', 'compliance'],
    spec: {
      type: 'functions.cartAndCheckoutValidation',
      name: 'Country Block Validation',
      category: 'FUNCTION',
      requires: ['VALIDATION_FUNCTION'],
      config: {
        rules: [
          {
            when: { blockCountryCodes: ['XX'] },
            errorMessage: 'We cannot ship to your country at this time.',
          },
        ],
      },
    } as RecipeSpec,
  },
  {
    id: 'FUL-139',
    name: 'Ship Alone Fragile Items',
    description: 'Force fragile tagged items to ship alone in separate packages.',
    category: 'FUNCTION',
    type: 'functions.fulfillmentConstraints',
    icon: 'shipping',
    tags: ['fulfillment', 'fragile', 'ship-alone', 'constraints'],
    spec: {
      type: 'functions.fulfillmentConstraints',
      name: 'Ship Alone Fragile Items',
      category: 'FUNCTION',
      requires: [],
      config: {
        rules: [
          { when: { productTagIn: ['fragile'] }, apply: { shipAlone: true } },
        ],
      },
    } as RecipeSpec,
  },
  {
    id: 'FUL-140',
    name: 'Group Hazmat Items',
    description: 'Group items tagged as hazmat into a separate fulfillment group.',
    category: 'FUNCTION',
    type: 'functions.fulfillmentConstraints',
    icon: 'shipping',
    tags: ['fulfillment', 'hazmat', 'grouping', 'constraints'],
    spec: {
      type: 'functions.fulfillmentConstraints',
      name: 'Group Hazmat Items',
      category: 'FUNCTION',
      requires: [],
      config: {
        rules: [
          { when: { productTagIn: ['hazmat'] }, apply: { groupWithTag: 'hazmat-shipment' } },
        ],
      },
    } as RecipeSpec,
  },
  {
    id: 'ORT-141',
    name: 'Prefer Nearest Warehouse',
    description: 'Route orders to the nearest warehouse location by priority.',
    category: 'FUNCTION',
    type: 'functions.orderRoutingLocationRule',
    icon: 'shipping',
    tags: ['order-routing', 'warehouse', 'location', 'fulfillment'],
    spec: {
      type: 'functions.orderRoutingLocationRule',
      name: 'Prefer Nearest Warehouse',
      category: 'FUNCTION',
      requires: [],
      config: {
        rules: [
          { when: {}, apply: { priority: 10 } },
        ],
      },
    } as RecipeSpec,
  },
  {
    id: 'ORT-142',
    name: 'Country-Based Routing',
    description: 'Route orders to a specific location based on the shipping country.',
    category: 'FUNCTION',
    type: 'functions.orderRoutingLocationRule',
    icon: 'shipping',
    tags: ['order-routing', 'country', 'location', 'international'],
    spec: {
      type: 'functions.orderRoutingLocationRule',
      name: 'Country-Based Routing',
      category: 'FUNCTION',
      requires: [],
      config: {
        rules: [
          { when: { countryCode: 'US' }, apply: { preferLocationId: 'us-warehouse-01', priority: 1 } },
          { when: { countryCode: 'GB' }, apply: { preferLocationId: 'uk-warehouse-01', priority: 1 } },
        ],
      },
    } as RecipeSpec,
  },
];
