import type { RecipeSpec } from './recipe.js';
import type { TemplateEntry } from './templates.js';

export const PART2_TEMPLATES: TemplateEntry[] = [
  // ═══════════════════════════════════════════════════════════════════
  // Category 5: Checkout UX Plus (CHK-037 to CHK-045)
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'CHK-037',
    name: 'Address Autocomplete Provider',
    description: 'Provide address suggestions during checkout to speed up form completion.',
    category: 'STOREFRONT_UI',
    type: 'checkout.block',
    icon: 'checkout',
    tags: ['checkout', 'address', 'autocomplete', 'plus'],
    spec: {
      type: 'checkout.block',
      name: 'Address Autocomplete Provider',
      category: 'STOREFRONT_UI',
      requires: ['CHECKOUT_UI_INFO_SHIP_PAY'],
      config: {
        target: 'purchase.address-autocomplete.suggest',
        title: 'Address Suggestions',
        message: 'Start typing your address and select from the suggestions below.',
      },
    } as RecipeSpec,
  },
  {
    id: 'CHK-038',
    name: 'Contact Field Helper',
    description: 'Display helpful tips below the contact information fields at checkout.',
    category: 'STOREFRONT_UI',
    type: 'checkout.block',
    icon: 'checkout',
    tags: ['checkout', 'contact', 'helper', 'plus'],
    spec: {
      type: 'checkout.block',
      name: 'Contact Field Helper',
      category: 'STOREFRONT_UI',
      requires: ['CHECKOUT_UI_INFO_SHIP_PAY'],
      config: {
        target: 'purchase.checkout.contact.render-after',
        title: 'Contact Tips',
        message: 'We will only use your email for order updates and shipping notifications.',
      },
    } as RecipeSpec,
  },
  {
    id: 'CHK-039',
    name: 'Checkout Header Trust Banner',
    description: 'Show a trust and security message in the checkout header area.',
    category: 'STOREFRONT_UI',
    type: 'checkout.block',
    icon: 'checkout',
    tags: ['checkout', 'trust', 'header', 'plus'],
    spec: {
      type: 'checkout.block',
      name: 'Checkout Header Trust Banner',
      category: 'STOREFRONT_UI',
      requires: ['CHECKOUT_UI_INFO_SHIP_PAY'],
      config: {
        target: 'purchase.checkout.header.render-after',
        title: 'Secure Checkout',
        message: 'Your payment information is encrypted and secure. We never store card details.',
      },
    } as RecipeSpec,
  },
  {
    id: 'CHK-040',
    name: 'Checkout Footer Policy Links',
    description: 'Add policy and support links to the checkout footer for transparency.',
    category: 'STOREFRONT_UI',
    type: 'checkout.block',
    icon: 'checkout',
    tags: ['checkout', 'footer', 'policy', 'plus'],
    spec: {
      type: 'checkout.block',
      name: 'Checkout Footer Policy Links',
      category: 'STOREFRONT_UI',
      requires: ['CHECKOUT_UI_INFO_SHIP_PAY'],
      config: {
        target: 'purchase.checkout.footer.render-after',
        title: 'Policies & Support',
        message: 'View our return policy, privacy policy, and contact support for assistance.',
      },
    } as RecipeSpec,
  },
  {
    id: 'CHK-041',
    name: 'Action-Area Warning',
    description: 'Remind customers to review their order before completing the purchase.',
    category: 'STOREFRONT_UI',
    type: 'checkout.block',
    icon: 'checkout',
    tags: ['checkout', 'warning', 'review', 'plus'],
    spec: {
      type: 'checkout.block',
      name: 'Action-Area Warning',
      category: 'STOREFRONT_UI',
      requires: ['CHECKOUT_UI_INFO_SHIP_PAY'],
      config: {
        target: 'purchase.checkout.actions.render-before',
        title: 'Review Your Order',
        message: 'Please double-check your shipping address and items before placing the order.',
      },
    } as RecipeSpec,
  },
  {
    id: 'CHK-042',
    name: 'Order Summary Savings Breakdown',
    description: 'Show per-item savings and discount details in the order summary.',
    category: 'STOREFRONT_UI',
    type: 'checkout.block',
    icon: 'checkout',
    tags: ['checkout', 'savings', 'discount', 'plus'],
    spec: {
      type: 'checkout.block',
      name: 'Order Summary Savings Breakdown',
      category: 'STOREFRONT_UI',
      requires: ['CHECKOUT_UI_INFO_SHIP_PAY'],
      config: {
        target: 'purchase.checkout.cart-line-item.render-after',
        title: 'Savings',
        message: 'You are saving with applied discounts. Savings shown per item.',
      },
    } as RecipeSpec,
  },
  {
    id: 'CHK-043',
    name: 'Discount Field Education',
    description: 'Guide customers on how to apply discount codes at checkout.',
    category: 'STOREFRONT_UI',
    type: 'checkout.block',
    icon: 'checkout',
    tags: ['checkout', 'discount', 'education', 'plus'],
    spec: {
      type: 'checkout.block',
      name: 'Discount Field Education',
      category: 'STOREFRONT_UI',
      requires: ['CHECKOUT_UI_INFO_SHIP_PAY'],
      config: {
        target: 'purchase.checkout.reductions.render-before',
        title: 'Discount Info',
        message: 'Have a promo code? Enter it above. Only one discount code can be used per order.',
      },
    } as RecipeSpec,
  },
  {
    id: 'CHK-044',
    name: 'Shipping Option Detail Helper',
    description: 'Provide extra delivery details alongside each shipping option.',
    category: 'STOREFRONT_UI',
    type: 'checkout.block',
    icon: 'checkout',
    tags: ['checkout', 'shipping', 'details', 'plus'],
    spec: {
      type: 'checkout.block',
      name: 'Shipping Option Detail Helper',
      category: 'STOREFRONT_UI',
      requires: ['CHECKOUT_UI_INFO_SHIP_PAY'],
      config: {
        target: 'purchase.checkout.shipping-option-item.details.render',
        title: 'Shipping Details',
        message: 'Estimated delivery times are calculated from the date of shipment.',
      },
    } as RecipeSpec,
  },
  {
    id: 'CHK-045',
    name: 'Payment Method Helper',
    description: 'Display guidance on available payment methods before the list.',
    category: 'STOREFRONT_UI',
    type: 'checkout.block',
    icon: 'checkout',
    tags: ['checkout', 'payment', 'helper', 'plus'],
    spec: {
      type: 'checkout.block',
      name: 'Payment Method Helper',
      category: 'STOREFRONT_UI',
      requires: ['CHECKOUT_UI_INFO_SHIP_PAY'],
      config: {
        target: 'purchase.checkout.payment-method-list.render-before',
        title: 'Payment Options',
        message: 'Choose your preferred payment method. All transactions are secured with SSL encryption.',
      },
    } as RecipeSpec,
  },

  // ═══════════════════════════════════════════════════════════════════
  // Category 6: Thank You & Order Status (TYO-046 to TYO-054)
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'TYO-046',
    name: 'TY Announcement Next Steps',
    description: 'Show next-step instructions on the thank-you page announcement area.',
    category: 'STOREFRONT_UI',
    type: 'checkout.block',
    icon: 'checkout',
    tags: ['thank-you', 'announcement', 'next-steps'],
    spec: {
      type: 'checkout.block',
      name: 'TY Announcement Next Steps',
      category: 'STOREFRONT_UI',
      requires: ['CHECKOUT_UI_INFO_SHIP_PAY'],
      config: {
        target: 'purchase.thank-you.announcement.render',
        title: 'What Happens Next',
        message: 'Your order is confirmed. You will receive a shipping confirmation email shortly.',
      },
    } as RecipeSpec,
  },
  {
    id: 'TYO-047',
    name: 'TY Support CTA Footer',
    description: 'Add a support call-to-action in the thank-you page footer.',
    category: 'STOREFRONT_UI',
    type: 'checkout.block',
    icon: 'checkout',
    tags: ['thank-you', 'support', 'footer'],
    spec: {
      type: 'checkout.block',
      name: 'TY Support CTA Footer',
      category: 'STOREFRONT_UI',
      requires: ['CHECKOUT_UI_INFO_SHIP_PAY'],
      config: {
        target: 'purchase.thank-you.footer.render-after',
        title: 'Need Help?',
        message: 'Our support team is available 24/7. Contact us for any order questions.',
      },
    } as RecipeSpec,
  },
  {
    id: 'TYO-048',
    name: 'TY Reorder Recommendations',
    description: 'Display product recommendations on the thank-you page.',
    category: 'STOREFRONT_UI',
    type: 'checkout.block',
    icon: 'checkout',
    tags: ['thank-you', 'recommendations', 'upsell'],
    spec: {
      type: 'checkout.block',
      name: 'TY Reorder Recommendations',
      category: 'STOREFRONT_UI',
      requires: ['CHECKOUT_UI_INFO_SHIP_PAY'],
      config: {
        target: 'purchase.thank-you.block.render',
        title: 'Recommended For You',
        message: 'Customers who bought these items also loved these products.',
      },
    } as RecipeSpec,
  },
  {
    id: 'TYO-049',
    name: 'TY Line-Item Education',
    description: 'Show product care tips next to each item on the thank-you page.',
    category: 'STOREFRONT_UI',
    type: 'checkout.block',
    icon: 'checkout',
    tags: ['thank-you', 'product-care', 'education'],
    spec: {
      type: 'checkout.block',
      name: 'TY Line-Item Education',
      category: 'STOREFRONT_UI',
      requires: ['CHECKOUT_UI_INFO_SHIP_PAY'],
      config: {
        target: 'purchase.thank-you.cart-line-item.render-after',
        title: 'Product Care',
        message: 'Follow the included care instructions to keep your purchase in great condition.',
      },
    } as RecipeSpec,
  },
  {
    id: 'TYO-050',
    name: 'TY Post-Purchase Survey',
    description: 'Prompt customers for quick feedback on the thank-you page.',
    category: 'STOREFRONT_UI',
    type: 'checkout.block',
    icon: 'checkout',
    tags: ['thank-you', 'survey', 'feedback'],
    spec: {
      type: 'checkout.block',
      name: 'TY Post-Purchase Survey',
      category: 'STOREFRONT_UI',
      requires: ['CHECKOUT_UI_INFO_SHIP_PAY'],
      config: {
        target: 'purchase.thank-you.block.render',
        title: 'Quick Feedback',
        message: 'How was your shopping experience? Your feedback helps us improve.',
      },
    } as RecipeSpec,
  },
  {
    id: 'TYO-051',
    name: 'Order Status Announcement',
    description: 'Show an announcement banner on the order status page.',
    category: 'CUSTOMER_ACCOUNT',
    type: 'customerAccount.blocks',
    icon: 'customer',
    tags: ['order-status', 'announcement', 'customer-account'],
    spec: {
      type: 'customerAccount.blocks',
      name: 'Order Status Announcement',
      category: 'CUSTOMER_ACCOUNT',
      requires: ['CUSTOMER_ACCOUNT_UI'],
      config: {
        target: 'customer-account.order-status.announcement.render',
        title: 'Order Update',
        blocks: [
          { kind: 'BADGE', content: 'Processing', tone: 'info' },
          { kind: 'TEXT', content: 'Your order is being prepared and will ship within 1-2 business days.' },
          { kind: 'LINK', content: 'View shipping FAQ', url: 'https://example.com/shipping-faq' },
        ],
        b2bOnly: false,
      },
    } as RecipeSpec,
  },
  {
    id: 'TYO-052',
    name: 'Order Status Tracking Embed',
    description: 'Embed a tracking card on the order status page for live updates.',
    category: 'CUSTOMER_ACCOUNT',
    type: 'customerAccount.blocks',
    icon: 'customer',
    tags: ['order-status', 'tracking', 'customer-account'],
    spec: {
      type: 'customerAccount.blocks',
      name: 'Order Status Tracking Embed',
      category: 'CUSTOMER_ACCOUNT',
      requires: ['CUSTOMER_ACCOUNT_UI'],
      config: {
        target: 'customer-account.order-status.block.render',
        title: 'Track Your Order',
        blocks: [
          { kind: 'TEXT', content: 'Your package is on its way. Check tracking for live updates.' },
          { kind: 'LINK', content: 'Track shipment', url: 'https://example.com/tracking' },
        ],
        b2bOnly: false,
      },
    } as RecipeSpec,
  },
  {
    id: 'TYO-053',
    name: 'Order Status Returns Button',
    description: 'Add a return initiation block after order return details.',
    category: 'CUSTOMER_ACCOUNT',
    type: 'customerAccount.blocks',
    icon: 'customer',
    tags: ['order-status', 'returns', 'customer-account'],
    spec: {
      type: 'customerAccount.blocks',
      name: 'Order Status Returns Button',
      category: 'CUSTOMER_ACCOUNT',
      requires: ['CUSTOMER_ACCOUNT_UI'],
      config: {
        target: 'customer-account.order-status.return-details.render-after',
        title: 'Start a Return',
        blocks: [
          { kind: 'TEXT', content: 'Not satisfied? You can start a return within 30 days of delivery.' },
          { kind: 'LINK', content: 'Initiate return', url: 'https://example.com/returns' },
        ],
        b2bOnly: false,
      },
    } as RecipeSpec,
  },
  {
    id: 'TYO-054',
    name: 'Order Status Payment Helper',
    description: 'Display payment info and billing support after payment details.',
    category: 'CUSTOMER_ACCOUNT',
    type: 'customerAccount.blocks',
    icon: 'customer',
    tags: ['order-status', 'payment', 'customer-account'],
    spec: {
      type: 'customerAccount.blocks',
      name: 'Order Status Payment Helper',
      category: 'CUSTOMER_ACCOUNT',
      requires: ['CUSTOMER_ACCOUNT_UI'],
      config: {
        target: 'customer-account.order-status.payment-details.render-after',
        title: 'Payment Details',
        blocks: [
          { kind: 'TEXT', content: 'Your payment has been processed successfully.' },
          { kind: 'LINK', content: 'Contact billing support', url: 'https://example.com/billing-support' },
        ],
        b2bOnly: false,
      },
    } as RecipeSpec,
  },

  // ═══════════════════════════════════════════════════════════════════
  // Category 7: Customer Account Experience (ACC-055 to ACC-063)
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'ACC-055',
    name: 'Account Footer Loyalty Teaser',
    description: 'Show a loyalty points teaser in the customer account footer.',
    category: 'CUSTOMER_ACCOUNT',
    type: 'customerAccount.blocks',
    icon: 'customer',
    tags: ['customer-account', 'footer', 'loyalty'],
    spec: {
      type: 'customerAccount.blocks',
      name: 'Account Footer Loyalty Teaser',
      category: 'CUSTOMER_ACCOUNT',
      requires: ['CUSTOMER_ACCOUNT_UI'],
      config: {
        target: 'customer-account.footer.render-after',
        title: 'Your Loyalty Points',
        blocks: [
          { kind: 'BADGE', content: 'Rewards Member', tone: 'success' },
          { kind: 'TEXT', content: 'Earn points with every purchase and redeem for exclusive discounts.' },
          { kind: 'LINK', content: 'View rewards', url: 'https://example.com/rewards' },
        ],
        b2bOnly: false,
      },
    } as RecipeSpec,
  },
  {
    id: 'ACC-056',
    name: 'Orders Index Promo Banner',
    description: 'Display a promotional announcement on the orders list page.',
    category: 'CUSTOMER_ACCOUNT',
    type: 'customerAccount.blocks',
    icon: 'customer',
    tags: ['customer-account', 'orders', 'promo'],
    spec: {
      type: 'customerAccount.blocks',
      name: 'Orders Index Promo Banner',
      category: 'CUSTOMER_ACCOUNT',
      requires: ['CUSTOMER_ACCOUNT_UI'],
      config: {
        target: 'customer-account.order-index.announcement.render',
        title: 'Special Offers',
        blocks: [
          { kind: 'BADGE', content: 'Limited Time', tone: 'warning' },
          { kind: 'TEXT', content: 'Reorder your favorites and get 10% off your next purchase.' },
          { kind: 'LINK', content: 'Shop deals', url: 'https://example.com/deals' },
        ],
        b2bOnly: false,
      },
    } as RecipeSpec,
  },
  {
    id: 'ACC-057',
    name: 'Orders Index Quick Actions',
    description: 'Add quick action buttons on the orders index page.',
    category: 'CUSTOMER_ACCOUNT',
    type: 'customerAccount.blocks',
    icon: 'customer',
    tags: ['customer-account', 'orders', 'quick-actions'],
    spec: {
      type: 'customerAccount.blocks',
      name: 'Orders Index Quick Actions',
      category: 'CUSTOMER_ACCOUNT',
      requires: ['CUSTOMER_ACCOUNT_UI'],
      config: {
        target: 'customer-account.order-index.block.render',
        title: 'Quick Actions',
        blocks: [
          { kind: 'LINK', content: 'Track all orders', url: 'https://example.com/tracking' },
          { kind: 'LINK', content: 'Start a return', url: 'https://example.com/returns' },
          { kind: 'LINK', content: 'Contact support', url: 'https://example.com/support' },
        ],
        b2bOnly: false,
      },
    } as RecipeSpec,
  },
  {
    id: 'ACC-058',
    name: 'Order Action Download Invoice',
    description: 'Add a download invoice option to the order action menu.',
    category: 'CUSTOMER_ACCOUNT',
    type: 'customerAccount.blocks',
    icon: 'customer',
    tags: ['customer-account', 'order', 'invoice'],
    spec: {
      type: 'customerAccount.blocks',
      name: 'Order Action Download Invoice',
      category: 'CUSTOMER_ACCOUNT',
      requires: ['CUSTOMER_ACCOUNT_UI'],
      config: {
        target: 'customer-account.order.action.menu-item.render',
        title: 'Download Invoice',
        blocks: [
          { kind: 'LINK', content: 'Download PDF invoice', url: 'https://example.com/invoice' },
        ],
        b2bOnly: false,
      },
    } as RecipeSpec,
  },
  {
    id: 'ACC-059',
    name: 'Account Loyalty Dashboard',
    description: 'A dedicated loyalty dashboard page within the customer account.',
    category: 'CUSTOMER_ACCOUNT',
    type: 'customerAccount.blocks',
    icon: 'customer',
    tags: ['customer-account', 'loyalty', 'dashboard'],
    spec: {
      type: 'customerAccount.blocks',
      name: 'Account Loyalty Dashboard',
      category: 'CUSTOMER_ACCOUNT',
      requires: ['CUSTOMER_ACCOUNT_UI'],
      config: {
        target: 'customer-account.page.render',
        title: 'Loyalty Dashboard',
        blocks: [
          { kind: 'BADGE', content: 'Gold Tier', tone: 'success' },
          { kind: 'TEXT', content: 'You have 3,200 points. Earn 800 more to reach Platinum status.' },
          { kind: 'LINK', content: 'Redeem points', url: 'https://example.com/rewards/redeem' },
        ],
        b2bOnly: false,
      },
    } as RecipeSpec,
  },
  {
    id: 'ACC-060',
    name: 'Order Support Center',
    description: 'Provide a support center page accessible from order details.',
    category: 'CUSTOMER_ACCOUNT',
    type: 'customerAccount.blocks',
    icon: 'customer',
    tags: ['customer-account', 'order', 'support'],
    spec: {
      type: 'customerAccount.blocks',
      name: 'Order Support Center',
      category: 'CUSTOMER_ACCOUNT',
      requires: ['CUSTOMER_ACCOUNT_UI'],
      config: {
        target: 'customer-account.order.page.render',
        title: 'Support Center',
        blocks: [
          { kind: 'TEXT', content: 'Need help with this order? Our team is here to assist you.' },
          { kind: 'LINK', content: 'Open support ticket', url: 'https://example.com/support/ticket' },
          { kind: 'LINK', content: 'View FAQ', url: 'https://example.com/faq' },
        ],
        b2bOnly: false,
      },
    } as RecipeSpec,
  },
  {
    id: 'ACC-061',
    name: 'Profile Announcement',
    description: 'Show an announcement banner on the customer profile page.',
    category: 'CUSTOMER_ACCOUNT',
    type: 'customerAccount.blocks',
    icon: 'customer',
    tags: ['customer-account', 'profile', 'announcement'],
    spec: {
      type: 'customerAccount.blocks',
      name: 'Profile Announcement',
      category: 'CUSTOMER_ACCOUNT',
      requires: ['CUSTOMER_ACCOUNT_UI'],
      config: {
        target: 'customer-account.profile.announcement.render',
        title: 'Account Notice',
        blocks: [
          { kind: 'BADGE', content: 'Action Required', tone: 'warning' },
          { kind: 'TEXT', content: 'Please verify your email address to receive order updates.' },
        ],
        b2bOnly: false,
      },
    } as RecipeSpec,
  },
  {
    id: 'ACC-062',
    name: 'Profile Addresses Helper',
    description: 'Display tips for managing saved addresses on the profile page.',
    category: 'CUSTOMER_ACCOUNT',
    type: 'customerAccount.blocks',
    icon: 'customer',
    tags: ['customer-account', 'profile', 'addresses'],
    spec: {
      type: 'customerAccount.blocks',
      name: 'Profile Addresses Helper',
      category: 'CUSTOMER_ACCOUNT',
      requires: ['CUSTOMER_ACCOUNT_UI'],
      config: {
        target: 'customer-account.profile.addresses.render-after',
        title: 'Address Tips',
        blocks: [
          { kind: 'TEXT', content: 'Keep your addresses up to date for faster checkout and accurate delivery.' },
          { kind: 'LINK', content: 'Learn about address formatting', url: 'https://example.com/address-help' },
        ],
        b2bOnly: false,
      },
    } as RecipeSpec,
  },
  {
    id: 'ACC-063',
    name: 'B2B Company Details',
    description: 'Display company information for B2B customers on their profile.',
    category: 'CUSTOMER_ACCOUNT',
    type: 'customerAccount.blocks',
    icon: 'customer',
    tags: ['customer-account', 'profile', 'b2b', 'company'],
    spec: {
      type: 'customerAccount.blocks',
      name: 'B2B Company Details',
      category: 'CUSTOMER_ACCOUNT',
      requires: ['CUSTOMER_ACCOUNT_UI'],
      config: {
        target: 'customer-account.profile.company-details.render-after',
        title: 'Company Info',
        blocks: [
          { kind: 'BADGE', content: 'B2B Account', tone: 'info' },
          { kind: 'TEXT', content: 'Manage your company details, payment terms, and team permissions.' },
          { kind: 'LINK', content: 'Update company info', url: 'https://example.com/b2b/company' },
        ],
        b2bOnly: true,
      },
    } as RecipeSpec,
  },

  // ═══════════════════════════════════════════════════════════════════
  // Category 8: Shipping & Delivery (SHP-064 to SHP-072)
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'SHP-064',
    name: 'Hide/Sort Delivery Options',
    description: 'Hide Express shipping for orders below $50 to reduce cart abandonment.',
    category: 'FUNCTION',
    type: 'functions.deliveryCustomization',
    icon: 'shipping',
    tags: ['shipping', 'delivery', 'rules'],
    spec: {
      type: 'functions.deliveryCustomization',
      name: 'Hide Express Below $50',
      category: 'FUNCTION',
      requires: ['SHIPPING_FUNCTION'],
      config: {
        rules: [
          {
            when: { minSubtotal: 0 },
            actions: { hideMethodsContaining: ['Express'], reorderPriority: 50 },
          },
        ],
      },
    } as RecipeSpec,
  },
  {
    id: 'SHP-065',
    name: 'Delivery Option Labels',
    description: 'Rename Standard shipping to show estimated delivery days for clarity.',
    category: 'FUNCTION',
    type: 'functions.deliveryCustomization',
    icon: 'shipping',
    tags: ['shipping', 'rename', 'labels'],
    spec: {
      type: 'functions.deliveryCustomization',
      name: 'Delivery Option Labels',
      category: 'FUNCTION',
      requires: ['SHIPPING_FUNCTION'],
      config: {
        rules: [
          {
            when: {},
            actions: { renameMethod: { contains: 'Standard', to: 'Economy (5-7 days)' } },
          },
        ],
      },
    } as RecipeSpec,
  },
  {
    id: 'SHP-066',
    name: 'Checkout Shipping Option Helper',
    description: 'Guide customers through shipping options before they make a selection.',
    category: 'STOREFRONT_UI',
    type: 'checkout.block',
    icon: 'checkout',
    tags: ['checkout', 'shipping', 'guide'],
    spec: {
      type: 'checkout.block',
      name: 'Checkout Shipping Option Helper',
      category: 'STOREFRONT_UI',
      requires: ['CHECKOUT_UI_INFO_SHIP_PAY'],
      config: {
        target: 'purchase.checkout.shipping-option-list.render-before',
        title: 'Shipping Guide',
        message: 'Choose the shipping speed that works best for you. Free shipping on orders over $75.',
      },
    } as RecipeSpec,
  },
  {
    id: 'SHP-067',
    name: 'Checkout Address Guidance',
    description: 'Provide address entry tips before the delivery address form.',
    category: 'STOREFRONT_UI',
    type: 'checkout.block',
    icon: 'checkout',
    tags: ['checkout', 'address', 'guidance'],
    spec: {
      type: 'checkout.block',
      name: 'Checkout Address Guidance',
      category: 'STOREFRONT_UI',
      requires: ['CHECKOUT_UI_INFO_SHIP_PAY'],
      config: {
        target: 'purchase.checkout.delivery-address.render-before',
        title: 'Address Tips',
        message: 'Please include apartment or suite numbers. PO Boxes may delay delivery.',
      },
    } as RecipeSpec,
  },
  {
    id: 'SHP-068',
    name: 'Local Pickup Instructions',
    description: 'Display pickup instructions before the location list at checkout.',
    category: 'STOREFRONT_UI',
    type: 'checkout.block',
    icon: 'checkout',
    tags: ['checkout', 'pickup', 'local'],
    spec: {
      type: 'checkout.block',
      name: 'Local Pickup Instructions',
      category: 'STOREFRONT_UI',
      requires: ['CHECKOUT_UI_INFO_SHIP_PAY'],
      config: {
        target: 'purchase.checkout.pickup-location-list.render-before',
        title: 'Pickup Instructions',
        message: 'Orders are ready for pickup within 2 hours. Bring your order confirmation email.',
      },
    } as RecipeSpec,
  },
  {
    id: 'SHP-069',
    name: 'Pickup Point Education',
    description: 'Help customers choose a convenient pickup point near them.',
    category: 'STOREFRONT_UI',
    type: 'checkout.block',
    icon: 'checkout',
    tags: ['checkout', 'pickup-point', 'education'],
    spec: {
      type: 'checkout.block',
      name: 'Pickup Point Education',
      category: 'STOREFRONT_UI',
      requires: ['CHECKOUT_UI_INFO_SHIP_PAY'],
      config: {
        target: 'purchase.checkout.pickup-point-list.render-before',
        title: 'Choose Pickup Point',
        message: 'Select a pickup point near you. Your package will be held for 7 days.',
      },
    } as RecipeSpec,
  },
  {
    id: 'SHP-070',
    name: 'Cart Shipping Estimator',
    description: 'Show a shipping estimate banner on the cart page to set expectations.',
    category: 'STOREFRONT_UI',
    type: 'theme.banner',
    icon: 'banner',
    tags: ['cart', 'shipping', 'estimator'],
    spec: {
      type: 'theme.banner',
      name: 'Cart Shipping Estimator',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        heading: 'Shipping Estimate',
        subheading: 'Most orders ship within 1-3 business days. Free shipping over $75.',
        ctaText: 'View shipping policy',
        ctaUrl: 'https://example.com/shipping-policy',
        enableAnimation: false,
      },
      placement: { enabled_on: { templates: ['cart'] as any } },
    } as RecipeSpec,
  },
  {
    id: 'SHP-071',
    name: 'Order Status Delivery Card',
    description: 'Show delivery details after fulfillment info on the order status page.',
    category: 'CUSTOMER_ACCOUNT',
    type: 'customerAccount.blocks',
    icon: 'customer',
    tags: ['order-status', 'delivery', 'customer-account'],
    spec: {
      type: 'customerAccount.blocks',
      name: 'Order Status Delivery Card',
      category: 'CUSTOMER_ACCOUNT',
      requires: ['CUSTOMER_ACCOUNT_UI'],
      config: {
        target: 'customer-account.order-status.fulfillment-details.render-after',
        title: 'Delivery Info',
        blocks: [
          { kind: 'TEXT', content: 'Your order has been shipped and is on its way to you.' },
          { kind: 'LINK', content: 'Track delivery', url: 'https://example.com/tracking' },
          { kind: 'BADGE', content: 'In Transit', tone: 'info' },
        ],
        b2bOnly: false,
      },
    } as RecipeSpec,
  },
  {
    id: 'SHP-072',
    name: 'Admin Delivery Ops Card',
    description: 'Add a delivery operations card to the admin order details page.',
    category: 'ADMIN_UI',
    type: 'admin.block',
    icon: 'admin',
    tags: ['admin', 'delivery', 'operations'],
    spec: {
      type: 'admin.block',
      name: 'Admin Delivery Ops Card',
      category: 'ADMIN_UI',
      requires: [],
      config: {
        target: 'admin.order-details.block.render',
        label: 'Delivery Operations',
      },
    } as RecipeSpec,
  },
];
