import type { RecipeSpec, ModuleCategory } from './recipe.js';

export type TemplateEntry = {
  id: string;
  name: string;
  description: string;
  category: ModuleCategory;
  type: string;
  icon?: string;
  tags?: string[];
  spec: RecipeSpec;
};

export const TEMPLATE_CATEGORIES = [
  'STOREFRONT_UI', 'FUNCTION', 'FLOW', 'INTEGRATION', 'CUSTOMER_ACCOUNT', 'ADMIN_UI',
] as const;

export const MODULE_TEMPLATES: TemplateEntry[] = [
  {
    id: 'tpl-banner-promo',
    name: 'Promotional Banner',
    description: 'Eye-catching banner with heading, subheading, and CTA button.',
    category: 'STOREFRONT_UI',
    type: 'theme.banner',
    icon: 'banner',
    tags: ['banner', 'sale', 'promotion'],
    spec: {
      type: 'theme.banner',
      name: 'Promotional Banner',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        heading: 'Summer Sale - Up to 50% Off',
        subheading: 'Limited time only. Shop our best deals now.',
        ctaText: 'Shop Now',
        ctaUrl: 'https://example.com/collections/sale',
        enableAnimation: false,
      },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium' },
        typography: { size: 'LG', weight: 'bold', lineHeight: 'normal', align: 'left' },
        colors: { text: '#ffffff', background: '#1a1a2e', buttonBg: '#e94560', buttonText: '#ffffff' },
        shape: { radius: 'md', borderWidth: 'none', shadow: 'sm' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
      },
    } as RecipeSpec,
  },
  {
    id: 'tpl-popup-exit',
    name: 'Exit Intent Popup',
    description: 'Popup that appears when the visitor is about to leave the page. Includes delay, frequency, and page targeting.',
    category: 'STOREFRONT_UI',
    type: 'theme.popup',
    icon: 'popup',
    tags: ['popup', 'exit-intent', 'conversion'],
    spec: {
      type: 'theme.popup',
      name: 'Exit Intent Popup',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        title: 'Wait! Before you go...',
        body: 'Sign up for 10% off your first order.',
        trigger: 'ON_EXIT_INTENT',
        delaySeconds: 0,
        frequency: 'ONCE_PER_WEEK',
        maxShowsPerDay: 1,
        showOnPages: 'ALL',
        customPageUrls: [],
        showCloseButton: true,
        autoCloseSeconds: 0,
        countdownEnabled: false,
        countdownSeconds: 0,
        countdownLabel: '',
        ctaText: 'Get My Discount',
        ctaUrl: 'https://example.com/subscribe',
      },
      style: {
        layout: { mode: 'overlay', anchor: 'center', offsetX: 0, offsetY: 0, width: 'narrow', zIndex: 'modal' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium' },
        typography: { size: 'MD', weight: 'normal', lineHeight: 'normal', align: 'center' },
        colors: { text: '#1a1a2e', background: '#ffffff', overlayBackdropOpacity: 0.5 },
        shape: { radius: 'lg', borderWidth: 'none', shadow: 'lg' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
      },
    } as RecipeSpec,
  },
  {
    id: 'tpl-popup-welcome',
    name: 'Welcome Popup',
    description: 'Greet first-time visitors with a special offer. Shows after 3 seconds, once per week.',
    category: 'STOREFRONT_UI',
    type: 'theme.popup',
    icon: 'popup',
    tags: ['popup', 'welcome', 'first-visit'],
    spec: {
      type: 'theme.popup',
      name: 'Welcome Popup',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        title: 'Welcome to our store!',
        body: 'Enjoy free shipping on your first order over $50.',
        trigger: 'TIMED',
        delaySeconds: 3,
        frequency: 'ONCE_PER_WEEK',
        maxShowsPerDay: 1,
        showOnPages: 'HOMEPAGE',
        customPageUrls: [],
        showCloseButton: true,
        autoCloseSeconds: 0,
        countdownEnabled: false,
        countdownSeconds: 0,
        countdownLabel: '',
        ctaText: 'Start Shopping',
        ctaUrl: 'https://example.com/collections/all',
      },
      style: {
        layout: { mode: 'overlay', anchor: 'center', offsetX: 0, offsetY: 0, width: 'narrow', zIndex: 'modal' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium' },
        typography: { size: 'MD', weight: 'normal', lineHeight: 'normal', align: 'center' },
        colors: { text: '#111111', background: '#ffffff', buttonBg: '#2c6ecb', buttonText: '#ffffff', overlayBackdropOpacity: 0.45 },
        shape: { radius: 'lg', borderWidth: 'none', shadow: 'lg' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
      },
    } as RecipeSpec,
  },
  {
    id: 'tpl-notification-bar',
    name: 'Announcement Bar',
    description: 'Top-of-page notification bar for announcements, sales, or shipping info.',
    category: 'STOREFRONT_UI',
    type: 'theme.notificationBar',
    icon: 'notification',
    tags: ['notification', 'announcement', 'shipping'],
    spec: {
      type: 'theme.notificationBar',
      name: 'Announcement Bar',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        message: 'Free shipping on orders over $75 - Shop now!',
        linkText: 'Learn more',
        linkUrl: 'https://example.com/shipping-policy',
        dismissible: true,
      },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'full', zIndex: 'sticky' },
        spacing: { padding: 'tight', margin: 'none', gap: 'medium' },
        typography: { size: 'SM', weight: 'medium', lineHeight: 'normal', align: 'center' },
        colors: { text: '#ffffff', background: '#0f3460' },
        shape: { radius: 'none', borderWidth: 'none', shadow: 'none' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
      },
    } as RecipeSpec,
  },
  {
    id: 'tpl-discount-vip',
    name: 'VIP Customer Discount',
    description: 'Automatic percentage discount for VIP-tagged customers.',
    category: 'FUNCTION',
    type: 'functions.discountRules',
    icon: 'discount',
    tags: ['discount', 'vip', 'loyalty'],
    spec: {
      type: 'functions.discountRules',
      name: 'VIP Customer Discount',
      category: 'FUNCTION',
      requires: ['DISCOUNT_FUNCTION'],
      config: {
        rules: [
          {
            when: { customerTags: ['VIP'] },
            apply: { percentageOff: 15 },
          },
        ],
        combineWithOtherDiscounts: true,
      },
    } as RecipeSpec,
  },
  {
    id: 'tpl-discount-bulk',
    name: 'Bulk Order Discount',
    description: 'Discount when the cart subtotal exceeds a threshold.',
    category: 'FUNCTION',
    type: 'functions.discountRules',
    icon: 'discount',
    tags: ['discount', 'bulk', 'cart'],
    spec: {
      type: 'functions.discountRules',
      name: 'Bulk Order Discount',
      category: 'FUNCTION',
      requires: ['DISCOUNT_FUNCTION'],
      config: {
        rules: [
          {
            when: { minSubtotal: 200 },
            apply: { percentageOff: 10 },
          },
        ],
        combineWithOtherDiscounts: true,
      },
    } as RecipeSpec,
  },
  {
    id: 'tpl-flow-order-tag',
    name: 'Tag Customer on Order',
    description: 'When a new order is created, tag the customer automatically.',
    category: 'FLOW',
    type: 'flow.automation',
    icon: 'flow',
    tags: ['flow', 'order', 'tagging'],
    spec: {
      type: 'flow.automation',
      name: 'Tag Customer on Order',
      category: 'FLOW',
      requires: [],
      config: {
        trigger: 'SHOPIFY_WEBHOOK_ORDER_CREATED',
        steps: [
          { kind: 'TAG_CUSTOMER', tag: 'purchased' },
        ],
      },
    } as RecipeSpec,
  },
  {
    id: 'tpl-flow-order-note',
    name: 'Add Order Note',
    description: 'Automatically add a processing note when a new order comes in.',
    category: 'FLOW',
    type: 'flow.automation',
    icon: 'flow',
    tags: ['flow', 'order', 'note'],
    spec: {
      type: 'flow.automation',
      name: 'Add Order Note',
      category: 'FLOW',
      requires: [],
      config: {
        trigger: 'SHOPIFY_WEBHOOK_ORDER_CREATED',
        steps: [
          { kind: 'ADD_ORDER_NOTE', note: 'Auto-processed by SuperApp flow' },
        ],
      },
    } as RecipeSpec,
  },
  {
    id: 'tpl-customer-profile',
    name: 'Customer Account Profile Block',
    description: 'Add custom info blocks to the customer account profile page.',
    category: 'CUSTOMER_ACCOUNT',
    type: 'customerAccount.blocks',
    icon: 'customer',
    tags: ['customer-account', 'profile', 'loyalty'],
    spec: {
      type: 'customerAccount.blocks',
      name: 'Customer Account Profile Block',
      category: 'CUSTOMER_ACCOUNT',
      requires: ['CUSTOMER_ACCOUNT_UI'],
      config: {
        target: 'customer-account.profile.block.render',
        title: 'Your Loyalty Status',
        blocks: [
          { kind: 'BADGE', content: 'Gold Member', tone: 'success' },
          { kind: 'TEXT', content: 'You have earned 2,500 loyalty points this year.' },
          { kind: 'LINK', content: 'View rewards catalog', url: 'https://example.com/rewards' },
        ],
        b2bOnly: false,
      },
    } as RecipeSpec,
  },
  {
    id: 'tpl-proxy-widget',
    name: 'App Proxy Widget',
    description: 'Custom page rendered via Shopify App Proxy with HTML output.',
    category: 'STOREFRONT_UI',
    type: 'proxy.widget',
    icon: 'widget',
    tags: ['proxy', 'widget', 'custom-page'],
    spec: {
      type: 'proxy.widget',
      name: 'Custom Page Widget',
      category: 'STOREFRONT_UI',
      requires: ['APP_PROXY'],
      config: {
        widgetId: 'custom-page',
        mode: 'HTML',
        title: 'Store Info',
        message: 'Welcome to our custom store page. Check out our latest collections.',
      },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium' },
        typography: { size: 'MD', weight: 'normal', lineHeight: 'normal', align: 'left' },
        colors: { text: '#1e293b', background: '#ffffff' },
        shape: { radius: 'md', borderWidth: 'thin', shadow: 'sm' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
      },
    } as RecipeSpec,
  },
  {
    id: 'tpl-checkout-upsell',
    name: 'Checkout Upsell',
    description: 'Offer a discounted product at checkout to increase AOV.',
    category: 'STOREFRONT_UI',
    type: 'checkout.upsell',
    icon: 'checkout',
    tags: ['checkout', 'upsell', 'aov'],
    spec: {
      type: 'checkout.upsell',
      name: 'Checkout Upsell Offer',
      category: 'STOREFRONT_UI',
      requires: ['CHECKOUT_UI_INFO_SHIP_PAY'],
      config: {
        offerTitle: 'Add this for 20% off!',
        productVariantGid: 'gid://shopify/ProductVariant/0000000000',
        discountPercent: 20,
      },
    } as RecipeSpec,
  },
  {
    id: 'tpl-delivery-hide',
    name: 'Hide Shipping Method',
    description: 'Hide specific shipping methods based on country or cart total.',
    category: 'FUNCTION',
    type: 'functions.deliveryCustomization',
    icon: 'shipping',
    tags: ['delivery', 'shipping', 'customization'],
    spec: {
      type: 'functions.deliveryCustomization',
      name: 'Hide Express for Low Orders',
      category: 'FUNCTION',
      requires: ['SHIPPING_FUNCTION'],
      config: {
        rules: [
          {
            when: { minSubtotal: 0 },
            actions: { hideMethodsContaining: ['Express'] },
          },
        ],
      },
    } as RecipeSpec,
  },

  // --- New templates ---

  {
    id: 'tpl-free-shipping-bar',
    name: 'Free Shipping Bar',
    description: 'Notification bar showing how much more to spend for free shipping.',
    category: 'STOREFRONT_UI',
    type: 'theme.notificationBar',
    icon: 'notification',
    tags: ['shipping', 'notification', 'threshold'],
    spec: {
      type: 'theme.notificationBar',
      name: 'Free Shipping Bar',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        message: 'Spend $25 more for FREE shipping!',
        linkText: 'Shop now',
        linkUrl: 'https://example.com/collections/all',
        dismissible: false,
      },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'full', zIndex: 'sticky' },
        spacing: { padding: 'tight', margin: 'none', gap: 'medium' },
        typography: { size: 'SM', weight: 'bold', lineHeight: 'normal', align: 'center' },
        colors: { text: '#ffffff', background: '#16a34a' },
        shape: { radius: 'none', borderWidth: 'none', shadow: 'none' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
      },
    } as RecipeSpec,
  },
  {
    id: 'tpl-countdown-timer',
    name: 'Countdown Timer Banner',
    description: 'Urgency banner with countdown text for flash sales.',
    category: 'STOREFRONT_UI',
    type: 'theme.banner',
    icon: 'banner',
    tags: ['banner', 'urgency', 'countdown'],
    spec: {
      type: 'theme.banner',
      name: 'Countdown Timer Banner',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        heading: 'Flash Sale Ends Tonight!',
        subheading: 'Hurry - deals expire at midnight.',
        ctaText: 'Shop the Sale',
        ctaUrl: 'https://example.com/collections/flash-sale',
        enableAnimation: true,
      },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium' },
        typography: { size: 'XL', weight: 'bold', lineHeight: 'tight', align: 'center' },
        colors: { text: '#ffffff', background: '#dc2626', buttonBg: '#ffffff', buttonText: '#dc2626' },
        shape: { radius: 'md', borderWidth: 'none', shadow: 'md' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
      },
    } as RecipeSpec,
  },
  {
    id: 'tpl-newsletter-popup',
    name: 'Newsletter Signup Popup',
    description: 'Popup for capturing visitor emails with a newsletter offer. Triggers on 50% scroll, once per week.',
    category: 'STOREFRONT_UI',
    type: 'theme.popup',
    icon: 'popup',
    tags: ['popup', 'newsletter', 'email'],
    spec: {
      type: 'theme.popup',
      name: 'Newsletter Signup Popup',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        title: 'Join Our Newsletter',
        body: 'Get exclusive deals and 15% off your next order.',
        trigger: 'ON_SCROLL_50',
        delaySeconds: 0,
        frequency: 'ONCE_PER_WEEK',
        maxShowsPerDay: 1,
        showOnPages: 'ALL',
        customPageUrls: [],
        showCloseButton: true,
        autoCloseSeconds: 0,
        countdownEnabled: false,
        countdownSeconds: 0,
        countdownLabel: '',
        ctaText: 'Subscribe',
        ctaUrl: 'https://example.com/newsletter',
        secondaryCtaText: 'No thanks',
      },
      style: {
        layout: { mode: 'overlay', anchor: 'center', offsetX: 0, offsetY: 0, width: 'narrow', zIndex: 'modal' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium' },
        typography: { size: 'MD', weight: 'normal', lineHeight: 'normal', align: 'center' },
        colors: { text: '#1a1a2e', background: '#ffffff', buttonBg: '#16a34a', buttonText: '#ffffff', overlayBackdropOpacity: 0.4 },
        shape: { radius: 'lg', borderWidth: 'none', shadow: 'lg' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
      },
    } as RecipeSpec,
  },
  {
    id: 'tpl-social-proof-popup',
    name: 'Social Proof Popup',
    description: 'Small popup showing recent purchase activity to build trust. Auto-closes after 5 seconds.',
    category: 'STOREFRONT_UI',
    type: 'theme.popup',
    icon: 'popup',
    tags: ['popup', 'social-proof', 'trust'],
    spec: {
      type: 'theme.popup',
      name: 'Social Proof Popup',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        title: 'Popular Right Now',
        body: '12 people bought this item in the last hour.',
        trigger: 'TIMED',
        delaySeconds: 5,
        frequency: 'ONCE_PER_SESSION',
        maxShowsPerDay: 3,
        showOnPages: 'PRODUCT',
        customPageUrls: [],
        showCloseButton: true,
        autoCloseSeconds: 5,
        countdownEnabled: false,
        countdownSeconds: 0,
        countdownLabel: '',
        ctaText: 'View Product',
        ctaUrl: 'https://example.com/products/best-seller',
      },
      style: {
        layout: { mode: 'overlay', anchor: 'bottom', offsetX: 16, offsetY: 16, width: 'narrow', zIndex: 'overlay' },
        spacing: { padding: 'medium', margin: 'none', gap: 'tight' },
        typography: { size: 'SM', weight: 'normal', lineHeight: 'normal', align: 'left' },
        colors: { text: '#1a1a2e', background: '#ffffff', overlayBackdropOpacity: 0 },
        shape: { radius: 'md', borderWidth: 'thin', shadow: 'md' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
      },
    } as RecipeSpec,
  },
  {
    id: 'tpl-back-in-stock',
    name: 'Back in Stock Alert',
    description: 'Notification bar announcing restocked items.',
    category: 'STOREFRONT_UI',
    type: 'theme.notificationBar',
    icon: 'notification',
    tags: ['notification', 'restock', 'inventory'],
    spec: {
      type: 'theme.notificationBar',
      name: 'Back in Stock Alert',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        message: 'Back in stock! Our best-selling item is available again.',
        linkText: 'Shop now',
        linkUrl: 'https://example.com/products/restocked-item',
        dismissible: true,
      },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'full', zIndex: 'sticky' },
        spacing: { padding: 'tight', margin: 'none', gap: 'medium' },
        typography: { size: 'SM', weight: 'medium', lineHeight: 'normal', align: 'center' },
        colors: { text: '#ffffff', background: '#7c3aed' },
        shape: { radius: 'none', borderWidth: 'none', shadow: 'none' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
      },
    } as RecipeSpec,
  },
  {
    id: 'tpl-trust-badge-banner',
    name: 'Trust Badge Banner',
    description: 'Banner with security and trust messaging to reassure shoppers.',
    category: 'STOREFRONT_UI',
    type: 'theme.banner',
    icon: 'banner',
    tags: ['banner', 'trust', 'security'],
    spec: {
      type: 'theme.banner',
      name: 'Trust Badge Banner',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        heading: 'Shop With Confidence',
        subheading: 'Secure checkout - Free returns - 24/7 support',
        enableAnimation: false,
      },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'medium', margin: 'none', gap: 'medium' },
        typography: { size: 'MD', weight: 'medium', lineHeight: 'normal', align: 'center' },
        colors: { text: '#1e293b', background: '#f0fdf4' },
        shape: { radius: 'md', borderWidth: 'thin', shadow: 'none' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
      },
    } as RecipeSpec,
  },
  {
    id: 'tpl-cart-quantity-discount',
    name: 'Cart Quantity Discount',
    description: 'Percentage discount when cart item quantity exceeds a threshold.',
    category: 'FUNCTION',
    type: 'functions.discountRules',
    icon: 'discount',
    tags: ['discount', 'cart', 'quantity'],
    spec: {
      type: 'functions.discountRules',
      name: 'Cart Quantity Discount',
      category: 'FUNCTION',
      requires: ['DISCOUNT_FUNCTION'],
      config: {
        rules: [
          {
            when: { minSubtotal: 150 },
            apply: { percentageOff: 5 },
          },
        ],
        combineWithOtherDiscounts: true,
      },
    } as RecipeSpec,
  },
  {
    id: 'tpl-free-gift',
    name: 'Free Gift with Purchase',
    description: 'Automatically apply a 100% discount on a gift item above a spend threshold.',
    category: 'FUNCTION',
    type: 'functions.discountRules',
    icon: 'discount',
    tags: ['discount', 'gift', 'promotion'],
    spec: {
      type: 'functions.discountRules',
      name: 'Free Gift with Purchase',
      category: 'FUNCTION',
      requires: ['DISCOUNT_FUNCTION'],
      config: {
        rules: [
          {
            when: { minSubtotal: 100 },
            apply: { percentageOff: 100 },
          },
        ],
        combineWithOtherDiscounts: false,
      },
    } as RecipeSpec,
  },
  {
    id: 'tpl-payment-method-gate',
    name: 'Payment Method Gate',
    description: 'Hide specific payment methods below a cart subtotal threshold.',
    category: 'FUNCTION',
    type: 'functions.paymentCustomization',
    icon: 'payment',
    tags: ['payment', 'customization', 'checkout'],
    spec: {
      type: 'functions.paymentCustomization',
      name: 'Payment Method Gate',
      category: 'FUNCTION',
      requires: ['PAYMENT_CUSTOMIZATION_FUNCTION'],
      config: {
        rules: [
          {
            when: { minSubtotal: 0 },
            actions: { hideMethodsContaining: ['Cash on Delivery'] },
          },
        ],
      },
    } as RecipeSpec,
  },
  {
    id: 'tpl-cart-validation',
    name: 'Cart Minimum Quantity Validation',
    description: 'Block checkout when a SKU quantity exceeds the allowed maximum.',
    category: 'FUNCTION',
    type: 'functions.cartAndCheckoutValidation',
    icon: 'validation',
    tags: ['validation', 'cart', 'minimum'],
    spec: {
      type: 'functions.cartAndCheckoutValidation',
      name: 'Cart Minimum Quantity Validation',
      category: 'FUNCTION',
      requires: ['VALIDATION_FUNCTION'],
      config: {
        rules: [
          {
            when: { maxQuantityPerSku: 10 },
            errorMessage: 'You can order a maximum of 10 units per item.',
          },
        ],
      },
    } as RecipeSpec,
  },
  {
    id: 'tpl-erp-order-sync',
    name: 'ERP Order Sync Flow',
    description: 'Send new order data to an external ERP system via HTTP.',
    category: 'FLOW',
    type: 'flow.automation',
    icon: 'flow',
    tags: ['flow', 'erp', 'sync'],
    spec: {
      type: 'flow.automation',
      name: 'ERP Order Sync Flow',
      category: 'FLOW',
      requires: [],
      config: {
        trigger: 'SHOPIFY_WEBHOOK_ORDER_CREATED',
        steps: [
          {
            kind: 'HTTP_REQUEST',
            connectorId: 'erp-connector',
            path: '/api/orders/sync',
            method: 'POST',
            bodyMapping: { orderId: '{{order.id}}', total: '{{order.total_price}}' },
          },
        ],
      },
    } as RecipeSpec,
  },
  {
    id: 'tpl-low-stock-alert',
    name: 'Low Stock Alert Flow',
    description: 'Write an inventory alert to the store when stock is updated.',
    category: 'FLOW',
    type: 'flow.automation',
    icon: 'flow',
    tags: ['flow', 'inventory', 'alert'],
    spec: {
      type: 'flow.automation',
      name: 'Low Stock Alert Flow',
      category: 'FLOW',
      requires: [],
      config: {
        trigger: 'SHOPIFY_WEBHOOK_PRODUCT_UPDATED',
        steps: [
          {
            kind: 'WRITE_TO_STORE',
            storeKey: 'low-stock-alerts',
            titleExpr: 'Low stock: {{product.title}}',
            payloadMapping: { productId: '{{product.id}}', variant: '{{product.variant_id}}' },
          },
        ],
      },
    } as RecipeSpec,
  },
  {
    id: 'tpl-webhook-relay',
    name: 'Webhook Relay Flow',
    description: 'Forward product update webhooks to an external endpoint.',
    category: 'FLOW',
    type: 'flow.automation',
    icon: 'flow',
    tags: ['flow', 'webhook', 'product'],
    spec: {
      type: 'flow.automation',
      name: 'Webhook Relay Flow',
      category: 'FLOW',
      requires: [],
      config: {
        trigger: 'SHOPIFY_WEBHOOK_PRODUCT_UPDATED',
        steps: [
          {
            kind: 'HTTP_REQUEST',
            connectorId: 'webhook-relay',
            path: '/api/webhooks/product-updated',
            method: 'POST',
            bodyMapping: { productId: '{{product.id}}', title: '{{product.title}}' },
          },
        ],
      },
    } as RecipeSpec,
  },
  {
    id: 'tpl-order-status-block',
    name: 'Order Status Page Block',
    description: 'Custom block on the customer account order status page.',
    category: 'CUSTOMER_ACCOUNT',
    type: 'customerAccount.blocks',
    icon: 'customer',
    tags: ['customer-account', 'order', 'status'],
    spec: {
      type: 'customerAccount.blocks',
      name: 'Order Status Page Block',
      category: 'CUSTOMER_ACCOUNT',
      requires: ['CUSTOMER_ACCOUNT_UI'],
      config: {
        target: 'customer-account.order-status.block.render',
        title: 'Order Updates',
        blocks: [
          { kind: 'TEXT', content: 'Your order is being prepared and will ship soon.' },
          { kind: 'LINK', content: 'Track your shipment', url: 'https://example.com/tracking' },
        ],
        b2bOnly: false,
      },
    } as RecipeSpec,
  },
  {
    id: 'tpl-referral-widget',
    name: 'Referral Program Widget',
    description: 'App Proxy page for a customer referral program.',
    category: 'STOREFRONT_UI',
    type: 'proxy.widget',
    icon: 'widget',
    tags: ['proxy', 'referral', 'widget'],
    spec: {
      type: 'proxy.widget',
      name: 'Referral Program Widget',
      category: 'STOREFRONT_UI',
      requires: ['APP_PROXY'],
      config: {
        widgetId: 'referral-program',
        mode: 'HTML',
        title: 'Refer a Friend',
        message: 'Share your unique link and earn rewards when friends make a purchase.',
      },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium' },
        typography: { size: 'MD', weight: 'normal', lineHeight: 'normal', align: 'center' },
        colors: { text: '#1e293b', background: '#eff6ff', buttonBg: '#2563eb', buttonText: '#ffffff' },
        shape: { radius: 'lg', borderWidth: 'none', shadow: 'sm' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
      },
    } as RecipeSpec,
  },
  {
    id: 'tpl-cart-transform-bundle',
    name: 'Product Bundle Transform',
    description: 'Automatically bundle component SKUs into a single cart line.',
    category: 'FUNCTION',
    type: 'functions.cartTransform',
    icon: 'cart',
    tags: ['cart', 'bundle', 'transform'],
    spec: {
      type: 'functions.cartTransform',
      name: 'Product Bundle Transform',
      category: 'FUNCTION',
      requires: ['CART_TRANSFORM_FUNCTION_UPDATE'],
      config: {
        mode: 'BUNDLE',
        bundles: [
          {
            title: 'Starter Kit Bundle',
            componentSkus: ['SKU-001', 'SKU-002'],
            bundleSku: 'BUNDLE-001',
          },
        ],
        fallbackTheme: {
          enabled: true,
          notificationMessage: 'Bundling requires Shopify Plus.',
        },
      },
    } as RecipeSpec,
  },
  {
    id: 'tpl-integration-http-sync',
    name: 'HTTP Integration Sync',
    description: 'Sync order data to an external API when orders are created.',
    category: 'INTEGRATION',
    type: 'integration.httpSync',
    icon: 'integration',
    tags: ['integration', 'http', 'sync', 'api'],
    spec: {
      type: 'integration.httpSync',
      name: 'Order Data HTTP Sync',
      category: 'INTEGRATION',
      requires: [],
      config: {
        connectorId: 'external-api',
        endpointPath: '/api/orders/ingest',
        trigger: 'SHOPIFY_WEBHOOK_ORDER_CREATED',
        payloadMapping: { orderId: '{{order.id}}', total: '{{order.total_price}}' },
      },
    } as RecipeSpec,
  },
  {
    id: 'tpl-extension-blueprint',
    name: 'Theme App Extension Blueprint',
    description: 'Scaffold a new theme app extension with suggested file structure.',
    category: 'ADMIN_UI',
    type: 'platform.extensionBlueprint',
    icon: 'blueprint',
    tags: ['extension', 'blueprint', 'scaffold', 'admin'],
    spec: {
      type: 'platform.extensionBlueprint',
      name: 'Theme Extension Blueprint',
      category: 'ADMIN_UI',
      requires: [],
      config: {
        surface: 'THEME_APP_EXTENSION',
        goal: 'Create a reusable theme app extension block for product badges.',
        suggestedFiles: ['blocks/product-badge.liquid', 'assets/badge.css', 'locales/en.default.json'],
      },
    } as RecipeSpec,
  },
];

export function findTemplate(templateId: string): TemplateEntry | undefined {
  return MODULE_TEMPLATES.find(t => t.id === templateId);
}

export function getTemplatesByCategory(category?: string): TemplateEntry[] {
  if (!category) return MODULE_TEMPLATES;
  return MODULE_TEMPLATES.filter(t => t.category === category);
}
