import { json } from '@remix-run/node';
import { shopify } from '~/shopify.server';

/**
 * Agent API: Capability discovery index.
 *
 * GET /api/agent  →  describes all available agent API routes and their schemas.
 *
 * Agents can call this to discover what operations are available, what inputs
 * are required, and what responses to expect — without reading source code.
 */
export async function loader({ request }: { request: Request }) {
  await shopify.authenticate.admin(request);

  return json({
    ok: true,
    description: 'Superapp Agent API — stable JSON surface for agent/MCP callers.',
    version: '1.0',
    endpoints: [
      {
        id: 'list_modules',
        method: 'GET',
        path: '/api/agent/modules',
        description: 'List all modules for this shop.',
        returns: 'modules[]: { id, name, type, category, status, latestVersion, activeVersion, updatedAt, createdAt }',
      },
      {
        id: 'get_module',
        method: 'GET',
        path: '/api/agent/modules/:moduleId',
        description: 'Get a single module with full spec for every version.',
        returns: 'module: { id, name, type, category, status, versions[]: { version, status, spec, publishedAt, targetThemeId } }',
      },
      {
        id: 'create_module',
        method: 'POST',
        path: '/api/agent/modules',
        description: 'Create a new draft module from a full RecipeSpec.',
        body: '{ spec: RecipeSpec }',
        returns: '{ ok, moduleId, name, type, status, version }',
        notes: 'spec.type cannot be changed after creation. Spec must pass RecipeSpecSchema validation.',
      },
      {
        id: 'update_spec',
        method: 'POST',
        path: '/api/agent/modules/:moduleId/spec',
        description: 'Update a module spec — creates a new DRAFT version. Does not publish.',
        body: '{ spec: RecipeSpec }',
        returns: '{ ok, moduleId, version, versionId }',
        notes: 'spec.type must match the existing module type.',
      },
      {
        id: 'publish_module',
        method: 'POST',
        path: '/api/agent/modules/:moduleId/publish',
        description: 'Publish a module (latest DRAFT version, or a specific version).',
        body: '{ themeId?: string, version?: number }',
        returns: '{ ok, moduleId, versionId, version, target }',
        notes: 'themeId is required for theme.* module types. Plan gating and pre-publish validation apply.',
      },
      {
        id: 'rollback_module',
        method: 'POST',
        path: '/api/agent/modules/:moduleId/rollback',
        description: 'Roll back a module to a previously published version.',
        body: '{ version: number }',
        returns: '{ ok, moduleId, rolledBackToVersion, versionId }',
      },
      {
        id: 'delete_module',
        method: 'POST',
        path: '/api/agent/modules/:moduleId/delete',
        description: 'Permanently delete a module and all its versions. Cannot be undone.',
        body: '{}',
        returns: '{ ok, moduleId, deleted }',
      },
      {
        id: 'classify_intent',
        method: 'POST',
        path: '/api/agent/classify',
        description: 'Classify a user prompt into a module intent without generating a spec. READ-ONLY primitive.',
        body: '{ prompt: string }',
        returns: '{ classification: { intent, moduleType, confidence, confidenceScore, confidenceBand, alternatives, reasons }, intentPacket, routing: { shouldProceed, needsClarification, suggestion } }',
        notes: 'Use this before create to understand intent. confidenceBand: "direct" | "with_alternatives" | "low".',
      },
      {
        id: 'generate_options',
        method: 'POST',
        path: '/api/agent/generate-options',
        description: 'Generate 3 AI RecipeSpec options from a prompt WITHOUT saving. Classify→LLM pipeline primitive.',
        body: '{ prompt: string, preferredType?: string }',
        returns: '{ ok, prompt, classification: { intent, moduleType, confidence, confidenceBand, alternatives }, options: [{ index, explanation, recipe }], hint }',
        notes: 'Splits AI generation from persistence. Use POST /api/agent/modules with a selected spec to save.',
      },
      {
        id: 'validate_spec',
        method: 'POST',
        path: '/api/agent/validate-spec',
        description: 'Validate a RecipeSpec without saving or publishing. Returns schema + plan gate + pre-publish results. READ-ONLY.',
        body: '{ spec: RecipeSpec }',
        returns: '{ ok, valid, schemaError, planGate: { planTier, blocked, reasons, allowed }, prePublish: { errors, passed }, spec }',
        notes: 'Use before saving to check if a spec will pass all validation gates.',
      },
      {
        id: 'get_spec',
        method: 'GET',
        path: '/api/agent/modules/:moduleId/spec',
        description: 'Read the current spec of a module (active or latest draft). READ-ONLY primitive.',
        returns: '{ ok, moduleId, version, versionId, status, spec }',
      },
      {
        id: 'modify_module',
        method: 'POST',
        path: '/api/agent/modules/:moduleId/modify',
        description: 'Propose 3 AI modification options for a module spec. Does NOT persist — use modify-confirm to save.',
        body: '{ instruction: string }',
        returns: '{ ok, moduleId, currentVersion, options: [{ index, explanation, recipe }], hint }',
      },
      {
        id: 'modify_confirm',
        method: 'POST',
        path: '/api/agent/modules/:moduleId/modify-confirm',
        description: 'Save a selected modification option as a new DRAFT version.',
        body: '{ spec: RecipeSpec }',
        returns: '{ ok, moduleId, version, versionId }',
        notes: 'spec.type must match the existing module type.',
      },
      {
        id: 'hydrate_module',
        method: 'POST',
        path: '/api/agent/modules/:moduleId/hydrate',
        description: 'Generate full config envelope (admin schema, defaults, theme editor settings, validation report) for the module draft version.',
        body: '{ versionId?: string, force?: boolean }',
        returns: '{ ok, moduleId, versionId, validationReport, hydratedAt }',
        notes: 'Uses latest DRAFT if versionId omitted. If already hydrated and force is not true, returns existing report without re-running AI. Set force: true to regenerate.',
      },
      {
        id: 'list_connectors',
        method: 'GET',
        path: '/api/agent/connectors',
        description: 'List all external API connectors for this shop.',
        returns: 'connectors[]: { id, name, baseUrl, isActive, endpointCount, createdAt }',
      },
      {
        id: 'create_connector',
        method: 'POST',
        path: '/api/agent/connectors',
        description: 'Create a new external API connector.',
        body: '{ name: string, baseUrl: string, allowlistDomains?: string[], auth?: { type, token? } }',
        returns: '{ ok, connectorId, name, baseUrl }',
        notes: 'baseUrl must be https://. Auth types: none | bearer | api_key.',
      },
      {
        id: 'get_connector',
        method: 'GET',
        path: '/api/agent/connectors/:connectorId',
        description: 'Get a single connector with its endpoints list.',
        returns: '{ connector: { id, name, baseUrl, isActive, endpoints[], createdAt } }',
      },
      {
        id: 'update_connector',
        method: 'POST',
        path: '/api/agent/connectors/:connectorId',
        description: 'Update a connector name, baseUrl, or allowlistDomains.',
        body: '{ intent: "update", name?, baseUrl?, allowlistDomains? }',
        returns: '{ ok, connectorId, updated }',
        notes: 'baseUrl is SSRF-validated. Partial update — only provided fields are changed.',
      },
      {
        id: 'delete_connector',
        method: 'POST',
        path: '/api/agent/connectors/:connectorId',
        description: 'Delete a connector permanently.',
        body: '{ intent: "delete" }',
        returns: '{ ok, connectorId, deleted }',
      },
      {
        id: 'list_connector_endpoints',
        method: 'GET',
        path: '/api/agent/connectors/:connectorId/endpoints',
        description: 'List saved endpoints for a connector.',
        returns: 'endpoints[]: { id, name, path, method, defaultHeaders, defaultBody, lastTestedAt, lastStatus }',
      },
      {
        id: 'connector_endpoints_action',
        method: 'POST',
        path: '/api/agent/connectors/:connectorId/endpoints',
        description: 'Create, update, or delete a saved connector endpoint.',
        body: '{ intent: "create"|"update"|"delete", ...params }',
        returns: '{ ok, intent, endpointId, ... }',
        notes: 'Intents: create(name,path,method?,defaultHeaders?,defaultBody?), update(endpointId,...), delete(endpointId).',
      },
      {
        id: 'test_connector',
        method: 'POST',
        path: '/api/agent/connectors/:connectorId/test',
        description: 'Test a connector by calling a path.',
        body: '{ path: string, method?: string, headers?: object, body?: string }',
        returns: '{ ok, connectorId, path, method, status, ok: boolean, responseBody, latencyMs }',
      },
      {
        id: 'data_stores',
        method: 'GET',
        path: '/api/agent/data-stores',
        description: 'List all data stores with record counts.',
        returns: 'stores[]: { id, key, label, isEnabled, recordCount }',
      },
      {
        id: 'data_stores_action',
        method: 'POST',
        path: '/api/agent/data-stores',
        description: 'Perform a data store operation.',
        body: '{ intent: "enable"|"disable"|"create-custom"|"delete-store"|"add-record"|"update-record"|"delete-record", ...params }',
        returns: '{ ok, intent, ...result }',
        notes: 'Intents: enable(key), disable(key), create-custom(key,label,description?), delete-store(storeId), add-record(storeKey,payload,...), update-record(storeKey,recordId,...), delete-record(storeKey,recordId).',
      },
      {
        id: 'list_schedules',
        method: 'GET',
        path: '/api/agent/schedules',
        description: 'List all flow schedules.',
        returns: 'schedules[]: { id, name, cronExpr, isActive, nextRunAt, lastRunAt, createdAt }',
      },
      {
        id: 'schedules_action',
        method: 'POST',
        path: '/api/agent/schedules',
        description: 'Create, update, toggle, or delete a flow schedule.',
        body: '{ intent: "create"|"update"|"toggle"|"delete", ...params }',
        returns: '{ ok, ...result }',
        notes: 'Intents: create(name,cronExpr,eventJson?), update(scheduleId,name?,cronExpr?,eventJson?), toggle(scheduleId,isActive), delete(scheduleId).',
      },
      {
        id: 'list_store_records',
        method: 'GET',
        path: '/api/agent/data-stores/:storeKey/records',
        description: 'List records in a data store with pagination.',
        returns: '{ ok, storeKey, storeId, label, total, records[], pagination: { limit, offset, hasMore } }',
        notes: 'Query params: limit (max 200, default 50), offset (default 0).',
      },
      {
        id: 'list_flows',
        method: 'GET',
        path: '/api/agent/flows',
        description: 'List all flow.automation modules.',
        returns: 'flows[]: { moduleId, name, status, version }',
      },
      {
        id: 'run_flow',
        method: 'POST',
        path: '/api/agent/flows',
        description: 'Trigger flows for a given trigger event.',
        body: '{ intent: "run", trigger: string, payload?: object }',
        returns: '{ ok, trigger, ran }',
      },
      {
        id: 'get_config',
        method: 'GET',
        path: '/api/agent/config',
        description: 'Introspect the agent classification + routing config: CLEAN_INTENTS, ROUTING_TABLE, MODULE_TYPE_TO_INTENT, CONFIDENCE_THRESHOLDS. READ-ONLY.',
        returns: '{ confidenceThresholds, cleanIntents, routingTable, moduleTypeToIntent, outputSchemas, promptProfiles }',
        notes: 'Use this to understand routing rules without reading source code.',
      },
    ],
    notes: [
      'All requests require Shopify admin authentication (session cookie or token).',
      'All request bodies must be application/json.',
      'Errors return { error: string } with appropriate HTTP status codes.',
      'Actions are logged to ActivityLog with actor: SYSTEM and source: agent_api.',
      'GET /api/agent/config returns all classification rules, intents, and routing as JSON.',
    ],
  });
}
