import type { TemplateEntry } from '../types.js';
import { THEME_PLACEABLE_TEMPLATES } from '../../allowed-values.js';

/**
 * NSEC-STATS — native theme-section templates for the "stats / CTA band" family.
 *
 * recipeType = `theme.section`; surface = native_section (dual-mode: authored ONCE as a
 * `theme.section`, compiled either to an app-block metaobject OR, flag+exemption gated, to a
 * self-contained `sections/superapp-<slug>.liquid` file with a native `{% schema %}` via the
 * Theme Files API — see recipe.ts ThemeDeployMode + specs/034 native-sections lib). These are
 * full-section designs: the animated stats row ("12,000+ sold" Number Ticker / counter row —
 * design-vocabulary §2 "stats row (animated counters)" + fera.md visual_patterns "Number
 * Ticker") and the conversion CTA band ("CTA band" — design-vocabulary §2), each with 3–5
 * layout variants driven by the same token set so stores never look templated.
 *
 * MODEL (design.md §A.6): the reorderable content lives in `config.blocks[]`. Stat sections use
 * `kind: 'stat'` blocks (each a metric: value + label carried in `fields`, headline in `text`);
 * CTA-band sections are copy+button-driven so they carry their content in `config.fields` and
 * an empty (or single-feature) block list. `config.layout.layout` picks the variant; `style`
 * carries the token grammar (one accent over neutral, layered/inset depth, restrained motion
 * paired with reducedMotion — design-vocabulary §3/§4). Placement targets the marketing surfaces
 * (`index`, `page`, `product`, `collection`) from THEME_PLACEABLE_TEMPLATES.
 *
 * HONESTY: no live/dynamic data binding is claimed. The counters render whatever numbers the
 * merchant types into the blocks/fields (or the app's preview seed) — they are NOT wired to a
 * live orders/inventory feed. The "animated" counter is a CSS/JS count-up over that static
 * number, gated behind `accessibility.reducedMotion`. Nothing here implies a guaranteed-live
 * metric source.
 */
export const NATIVE_STATS_CTA_BAND_TEMPLATES: TemplateEntry[] = [
  // ── Stats variants ───────────────────────────────────────────────────────────
  {
    id: 'NSEC-STATS-01',
    name: 'Stats — Animated Counter Row',
    description: 'A horizontal row of animated count-up metrics ("12,000+ sold") for the homepage — one accent, four evenly spaced stat blocks.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'stats',
    tags: ['section', 'stats', 'counters', 'social-proof', 'index', 'bold-dtc'],
    spec: {
      type: 'theme.section',
      name: 'Stats — Animated Counter Row',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'stats',
        activation: 'section',
        title: 'The numbers speak for themselves',
        subtitle: 'Trusted by thousands of customers worldwide',
        layout: { layout: 'grid', columns: 4 },
        fields: {
          animateCounters: true,
          countUpDurationMs: 1600,
          dividers: true,
          columnsDesktop: 4,
          columnsMobile: 2,
        },
        blocks: [
          { kind: 'stat', text: '12,000+', fields: { label: 'Orders shipped', prefix: '', suffix: '+', animate: true } },
          { kind: 'stat', text: '4.9', fields: { label: 'Average rating', suffix: '★', decimals: 1, animate: true } },
          { kind: 'stat', text: '98', fields: { label: 'Would buy again', suffix: '%', animate: true } },
          { kind: 'stat', text: '30', fields: { label: 'Day returns', suffix: '-day', animate: false } },
        ],
      },
      placement: { enabled_on: { templates: ['index'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: '2XL', weight: 'bold', lineHeight: 'tight', align: 'center' },
        colors: { text: '#0f172a', background: '#ffffff', seed: '#2563eb', overlayBackdropOpacity: 0.45 },
        shape: { radius: 'md', borderWidth: 'none', shadow: 'none', elevation: 'border' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'slow', easing: 'enter' },
      },
    },
  },
  {
    id: 'NSEC-STATS-02',
    name: 'Stats — Card Grid',
    description: 'A 2x2 grid of elevated stat cards for the About/brand page — each metric on its own soft-shadow card with a supporting caption.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'stats',
    tags: ['section', 'stats', 'grid', 'about', 'page', 'editorial-wellness'],
    spec: {
      type: 'theme.section',
      name: 'Stats — Card Grid',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'stats',
        activation: 'section',
        title: 'Our impact by the numbers',
        subtitle: 'A decade of doing things the slow, careful way',
        layout: { layout: 'grid', columns: 2 },
        fields: {
          animateCounters: true,
          countUpDurationMs: 1400,
          cardStyle: 'elevated',
          columnsDesktop: 2,
          columnsMobile: 1,
        },
        blocks: [
          { kind: 'stat', text: '10', fields: { label: 'Years in business', suffix: '+', caption: 'Independent and founder-owned since 2016.', animate: true } },
          { kind: 'stat', text: '250,000', fields: { label: 'Garments made', caption: 'Cut and sewn in our own studio.', animate: true } },
          { kind: 'stat', text: '1,900', fields: { label: 'Five-star reviews', suffix: '+', caption: 'From verified buyers across the store.', animate: true } },
          { kind: 'stat', text: '12', fields: { label: 'Countries served', caption: 'Shipping carbon-neutral, worldwide.', animate: false } },
        ],
      },
      placement: { enabled_on: { templates: ['page'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'loose', density: 'airy' },
        typography: { size: 'XL', weight: 'medium', lineHeight: 'normal', align: 'center' },
        colors: { text: '#1c1917', background: '#faf9f7', border: '#e7e5e4', seed: '#6b705c', overlayBackdropOpacity: 0.45 },
        shape: { radius: 'lg', borderWidth: 'thin', shadow: 'sm', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'base', easing: 'standard' },
      },
    },
  },
  {
    id: 'NSEC-STATS-03',
    name: 'Stats — Big Number Split',
    description: 'A two-up split: one oversized hero metric on the left, a stacked list of supporting stats on the right — for a data-forward brand story.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'stats',
    tags: ['section', 'stats', 'split', 'big-number', 'page', 'tech-utility'],
    spec: {
      type: 'theme.section',
      name: 'Stats — Big Number Split',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'stats',
        activation: 'section',
        title: 'Built to last',
        subtitle: 'The metrics we hold ourselves to',
        layout: { layout: 'columns', columns: 2 },
        fields: {
          animateCounters: true,
          heroBlockIndex: 0,
          countUpDurationMs: 2000,
          columnsDesktop: 2,
          columnsMobile: 1,
        },
        blocks: [
          { kind: 'stat', text: '99.9', fields: { label: 'Uptime this year', suffix: '%', hero: true, animate: true } },
          { kind: 'stat', text: '48', fields: { label: 'Hours to ship', suffix: 'h', animate: true } },
          { kind: 'stat', text: '3', fields: { label: 'Fulfilment centers', animate: false } },
          { kind: 'stat', text: '15,400', fields: { label: 'Units in stock', animate: true } },
        ],
      },
      placement: { enabled_on: { templates: ['page', 'index'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'wide', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'loose', density: 'compact' },
        typography: { size: '2XL', weight: 'bold', lineHeight: 'tight', align: 'left' },
        colors: { text: '#e2e8f0', background: '#0b1120', border: '#1e293b', seed: '#38bdf8', overlayBackdropOpacity: 0.45 },
        shape: { radius: 'sm', borderWidth: 'thin', shadow: 'none', elevation: 'border' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'fast', easing: 'mechanical' },
      },
    },
  },
  {
    id: 'NSEC-STATS-04',
    name: 'Stats — Trust Bar (Compact Inline)',
    description: 'A slim, single-row trust strip of icon-led metrics sitting under the product hero — compact, quiet, one accent, no card chrome.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'stats',
    tags: ['section', 'stats', 'trust', 'product', 'inline', 'apple-hig'],
    spec: {
      type: 'theme.section',
      name: 'Stats — Trust Bar (Compact Inline)',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'stats',
        activation: 'section',
        subtitle: 'Why shoppers choose us',
        layout: { layout: 'grid', columns: 3 },
        fields: {
          animateCounters: false,
          showIcons: true,
          divider: 'dot',
          columnsDesktop: 3,
          columnsMobile: 3,
        },
        blocks: [
          { kind: 'stat', text: '50k+', fields: { label: 'Happy customers', icon: 'users' } },
          { kind: 'stat', text: 'Free', fields: { label: 'Shipping over $50', icon: 'truck' } },
          { kind: 'stat', text: '30-day', fields: { label: 'Easy returns', icon: 'refresh' } },
        ],
      },
      placement: { enabled_on: { templates: ['product'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'medium', margin: 'none', gap: 'medium', density: 'compact' },
        typography: { size: 'MD', weight: 'medium', lineHeight: 'normal', align: 'center' },
        colors: { text: '#111827', background: '#f9fafb', seed: '#111827', overlayBackdropOpacity: 0.45 },
        shape: { radius: 'md', borderWidth: 'none', shadow: 'none', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'fast', easing: 'standard' },
      },
    },
  },
  {
    id: 'NSEC-STATS-05',
    name: 'Stats — Milestone Timeline',
    description: 'Year-anchored milestone metrics arranged as a horizontal timeline for a founder/heritage page — each block a "since 20XX" achievement.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'stats',
    tags: ['section', 'stats', 'timeline', 'about', 'page', 'editorial-wellness'],
    spec: {
      type: 'theme.section',
      name: 'Stats — Milestone Timeline',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'stats',
        activation: 'section',
        title: 'How far we have come',
        subtitle: 'From a kitchen table to a global brand',
        layout: { layout: 'columns', columns: 4 },
        fields: {
          animateCounters: true,
          connector: 'line',
          columnsDesktop: 4,
          columnsMobile: 1,
        },
        blocks: [
          { kind: 'stat', text: '2016', fields: { label: 'Founded', milestone: 'First 100 orders', animate: false } },
          { kind: 'stat', text: '2019', fields: { label: 'Went global', milestone: 'Shipping to 12 countries', animate: false } },
          { kind: 'stat', text: '2022', fields: { label: '100k customers', milestone: 'Six-figure community', animate: true } },
          { kind: 'stat', text: '2025', fields: { label: 'Carbon neutral', milestone: 'Every order offset', animate: false } },
        ],
      },
      placement: { enabled_on: { templates: ['page'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'wide', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'loose', density: 'airy' },
        typography: { size: 'LG', weight: 'medium', lineHeight: 'relaxed', align: 'center' },
        colors: { text: '#292524', background: '#ffffff', border: '#d6d3d1', seed: '#a16207', overlayBackdropOpacity: 0.45 },
        shape: { radius: 'md', borderWidth: 'thin', shadow: 'none', elevation: 'border' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'slow', easing: 'enter' },
      },
    },
  },
  // ── CTA band variants ────────────────────────────────────────────────────────
  {
    id: 'NSEC-STATS-06',
    name: 'CTA Band — Centered Gradient',
    description: 'A full-width centered call-to-action band on a bold gradient ground — one headline, one supporting line, one primary button.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'banner',
    tags: ['section', 'cta', 'conversion', 'index', 'bold-dtc'],
    spec: {
      type: 'theme.section',
      name: 'CTA Band — Centered Gradient',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'cta',
        activation: 'section',
        title: 'Ready to make the switch?',
        subtitle: 'Join thousands who upgraded their everyday. Free shipping on your first order.',
        layout: { layout: 'stacked' },
        fields: {
          ctaLabel: 'Shop the collection',
          ctaUrl: 'https://example.com/collections/all',
          secondaryLabel: 'Learn more',
          secondaryUrl: 'https://example.com/pages/about',
          background: 'gradient',
          fullBleed: true,
        },
        blocks: [],
      },
      placement: { enabled_on: { templates: ['index'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'full', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: '2XL', weight: 'bold', lineHeight: 'tight', align: 'center' },
        colors: { text: '#ffffff', background: '#4f46e5', buttonBg: '#ffffff', buttonText: '#4f46e5', seed: '#7c3aed', overlayBackdropOpacity: 0.45 },
        shape: { radius: 'lg', borderWidth: 'none', shadow: 'md', elevation: 'glow' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'base', easing: 'enter' },
      },
    },
  },
  {
    id: 'NSEC-STATS-07',
    name: 'CTA Band — Split with Media',
    description: 'A two-column CTA band: persuasive copy and a button on one side, a supporting image on the other — for a page or homepage promo.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'banner',
    tags: ['section', 'cta', 'split', 'promo', 'page', 'editorial-wellness'],
    spec: {
      type: 'theme.section',
      name: 'CTA Band — Split with Media',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'cta',
        activation: 'section',
        title: 'Designed for the way you live',
        subtitle: 'Thoughtful pieces, made to be used every day. See what fits your routine.',
        layout: { layout: 'columns', columns: 2 },
        fields: {
          ctaLabel: 'Explore the range',
          ctaUrl: 'https://example.com/collections/featured',
          mediaSide: 'right',
          imageUrl: 'https://cdn.example.com/cta/lifestyle.jpg',
        },
        blocks: [],
      },
      placement: { enabled_on: { templates: ['page', 'index'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'loose', density: 'airy' },
        typography: { size: 'XL', weight: 'medium', lineHeight: 'relaxed', align: 'left' },
        colors: { text: '#1c1917', background: '#f5f5f4', buttonBg: '#1c1917', buttonText: '#ffffff', seed: '#78716c', overlayBackdropOpacity: 0.45 },
        shape: { radius: 'lg', borderWidth: 'none', shadow: 'sm', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'slow', easing: 'standard' },
      },
    },
  },
  {
    id: 'NSEC-STATS-08',
    name: 'CTA Band — Newsletter Capture',
    description: 'An inline email-capture CTA band with a headline, incentive line, and a single input+button row — for footer or content pages.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'banner',
    tags: ['section', 'cta', 'newsletter', 'email-capture', 'page', 'playful-commerce'],
    spec: {
      type: 'theme.section',
      name: 'CTA Band — Newsletter Capture',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'cta',
        activation: 'section',
        title: 'Get 10% off your first order',
        subtitle: 'Sign up for early access, restock alerts, and members-only drops.',
        layout: { layout: 'stacked' },
        fields: {
          captureMode: 'email',
          inputPlaceholder: 'you@example.com',
          ctaLabel: 'Sign me up',
          consentText: 'By subscribing you agree to receive marketing emails. Unsubscribe anytime.',
          successMessage: 'You are on the list — check your inbox for your code.',
        },
        blocks: [],
      },
      placement: { enabled_on: { templates: ['page', 'index'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'narrow', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: 'XL', weight: 'bold', lineHeight: 'normal', align: 'center' },
        colors: { text: '#3b0764', background: '#faf5ff', buttonBg: '#9333ea', buttonText: '#ffffff', seed: '#c084fc', overlayBackdropOpacity: 0.45 },
        shape: { radius: 'xl', borderWidth: 'none', shadow: 'sm', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'base', easing: 'enter' },
      },
    },
  },
  {
    id: 'NSEC-STATS-09',
    name: 'CTA Band — Countdown Urgency',
    description: 'A high-contrast CTA band pairing a promo headline with a static countdown deadline line and a primary button — for sale/launch pages.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'banner',
    tags: ['section', 'cta', 'countdown', 'urgency', 'collection', 'bold-dtc'],
    spec: {
      type: 'theme.section',
      name: 'CTA Band — Countdown Urgency',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'cta',
        activation: 'section',
        title: 'The sale ends this weekend',
        subtitle: 'Up to 40% off site-wide. Once it is gone, it is gone.',
        layout: { layout: 'stacked' },
        fields: {
          ctaLabel: 'Shop the sale',
          ctaUrl: 'https://example.com/collections/sale',
          countdownEndsAt: '2026-12-31T23:59:59Z',
          countdownStyle: 'digits',
          note: 'Countdown is a visual timer only; the merchant sets the deadline.',
        },
        blocks: [],
      },
      placement: { enabled_on: { templates: ['collection', 'index'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'full', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: '2XL', weight: 'bold', lineHeight: 'tight', align: 'center' },
        colors: { text: '#fef2f2', background: '#991b1b', buttonBg: '#fef2f2', buttonText: '#991b1b', seed: '#ef4444', overlayBackdropOpacity: 0.45 },
        shape: { radius: 'md', borderWidth: 'none', shadow: 'md', elevation: 'glow' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'fast', easing: 'mechanical' },
      },
    },
  },
  {
    id: 'NSEC-STATS-10',
    name: 'Stats + CTA — Proof-to-Action Band',
    description: 'A combined band: a row of proof metrics above a single call-to-action button — the "here is the proof, now buy" homepage closer.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'stats',
    tags: ['section', 'stats', 'cta', 'social-proof', 'index', 'bold-dtc'],
    spec: {
      type: 'theme.section',
      name: 'Stats + CTA — Proof-to-Action Band',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'stats',
        activation: 'section',
        title: 'Join 50,000+ happy customers',
        subtitle: 'The proof is in the numbers — and the next order could be yours.',
        layout: { layout: 'grid', columns: 3 },
        fields: {
          animateCounters: true,
          countUpDurationMs: 1500,
          ctaLabel: 'Start shopping',
          ctaUrl: 'https://example.com/collections/all',
          ctaBelowStats: true,
          columnsDesktop: 3,
          columnsMobile: 3,
        },
        blocks: [
          { kind: 'stat', text: '50,000', fields: { label: 'Orders delivered', suffix: '+', animate: true } },
          { kind: 'stat', text: '4.9', fields: { label: 'Average rating', suffix: '★', decimals: 1, animate: true } },
          { kind: 'stat', text: '24', fields: { label: 'Hour dispatch', suffix: 'h', animate: false } },
        ],
      },
      placement: { enabled_on: { templates: ['index'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: 'XL', weight: 'bold', lineHeight: 'normal', align: 'center' },
        colors: { text: '#0f172a', background: '#f8fafc', buttonBg: '#0f172a', buttonText: '#ffffff', seed: '#0ea5e9', overlayBackdropOpacity: 0.45 },
        shape: { radius: 'lg', borderWidth: 'none', shadow: 'sm', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'slow', easing: 'enter' },
      },
    },
  },
];
