import type { TemplateEntry } from '../types.js';
import { THEME_PLACEABLE_TEMPLATES } from '../../allowed-values.js';

/**
 * NSEC-TEST — native-section testimonials / review social-proof (surface-coverage 034).
 *
 * Ten `theme.section` templates that compile to a self-contained native
 * `sections/superapp-<slug>.liquid` (ThemeDeployMode `native_section`, recipe.ts:100)
 * OR to the shipped app-block metaobject. All are pure presentation over the
 * merchant's own review corpus — the section renders the display layer; the review
 * data / media / verified-buyer state that a Loox/Judge.me/Okendo/Fera backend owns is
 * out of scope for a section (see each corpus record's mapping_note). Blocks carry
 * demo review copy so the preview + editor show a realistic "wall of love"; a merchant
 * swaps in their own reviews per block.
 *
 * Grounding: the real testimonials/social-proof widget fleets and their design-tab
 * knobs — Fera (List | Masonry | Carousel widget kinds; verified badge; star color),
 * Loox (Testimonials / Gallery / Cards carousel variants; reviews-per-row desktop/mobile),
 * Okendo (left summary rail: average score + star-distribution bars + attribute averages),
 * Judge.me (verbatim knobs: Show reviewer avatar / location / country flag / date; review
 * word singular/plural; no-reviews text), ProveSource (Live-visitor / Social-counter big
 * numbers, "12,000+ sold" number-ticker social proof). Layout variants are driven by the
 * same token set (design-vocabulary §2 "Testimonials — wall / marquee / single-quote
 * spotlight") so no two stores look templated.
 */
export const NATIVE_TESTIMONIALS_SOCIAL_PROOF_TEMPLATES: TemplateEntry[] = [
  {
    id: 'NSEC-TEST-01',
    name: 'Wall of Love — Photo Review Grid',
    description:
      'Masonry "wall of love" grid of verified-buyer photo reviews for the product page, with star cards and reviewer avatars.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'reviews',
    tags: ['section', 'reviews', 'social-proof', 'ugc', 'wall-of-love', 'product'],
    spec: {
      type: 'theme.section',
      name: 'Wall of Love — Photo Review Grid',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'reviews',
        activation: 'section',
        title: 'Loved by thousands',
        subtitle: 'Real photos from verified buyers',
        layout: { layout: 'masonry', columns: 3 },
        fields: {
          reviewsPerRowDesktop: 3,
          reviewsPerRowMobile: 1,
          showVerifiedBadge: true,
          showReviewerAvatar: true,
          showReviewDate: true,
          showMediaGallery: true,
          starColor: '#f5a623',
          reviewWordSingular: 'review',
          reviewWordPlural: 'reviews',
          noReviewsText: 'Be the first to leave a review.',
        },
        blocks: [
          {
            kind: 'review-card',
            text: 'Exactly as pictured and the quality is unreal. Obsessed already.',
            imageUrl: 'https://cdn.shopify.com/s/files/reviews/wall-01.jpg',
            fields: { author: 'Maya R.', rating: 5, verified: true, date: '2026-05-18', location: 'Austin, TX' },
          },
          {
            kind: 'review-card',
            text: 'Fast shipping, beautiful packaging, and it photographs even better in person.',
            imageUrl: 'https://cdn.shopify.com/s/files/reviews/wall-02.jpg',
            fields: { author: 'Devon K.', rating: 5, verified: true, date: '2026-05-11', location: 'Denver, CO' },
          },
          {
            kind: 'review-card',
            text: 'Bought two — gifting one to my sister. Would absolutely order again.',
            imageUrl: 'https://cdn.shopify.com/s/files/reviews/wall-03.jpg',
            fields: { author: 'Priya S.', rating: 4, verified: true, date: '2026-04-29', location: 'Seattle, WA' },
          },
          {
            kind: 'review-card',
            text: 'Held up after a month of daily use. Genuinely my new favorite.',
            imageUrl: 'https://cdn.shopify.com/s/files/reviews/wall-04.jpg',
            fields: { author: 'Jordan M.', rating: 5, verified: true, date: '2026-04-22', location: 'Miami, FL' },
          },
        ],
      },
      placement: { enabled_on: { templates: ['product'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: 'LG', weight: 'bold', lineHeight: 'normal', align: 'center' },
        colors: { overlayBackdropOpacity: 0.45, seed: '#f5a623' },
        shape: { radius: 'lg', borderWidth: 'thin', shadow: 'sm', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'base', easing: 'enter' },
        pack: 'bold',
      },
    },
  },
  {
    id: 'NSEC-TEST-02',
    name: 'Testimonials Carousel — Curated Quotes',
    description:
      'Auto-advancing carousel of curated best reviews for the homepage — the classic "Testimonials" slider variant with star rows and attribution.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'reviews',
    tags: ['section', 'testimonials', 'social-proof', 'carousel', 'index'],
    spec: {
      type: 'theme.section',
      name: 'Testimonials Carousel — Curated Quotes',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'testimonials',
        activation: 'section',
        title: 'What customers are saying',
        subtitle: 'Hand-picked from thousands of verified reviews',
        layout: { layout: 'carousel' },
        fields: {
          reviewsPerRowDesktop: 3,
          reviewsPerRowMobile: 1,
          autoAdvance: true,
          showVerifiedBadge: true,
          showStars: true,
          starColor: '#111111',
          carouselVariant: 'testimonials',
        },
        blocks: [
          {
            kind: 'review-card',
            text: 'The kind of quality you can feel the moment you open the box. Worth every penny.',
            fields: { author: 'Camille B.', rating: 5, verified: true, title: 'Repeat customer' },
          },
          {
            kind: 'review-card',
            text: 'I recommend this to everyone who asks. It has become part of my daily ritual.',
            fields: { author: 'Andre L.', rating: 5, verified: true, title: 'Verified buyer' },
          },
          {
            kind: 'review-card',
            text: 'Customer support went above and beyond. The product speaks for itself.',
            fields: { author: 'Sofia T.', rating: 5, verified: true, title: 'Verified buyer' },
          },
          {
            kind: 'review-card',
            text: 'Three orders in and it never disappoints. Beautifully made.',
            fields: { author: 'Marcus W.', rating: 4, verified: true, title: 'Repeat customer' },
          },
          {
            kind: 'review-card',
            text: 'Better than I hoped and it arrived days early. Five stars from me.',
            fields: { author: 'Nadia P.', rating: 5, verified: true, title: 'Verified buyer' },
          },
        ],
      },
      placement: { enabled_on: { templates: ['index'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'wide', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'loose', density: 'airy' },
        typography: { size: 'XL', weight: 'normal', lineHeight: 'relaxed', align: 'center' },
        colors: { overlayBackdropOpacity: 0.45, seed: '#8a7d6b' },
        shape: { radius: 'md', borderWidth: 'none', shadow: 'sm', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'slow', easing: 'standard' },
        pack: 'luxe',
      },
    },
  },
  {
    id: 'NSEC-TEST-03',
    name: 'Single-Quote Spotlight',
    description:
      'Full-width single-quote spotlight for the homepage — one large marquee testimonial with star rating and named attribution for maximum trust weight.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'reviews',
    tags: ['section', 'testimonials', 'social-proof', 'spotlight', 'index'],
    spec: {
      type: 'theme.section',
      name: 'Single-Quote Spotlight',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'testimonials',
        activation: 'section',
        title: 'In their words',
        layout: { layout: 'stacked' },
        fields: {
          showStars: true,
          starColor: '#c8a15a',
          showVerifiedBadge: true,
          showReviewerAvatar: true,
          emphasis: 'spotlight',
        },
        blocks: [
          {
            kind: 'review-card',
            text: 'I have tried every brand on the market and nothing comes close. This is the one I keep coming back to, and the one I tell all my friends about.',
            imageUrl: 'https://cdn.shopify.com/s/files/reviews/spotlight-01.jpg',
            fields: { author: 'Eleanor V.', rating: 5, verified: true, title: 'Customer since 2023' },
          },
        ],
      },
      placement: { enabled_on: { templates: ['index'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'inline', anchor: 'center', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'airy' },
        typography: { size: '2XL', weight: 'medium', lineHeight: 'relaxed', align: 'center' },
        colors: { overlayBackdropOpacity: 0.45, seed: '#c8a15a' },
        shape: { radius: 'sm', borderWidth: 'none', shadow: 'none', elevation: 'emboss' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'slow', easing: 'enter' },
        pack: 'luxe',
      },
    },
  },
  {
    id: 'NSEC-TEST-04',
    name: 'Reviews Feed — List with Rating Summary',
    description:
      'Vertical review-feed list for the product page with a left summary rail: average score, star-distribution bars, and review count.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'reviews',
    tags: ['section', 'reviews', 'social-proof', 'list', 'product'],
    spec: {
      type: 'theme.section',
      name: 'Reviews Feed — List with Rating Summary',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'reviews',
        activation: 'section',
        title: 'Customer reviews',
        layout: { layout: 'stacked' },
        fields: {
          showSummaryRail: true,
          averageRating: 4.8,
          reviewCount: 1284,
          distribution: { 5: 1052, 4: 168, 3: 41, 2: 14, 1: 9 },
          showReviewerAvatar: true,
          showReviewerLocation: true,
          showReviewDate: true,
          showVerifiedBadge: true,
          starColor: '#111111',
          reviewWordSingular: 'review',
          reviewWordPlural: 'reviews',
          noReviewsText: 'No reviews yet — check back soon.',
        },
        blocks: [
          {
            kind: 'review-card',
            text: 'Comfortable from day one, no break-in needed. True to size and the fit is spot on.',
            fields: { author: 'Hannah G.', rating: 5, verified: true, date: '2026-06-02', location: 'Portland, OR' },
          },
          {
            kind: 'review-card',
            text: 'Solid build and thoughtful details. Docked one star only because I wanted a second color.',
            fields: { author: 'Theo N.', rating: 4, verified: true, date: '2026-05-27', location: 'Chicago, IL' },
          },
          {
            kind: 'review-card',
            text: 'My third purchase from this brand. Consistent quality every single time.',
            fields: { author: 'Rosa I.', rating: 5, verified: true, date: '2026-05-19', location: 'San Diego, CA' },
          },
        ],
      },
      placement: { enabled_on: { templates: ['product'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'medium', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: 'MD', weight: 'normal', lineHeight: 'normal', align: 'left' },
        colors: { seed: '#059669', overlayBackdropOpacity: 0.45 },
        shape: { radius: 'md', borderWidth: 'thin', shadow: 'none', elevation: 'border' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        pack: 'luxe',
      },
    },
  },
  {
    id: 'NSEC-TEST-05',
    name: 'UGC Media Gallery — Photo & Video',
    description:
      'Site-wide customer media gallery grid of photo and video reviews for a content page — a "Happy Customers" UGC wall pulled from your best media reviews.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'gallery',
    tags: ['section', 'reviews', 'social-proof', 'ugc', 'gallery', 'page'],
    spec: {
      type: 'theme.section',
      name: 'UGC Media Gallery — Photo & Video',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'reviews',
        activation: 'section',
        title: 'Happy customers',
        subtitle: 'Tagged photos and videos from real orders',
        // 6 UGC tiles → 3×2 wall (was columns:4, which left a 2-tile orphan row).
        layout: { layout: 'grid', columns: 3 },
        fields: {
          reviewsPerRowDesktop: 3,
          reviewsPerRowMobile: 2,
          mediaOnly: true,
          openInLightbox: true,
          showVerifiedBadge: true,
          starColor: '#e8455a',
        },
        blocks: [
          {
            kind: 'review-card',
            imageUrl: 'https://cdn.shopify.com/s/files/reviews/ugc-01.jpg',
            fields: { author: 'Bea C.', rating: 5, verified: true, mediaType: 'photo' },
          },
          {
            kind: 'review-card',
            imageUrl: 'https://cdn.shopify.com/s/files/reviews/ugc-02.jpg',
            fields: { author: 'Owen D.', rating: 5, verified: true, mediaType: 'video' },
          },
          {
            kind: 'review-card',
            imageUrl: 'https://cdn.shopify.com/s/files/reviews/ugc-03.jpg',
            fields: { author: 'Lena F.', rating: 4, verified: true, mediaType: 'photo' },
          },
          {
            kind: 'review-card',
            imageUrl: 'https://cdn.shopify.com/s/files/reviews/ugc-04.jpg',
            fields: { author: 'Kai H.', rating: 5, verified: true, mediaType: 'photo' },
          },
          {
            kind: 'review-card',
            imageUrl: 'https://cdn.shopify.com/s/files/reviews/ugc-05.jpg',
            fields: { author: 'Mira J.', rating: 5, verified: true, mediaType: 'video' },
          },
          {
            kind: 'review-card',
            imageUrl: 'https://cdn.shopify.com/s/files/reviews/ugc-06.jpg',
            fields: { author: 'Ravi K.', rating: 5, verified: true, mediaType: 'photo' },
          },
        ],
      },
      placement: { enabled_on: { templates: ['page'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'wide', zIndex: 'base' },
        spacing: { padding: 'medium', margin: 'none', gap: 'tight', density: 'compact' },
        typography: { size: 'LG', weight: 'bold', lineHeight: 'normal', align: 'center' },
        colors: { overlayBackdropOpacity: 0.6, seed: '#e8455a' },
        shape: { radius: 'md', borderWidth: 'none', shadow: 'sm', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'fast', easing: 'enter' },
        pack: 'bold',
      },
    },
  },
  {
    id: 'NSEC-TEST-06',
    name: 'Review Cards Slider — Compact',
    description:
      'Compact swipeable "Cards" carousel of short reviews for the product page — reviewer avatar, star row, and a one-line quote per card.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'reviews',
    tags: ['section', 'reviews', 'social-proof', 'carousel', 'product'],
    spec: {
      type: 'theme.section',
      name: 'Review Cards Slider — Compact',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'reviews',
        activation: 'section',
        title: 'From the reviews',
        layout: { layout: 'carousel' },
        fields: {
          reviewsPerRowDesktop: 4,
          reviewsPerRowMobile: 1,
          carouselVariant: 'cards',
          showReviewerAvatar: true,
          showStars: true,
          starColor: '#ff6b35',
        },
        blocks: [
          {
            kind: 'review-card',
            text: 'Ridiculously good. 10/10.',
            fields: { author: 'Tess A.', rating: 5, verified: true },
          },
          {
            kind: 'review-card',
            text: 'Arrived early and looks amazing.',
            fields: { author: 'Gus B.', rating: 5, verified: true },
          },
          {
            kind: 'review-card',
            text: 'Great value for the quality.',
            fields: { author: 'Ivy C.', rating: 4, verified: true },
          },
          {
            kind: 'review-card',
            text: 'Already ordered a second one.',
            fields: { author: 'Otto D.', rating: 5, verified: true },
          },
          {
            kind: 'review-card',
            text: 'Exceeded my expectations.',
            fields: { author: 'Faye E.', rating: 5, verified: true },
          },
          {
            kind: 'review-card',
            text: 'My go-to gift from now on.',
            fields: { author: 'Levi G.', rating: 5, verified: true },
          },
        ],
      },
      placement: { enabled_on: { templates: ['product'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'medium', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: 'MD', weight: 'medium', lineHeight: 'normal', align: 'center' },
        colors: { overlayBackdropOpacity: 0.45, seed: '#ff6b35' },
        shape: { radius: 'xl', borderWidth: 'none', shadow: 'md', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'base', easing: 'enter' },
        pack: 'bold',
      },
    },
  },
  {
    id: 'NSEC-TEST-07',
    name: 'Social Proof Stat Bar',
    description:
      'A compact big-number social-proof bar for the homepage — aggregate rating, review count, and "units sold" number-ticker stats sit side by side.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'social-proof',
    tags: ['section', 'social-proof', 'stats', 'trust', 'index'],
    spec: {
      type: 'theme.section',
      name: 'Social Proof Stat Bar',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'social-proof',
        activation: 'section',
        title: 'Trusted by our community',
        layout: { layout: 'grid', columns: 4 },
        fields: {
          animateCounters: true,
          starColor: '#111111',
        },
        blocks: [
          { kind: 'stat', text: '4.8', fields: { label: 'Average rating', suffix: '/ 5', showStars: true } },
          { kind: 'stat', text: '12,400', fields: { label: 'Verified reviews', suffix: '+' } },
          { kind: 'stat', text: '86,000', fields: { label: 'Units sold', suffix: '+' } },
          { kind: 'stat', text: '97', fields: { label: 'Would recommend', suffix: '%' } },
        ],
      },
      placement: { enabled_on: { templates: ['index'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'wide', zIndex: 'base' },
        spacing: { padding: 'medium', margin: 'none', gap: 'medium', density: 'compact' },
        typography: { size: '2XL', weight: 'bold', lineHeight: 'tight', align: 'center' },
        colors: { seed: '#4f46e5', overlayBackdropOpacity: 0.45 },
        shape: { radius: 'sm', borderWidth: 'thin', shadow: 'none', elevation: 'border' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'fast', easing: 'standard' },
        pack: 'bold',
      },
    },
  },
  {
    id: 'NSEC-TEST-08',
    name: 'Verified Reviews — Attribute Summary Rail',
    description:
      'PDP reviews module with an attribute summary rail (fit, quality, value averages) alongside a filterable list of verified reviews.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'reviews',
    tags: ['section', 'reviews', 'social-proof', 'attributes', 'product'],
    spec: {
      type: 'theme.section',
      name: 'Verified Reviews — Attribute Summary Rail',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'reviews',
        activation: 'section',
        title: 'Reviews & ratings',
        subtitle: 'What buyers say about fit, quality, and value',
        layout: { layout: 'stacked' },
        fields: {
          showSummaryRail: true,
          averageRating: 4.7,
          reviewCount: 642,
          attributeAverages: [
            { label: 'Fit', value: 4.6, scale: 5 },
            { label: 'Quality', value: 4.9, scale: 5 },
            { label: 'Value', value: 4.5, scale: 5 },
          ],
          showFilterChips: true,
          showVerifiedBadge: true,
          showReviewerAvatar: true,
          showReviewDate: true,
          starColor: '#2b2b2b',
        },
        blocks: [
          {
            kind: 'review-card',
            text: 'Runs true to size and the fabric feels premium. Exactly what I hoped for.',
            fields: {
              author: 'Nora Q.',
              rating: 5,
              verified: true,
              date: '2026-06-08',
              attributes: { Fit: 'True to size', Quality: 'Excellent' },
            },
          },
          {
            kind: 'review-card',
            text: 'Great quality overall — sizing ran slightly large so I would size down.',
            fields: {
              author: 'Sam V.',
              rating: 4,
              verified: true,
              date: '2026-05-30',
              attributes: { Fit: 'Runs large', Quality: 'Very good' },
            },
          },
          {
            kind: 'review-card',
            text: 'Worth the price and then some. Third order and still impressed.',
            fields: {
              author: 'Ida W.',
              rating: 5,
              verified: true,
              date: '2026-05-21',
              attributes: { Fit: 'True to size', Value: 'Great' },
            },
          },
        ],
      },
      placement: { enabled_on: { templates: ['product'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'medium', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: 'MD', weight: 'normal', lineHeight: 'normal', align: 'left' },
        colors: { seed: '#be123c', overlayBackdropOpacity: 0.45 },
        shape: { radius: 'md', borderWidth: 'thin', shadow: 'none', elevation: 'border' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        pack: 'luxe',
      },
    },
  },
  {
    id: 'NSEC-TEST-09',
    name: 'As Seen In — Press & Rating Marquee',
    description:
      'A scroll-velocity press marquee for the homepage: publication logos beside a store-wide star rating and review count for instant credibility.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'trust',
    tags: ['section', 'social-proof', 'trust', 'marquee', 'index'],
    spec: {
      type: 'theme.section',
      name: 'As Seen In — Press & Rating Marquee',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'social-proof',
        activation: 'section',
        title: 'As seen in',
        subtitle: 'Rated 4.9/5 by 8,000+ shoppers',
        layout: { layout: 'carousel' },
        fields: {
          marquee: true,
          scrollVelocityDriven: true,
          storeRating: 4.9,
          reviewCount: 8191,
          starColor: '#ffffff',
        },
        blocks: [
          { kind: 'logo', imageUrl: 'https://cdn.shopify.com/s/files/press/vogue.png', fields: { name: 'Vogue' } },
          { kind: 'logo', imageUrl: 'https://cdn.shopify.com/s/files/press/gq.png', fields: { name: 'GQ' } },
          { kind: 'logo', imageUrl: 'https://cdn.shopify.com/s/files/press/forbes.png', fields: { name: 'Forbes' } },
          { kind: 'logo', imageUrl: 'https://cdn.shopify.com/s/files/press/allure.png', fields: { name: 'Allure' } },
          { kind: 'logo', imageUrl: 'https://cdn.shopify.com/s/files/press/wired.png', fields: { name: 'Wired' } },
        ],
      },
      placement: { enabled_on: { templates: ['index'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'full', zIndex: 'base' },
        spacing: { padding: 'medium', margin: 'none', gap: 'loose', density: 'comfortable' },
        typography: { size: 'SM', weight: 'medium', lineHeight: 'normal', align: 'center' },
        colors: { text: '#f5f5f5', background: '#111111', overlayBackdropOpacity: 0.45, seed: '#f5a623' },
        shape: { radius: 'none', borderWidth: 'none', shadow: 'none', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'slow', easing: 'standard' },
        pack: 'bold',
      },
    },
  },
  {
    id: 'NSEC-TEST-10',
    name: 'Collection Social Proof — Rating Row',
    description:
      'A trust strip for the collection page pairing a store-wide star rating with three short verified quotes to reassure shoppers while they browse.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'reviews',
    tags: ['section', 'reviews', 'social-proof', 'trust', 'collection'],
    spec: {
      type: 'theme.section',
      name: 'Collection Social Proof — Rating Row',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'social-proof',
        activation: 'section',
        title: 'Why shoppers choose us',
        subtitle: '4.8/5 across 3,900+ verified reviews',
        layout: { layout: 'grid', columns: 3 },
        fields: {
          storeRating: 4.8,
          reviewCount: 3912,
          showStars: true,
          showVerifiedBadge: true,
          starColor: '#111111',
        },
        blocks: [
          {
            kind: 'review-card',
            text: 'Every order has been flawless. I never shop elsewhere anymore.',
            fields: { author: 'Cora M.', rating: 5, verified: true },
          },
          {
            kind: 'review-card',
            text: 'Fast delivery, easy returns, and quality that lasts.',
            fields: { author: 'Dane P.', rating: 5, verified: true },
          },
          {
            kind: 'review-card',
            text: 'The whole range is beautifully made. Hard to pick a favorite.',
            fields: { author: 'Elle R.', rating: 4, verified: true },
          },
        ],
      },
      placement: { enabled_on: { templates: ['collection'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'medium', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: 'MD', weight: 'normal', lineHeight: 'normal', align: 'center' },
        colors: { seed: '#8a7f6d', overlayBackdropOpacity: 0.45 },
        shape: { radius: 'md', borderWidth: 'thin', shadow: 'none', elevation: 'border' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        pack: 'luxe',
      },
    },
  },

  // 11 — V-A A4: Loox-style scroll-snap review carousel. Rich blocks (avatarUrl +
  // authorTitle + half-star ratings + verified) trip the carousel upgrade in the
  // storefront/preview renderer; the static grid is untouched for specs without them.
  {
    id: 'NSEC-TEST-11',
    name: 'Review Carousel — Rated Cards (Loox-style)',
    description: 'Swipeable scroll-snap carousel of verified photo reviews with reviewer avatars, half-star precision ratings, and a verified-buyer chip — the Loox/Judge.me "Cards" slider for the product page.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'reviews',
    tags: ['section', 'reviews', 'social-proof', 'carousel', 'ratings', 'product'],
    spec: {
      type: 'theme.section',
      name: 'Review Carousel — Rated Cards',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'reviews',
        activation: 'section',
        title: 'What buyers are saying',
        subtitle: 'Verified reviews from real customers',
        layout: { layout: 'carousel' },
        fields: { reviewsPerRowDesktop: 3, reviewsPerRowMobile: 1, showVerifiedBadge: true, showReviewerAvatar: true },
        blocks: [
          { kind: 'review-card', text: 'Exactly as pictured and even better in person. The quality blew me away.', fields: { author: 'Maya R.', authorTitle: 'Verified buyer', rating: 5, verified: true, avatarUrl: 'https://cdn.shopify.com/s/files/avatars/maya.jpg' } },
          { kind: 'review-card', text: 'Fast shipping and beautiful packaging. Would happily order again.', fields: { author: 'Devon K.', authorTitle: 'Denver, CO', rating: 4.5, verified: true, avatarUrl: 'https://cdn.shopify.com/s/files/avatars/devon.jpg' } },
          { kind: 'review-card', text: 'Held up after a month of daily use — genuinely my new favorite.', fields: { author: 'Priya S.', authorTitle: 'Repeat customer', rating: 5, verified: true, avatarUrl: 'https://cdn.shopify.com/s/files/avatars/priya.jpg' } },
          { kind: 'review-card', text: 'Great value for the price. Docked half a star only because I wanted more colors.', fields: { author: 'Jordan M.', authorTitle: 'Miami, FL', rating: 4.5, verified: true } },
          { kind: 'review-card', text: 'Customer service was fantastic when I had a question. Five stars.', fields: { author: 'Sam T.', authorTitle: 'Verified buyer', rating: 5, verified: true, avatarUrl: 'https://cdn.shopify.com/s/files/avatars/sam.jpg' } },
        ],
      },
      placement: { enabled_on: { templates: ['product', 'index'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: 'MD', weight: 'normal', lineHeight: 'normal', align: 'left' },
        colors: { overlayBackdropOpacity: 0.45, seed: '#f5a623' },
        shape: { radius: 'lg', borderWidth: 'thin', shadow: 'sm', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'base', easing: 'standard' },
        pack: 'bold',
      },
    },
  },

  // 12 — V-A A4: minimal-luxe founder-story quotes carousel (initials avatars, no photos).
  {
    id: 'NSEC-TEST-12',
    name: 'Founder Story Quotes — Minimal Carousel',
    description: 'Quiet, editorial scroll-snap carousel of founder and team quotes with initials-avatar chips and role titles — a minimal-luxe "in their words" strip with no review photos.',
    category: 'STOREFRONT_UI',
    type: 'theme.section',
    icon: 'reviews',
    tags: ['section', 'testimonials', 'quotes', 'carousel', 'founder', 'editorial'],
    spec: {
      type: 'theme.section',
      name: 'Founder Story Quotes',
      category: 'STOREFRONT_UI',
      requires: ['THEME_ASSETS'],
      config: {
        kind: 'testimonials',
        activation: 'section',
        title: 'In their words',
        subtitle: 'From the people who make it',
        layout: { layout: 'carousel' },
        fields: { showReviewerAvatar: true },
        blocks: [
          { kind: 'review-card', text: 'We started this in a garage with one sewing machine and a stubborn idea about quality.', fields: { author: 'Ana Ríos', authorTitle: 'Co-founder & CEO', rating: 5 } },
          { kind: 'review-card', text: 'Every material is chosen to last a decade, not a season. That is the whole philosophy.', fields: { author: 'Theo Lund', authorTitle: 'Head of Design', rating: 5 } },
          { kind: 'review-card', text: 'Our customers write to us like friends. That relationship is what we protect most.', fields: { author: 'Priya Anand', authorTitle: 'Head of Community', rating: 5 } },
        ],
      },
      placement: { enabled_on: { templates: ['page', 'index'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'airy' },
        typography: { size: 'LG', weight: 'normal', lineHeight: 'relaxed', align: 'left' },
        colors: { overlayBackdropOpacity: 0.45, seed: '#0f172a' },
        shape: { radius: 'sm', borderWidth: 'thin', shadow: 'none', elevation: 'border' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'slow', easing: 'enter' },
        pack: 'luxe',
      },
    },
  },
];
