import type { TemplateEntry } from '../types.js';

/**
 * POS — Customer & Cart surfaces (surface-coverage 034, unit "customer-and-cart", 20 templates).
 *
 * Every template is a `pos.extension` recipe scoped to the two assigned POS surfaces:
 *   - `pos.customer-details.*`         — the customer-detail screen (block + menu-item↔action).
 *   - `pos.cart.line-item-details.*`   — a selected cart line item (menu-item↔action).
 *
 * Grounded in the loyalty/wishlist/pricing corpus (Smile.io, BON, LoyaltyLion, Growave,
 * Swym Wishlist Plus, Bold Discounts, Bold Custom Pricing) — the real in-store behaviours
 * those apps expose at the POS counter: look up a customer's points/tier, accrue/redeem
 * loyalty, apply a wholesale/flash-sale line discount, stamp a note or property on the sale,
 * add a recommended add-on line, and forward the sale context to the app backend.
 *
 * HONESTY — authored ONLY against the current POS vocabulary (allowed-values.ts):
 *   - `loyalty.points` / `loyalty.tier` bindings and LOYALTY_READ / LOYALTY_WRITE actions
 *     are app-owned: they resolve through `appProxyPath` (the app proxy), NOT the inline POS
 *     API. Until that proxy resolves them they degrade to the block's literal `label` — these
 *     templates model that path honestly and never imply a guaranteed-live value.
 *   - `session.*` bindings expose IDs/currency ONLY (no staff/location NAMES — POS has none).
 *   - APPLY_LINE_DISCOUNT / ADD_CART_PROPERTY on a line context are used only on the
 *     `pos.cart.line-item-details.*` targets, where a `shopify.cartLineItem` exists.
 *   - menu-item↔action pairs use `presentation: 'MENUITEM_ACTION'`; a persistent info panel
 *     uses `blockKind: 'block'` + `presentation: 'STANDALONE'`.
 */
export const POS_CUSTOMER_AND_CART_TEMPLATES: TemplateEntry[] = [
  // ── pos.customer-details.block.render — persistent info panels (LOYALTY_READ / bindings) ──
  {
    id: 'POS-CUST-01',
    name: 'POS Loyalty Balance Panel',
    description: 'Shows the customer\'s live loyalty points balance on the POS customer-details screen, read from the app proxy.',
    category: 'ADMIN_UI',
    type: 'pos.extension',
    icon: 'pos',
    tags: ['pos', 'loyalty', 'points', 'customer', 'smile'],
    spec: {
      type: 'pos.extension',
      name: 'POS Loyalty Balance Panel',
      category: 'ADMIN_UI',
      requires: [],
      config: {
        target: 'pos.customer-details.block.render',
        label: 'Loyalty points',
        blockKind: 'block',
        presentation: 'STANDALONE',
        action: 'LOYALTY_READ',
        binding: 'loyalty.points',
        appProxyPath: '/loyalty/balance',
      },
    },
  },
  {
    id: 'POS-CUST-02',
    name: 'POS VIP Tier Panel',
    description: 'Displays the customer\'s VIP tier on the POS customer-details screen so staff can honor tier perks in-store.',
    category: 'ADMIN_UI',
    type: 'pos.extension',
    icon: 'pos',
    tags: ['pos', 'loyalty', 'vip', 'tier', 'bon-loyalty'],
    spec: {
      type: 'pos.extension',
      name: 'POS VIP Tier Panel',
      category: 'ADMIN_UI',
      requires: [],
      config: {
        target: 'pos.customer-details.block.render',
        label: 'VIP tier',
        blockKind: 'block',
        presentation: 'STANDALONE',
        action: 'LOYALTY_READ',
        binding: 'loyalty.tier',
        appProxyPath: '/loyalty/tier',
      },
    },
  },
  {
    id: 'POS-CUST-03',
    name: 'POS Wishlist Lookup Panel',
    description: 'Surfaces the customer\'s saved wishlist on the POS customer-details screen so staff can pull items in-store.',
    category: 'ADMIN_UI',
    type: 'pos.extension',
    icon: 'pos',
    tags: ['pos', 'wishlist', 'customer', 'swym', 'lookup'],
    spec: {
      type: 'pos.extension',
      name: 'POS Wishlist Lookup Panel',
      category: 'ADMIN_UI',
      requires: [],
      config: {
        target: 'pos.customer-details.block.render',
        label: 'Saved wishlist',
        blockKind: 'block',
        presentation: 'STANDALONE',
        action: 'APP_PROXY_POST',
        appProxyPath: '/wishlist/lookup',
      },
    },
  },
  {
    id: 'POS-CUST-04',
    name: 'POS Wholesale Tier Panel',
    description: 'Shows the customer\'s wholesale/B2B pricing tier on the POS customer-details screen so staff apply the right price.',
    category: 'ADMIN_UI',
    type: 'pos.extension',
    icon: 'pos',
    tags: ['pos', 'wholesale', 'b2b', 'pricing', 'bold-custom-pricing'],
    spec: {
      type: 'pos.extension',
      name: 'POS Wholesale Tier Panel',
      category: 'ADMIN_UI',
      requires: [],
      config: {
        target: 'pos.customer-details.block.render',
        label: 'Wholesale tier',
        blockKind: 'block',
        presentation: 'STANDALONE',
        action: 'APP_PROXY_POST',
        appProxyPath: '/pricing/customer-tier',
      },
    },
  },
  {
    id: 'POS-CUST-05',
    name: 'POS Store Credit Panel',
    description: 'Displays the customer\'s available store-credit balance on the POS customer-details screen, read from the app proxy.',
    category: 'ADMIN_UI',
    type: 'pos.extension',
    icon: 'pos',
    tags: ['pos', 'store-credit', 'loyalty', 'customer', 'growave'],
    spec: {
      type: 'pos.extension',
      name: 'POS Store Credit Panel',
      category: 'ADMIN_UI',
      requires: [],
      config: {
        target: 'pos.customer-details.block.render',
        label: 'Store credit',
        blockKind: 'block',
        presentation: 'STANDALONE',
        action: 'LOYALTY_READ',
        binding: 'loyalty.points',
        appProxyPath: '/store-credit/balance',
      },
    },
  },

  // ── pos.customer-details.action.menu-item + action.render — customer-scoped actions ──
  {
    id: 'POS-CUST-06',
    name: 'POS Enroll in Loyalty',
    description: 'Adds a customer-details menu action that enrolls the walk-in customer into the loyalty program via the app proxy.',
    category: 'ADMIN_UI',
    type: 'pos.extension',
    icon: 'pos',
    tags: ['pos', 'loyalty', 'enroll', 'customer', 'smile'],
    spec: {
      type: 'pos.extension',
      name: 'POS Enroll in Loyalty',
      category: 'ADMIN_UI',
      requires: [],
      config: {
        target: 'pos.customer-details.action.menu-item.render',
        label: 'Enroll in loyalty',
        blockKind: 'action',
        presentation: 'MENUITEM_ACTION',
        action: 'LOYALTY_WRITE',
        appProxyPath: '/loyalty/enroll',
      },
    },
  },
  {
    id: 'POS-CUST-07',
    name: 'POS Redeem Points for Cart Discount',
    description: 'Customer-details action that redeems loyalty points and applies the resulting cart discount at the POS counter.',
    category: 'ADMIN_UI',
    type: 'pos.extension',
    icon: 'pos',
    tags: ['pos', 'loyalty', 'redeem', 'discount', 'loyaltylion'],
    spec: {
      type: 'pos.extension',
      name: 'POS Redeem Points for Cart Discount',
      category: 'ADMIN_UI',
      requires: [],
      config: {
        target: 'pos.customer-details.action.render',
        label: 'Redeem points',
        blockKind: 'action',
        presentation: 'MENUITEM_ACTION',
        action: 'APPLY_CART_DISCOUNT',
        binding: 'loyalty.points',
        appProxyPath: '/loyalty/redeem',
        staffPin: { required: true, reason: 'Loyalty redemption applies a discount to the sale.' },
        actionConfig: {
          discountTitle: 'Loyalty reward',
          discountKind: 'FixedAmount',
          discountAmount: '5.00',
        },
      },
    },
  },
  {
    id: 'POS-CUST-08',
    name: 'POS Apply VIP Member Discount',
    description: 'Customer-details action that applies the customer\'s VIP-tier percentage discount to the cart, gated by a staff PIN.',
    category: 'ADMIN_UI',
    type: 'pos.extension',
    icon: 'pos',
    tags: ['pos', 'vip', 'discount', 'loyalty', 'bon-loyalty'],
    spec: {
      type: 'pos.extension',
      name: 'POS Apply VIP Member Discount',
      category: 'ADMIN_UI',
      requires: [],
      config: {
        target: 'pos.customer-details.action.render',
        label: 'Apply VIP discount',
        blockKind: 'action',
        presentation: 'MENUITEM_ACTION',
        action: 'APPLY_CART_DISCOUNT',
        binding: 'loyalty.tier',
        appProxyPath: '/loyalty/vip-discount',
        staffPin: { required: true, reason: 'VIP discounts affect the sale total.' },
        actionConfig: {
          discountTitle: 'VIP member',
          discountKind: 'Percentage',
          discountAmount: '10',
        },
      },
    },
  },
  {
    id: 'POS-CUST-09',
    name: 'POS Apply Wholesale Code',
    description: 'Customer-details action that applies the customer\'s wholesale discount code to the cart at POS.',
    category: 'ADMIN_UI',
    type: 'pos.extension',
    icon: 'pos',
    tags: ['pos', 'wholesale', 'b2b', 'discount-code', 'bold-custom-pricing'],
    spec: {
      type: 'pos.extension',
      name: 'POS Apply Wholesale Code',
      category: 'ADMIN_UI',
      requires: [],
      config: {
        target: 'pos.customer-details.action.render',
        label: 'Apply wholesale price',
        blockKind: 'action',
        presentation: 'MENUITEM_ACTION',
        action: 'APPLY_CODE_DISCOUNT',
        staffPin: { required: true, reason: 'Wholesale pricing is restricted to approved accounts.' },
        actionConfig: {
          discountCode: 'WHOLESALE',
        },
      },
    },
  },
  {
    id: 'POS-CUST-10',
    name: 'POS Tag Customer Note',
    description: 'Customer-details action that writes a staff note onto the cart, e.g. a wholesale account or VIP flag for the sale.',
    category: 'ADMIN_UI',
    type: 'pos.extension',
    icon: 'pos',
    tags: ['pos', 'customer', 'note', 'cart', 'bold-custom-pricing'],
    spec: {
      type: 'pos.extension',
      name: 'POS Tag Customer Note',
      category: 'ADMIN_UI',
      requires: [],
      config: {
        target: 'pos.customer-details.action.render',
        label: 'Add account note',
        blockKind: 'action',
        presentation: 'MENUITEM_ACTION',
        action: 'SET_CART_NOTE',
        actionConfig: {
          note: 'Wholesale account — verify tier before checkout.',
        },
      },
    },
  },
  {
    id: 'POS-CUST-11',
    name: 'POS Capture Wishlist Email',
    description: 'Customer-details action that captures the walk-in customer\'s email into their wishlist/marketing list via the app proxy.',
    category: 'ADMIN_UI',
    type: 'pos.extension',
    icon: 'pos',
    tags: ['pos', 'wishlist', 'email', 'customer', 'swym'],
    spec: {
      type: 'pos.extension',
      name: 'POS Capture Wishlist Email',
      category: 'ADMIN_UI',
      requires: [],
      config: {
        target: 'pos.customer-details.action.render',
        label: 'Save to wishlist',
        blockKind: 'action',
        presentation: 'MENUITEM_ACTION',
        action: 'APP_PROXY_POST',
        appProxyPath: '/wishlist/capture-email',
      },
    },
  },
  {
    id: 'POS-CUST-12',
    name: 'POS Award Bonus Points',
    description: 'Customer-details action that credits manual bonus loyalty points to the customer ledger via the app proxy, PIN-gated.',
    category: 'ADMIN_UI',
    type: 'pos.extension',
    icon: 'pos',
    tags: ['pos', 'loyalty', 'points', 'bonus', 'growave'],
    spec: {
      type: 'pos.extension',
      name: 'POS Award Bonus Points',
      category: 'ADMIN_UI',
      requires: [],
      config: {
        target: 'pos.customer-details.action.render',
        label: 'Award bonus points',
        blockKind: 'action',
        presentation: 'MENUITEM_ACTION',
        action: 'LOYALTY_WRITE',
        binding: 'loyalty.points',
        appProxyPath: '/loyalty/award',
        staffPin: { required: true, reason: 'Manual point adjustments change the customer balance.' },
      },
    },
  },
  {
    id: 'POS-CUST-13',
    name: 'POS Send Referral Link',
    description: 'Customer-details action that emails the customer their loyalty referral link via the app proxy.',
    category: 'ADMIN_UI',
    type: 'pos.extension',
    icon: 'pos',
    tags: ['pos', 'loyalty', 'referral', 'customer', 'smile'],
    spec: {
      type: 'pos.extension',
      name: 'POS Send Referral Link',
      category: 'ADMIN_UI',
      requires: [],
      config: {
        target: 'pos.customer-details.action.render',
        label: 'Send referral link',
        blockKind: 'action',
        presentation: 'MENUITEM_ACTION',
        action: 'APP_PROXY_POST',
        appProxyPath: '/loyalty/referral-link',
      },
    },
  },
  {
    id: 'POS-CUST-14',
    name: 'POS Enroll Menu Item',
    description: 'Customer-details menu-item entry that opens the loyalty enrollment action for a non-member walk-in.',
    category: 'ADMIN_UI',
    type: 'pos.extension',
    icon: 'pos',
    tags: ['pos', 'loyalty', 'enroll', 'menu-item', 'bon-loyalty'],
    spec: {
      type: 'pos.extension',
      name: 'POS Enroll Menu Item',
      category: 'ADMIN_UI',
      requires: [],
      config: {
        target: 'pos.customer-details.action.menu-item.render',
        label: 'Join rewards',
        blockKind: 'action',
        presentation: 'MENUITEM_ACTION',
        action: 'PRESENT_MODAL',
      },
    },
  },
  {
    id: 'POS-CUST-15',
    name: 'POS Loyalty Actions Menu Item',
    description: 'Customer-details menu-item entry that opens the loyalty redeem/award action sheet at the POS counter.',
    category: 'ADMIN_UI',
    type: 'pos.extension',
    icon: 'pos',
    tags: ['pos', 'loyalty', 'menu-item', 'redeem', 'loyaltylion'],
    spec: {
      type: 'pos.extension',
      name: 'POS Loyalty Actions Menu Item',
      category: 'ADMIN_UI',
      requires: [],
      config: {
        target: 'pos.customer-details.action.menu-item.render',
        label: 'Loyalty actions',
        blockKind: 'action',
        presentation: 'MENUITEM_ACTION',
        action: 'PRESENT_MODAL',
      },
    },
  },

  // ── pos.cart.line-item-details.* — selected cart line actions (line-item context) ──
  {
    id: 'POS-CUST-16',
    name: 'POS Line Wholesale Discount',
    description: 'Cart line-item action that applies the wholesale percentage discount to the selected line, gated by a staff PIN.',
    category: 'ADMIN_UI',
    type: 'pos.extension',
    icon: 'pos',
    tags: ['pos', 'wholesale', 'line-discount', 'cart', 'bold-custom-pricing'],
    spec: {
      type: 'pos.extension',
      name: 'POS Line Wholesale Discount',
      category: 'ADMIN_UI',
      requires: [],
      config: {
        target: 'pos.cart.line-item-details.action.render',
        label: 'Wholesale price',
        blockKind: 'action',
        presentation: 'MENUITEM_ACTION',
        action: 'APPLY_LINE_DISCOUNT',
        binding: 'lineItem.title',
        staffPin: { required: true, reason: 'Wholesale line pricing is restricted to approved accounts.' },
        actionConfig: {
          discountTitle: 'Wholesale',
          discountKind: 'Percentage',
          discountAmount: '15',
        },
      },
    },
  },
  {
    id: 'POS-CUST-17',
    name: 'POS Line Flash-Sale Discount',
    description: 'Cart line-item action that applies a flash-sale fixed-amount discount to the selected line at POS.',
    category: 'ADMIN_UI',
    type: 'pos.extension',
    icon: 'pos',
    tags: ['pos', 'flash-sale', 'line-discount', 'cart', 'bold-discounts'],
    spec: {
      type: 'pos.extension',
      name: 'POS Line Flash-Sale Discount',
      category: 'ADMIN_UI',
      requires: [],
      config: {
        target: 'pos.cart.line-item-details.action.render',
        label: 'Flash sale price',
        blockKind: 'action',
        presentation: 'MENUITEM_ACTION',
        action: 'APPLY_LINE_DISCOUNT',
        binding: 'lineItem.title',
        staffPin: { required: true, reason: 'Sale pricing changes the line total.' },
        actionConfig: {
          discountTitle: 'Flash sale',
          discountKind: 'FixedAmount',
          discountAmount: '5.00',
        },
      },
    },
  },
  {
    id: 'POS-CUST-18',
    name: 'POS Line Gift Note',
    description: 'Cart line-item action that stamps a gift-message property onto the selected line for the sale.',
    category: 'ADMIN_UI',
    type: 'pos.extension',
    icon: 'pos',
    tags: ['pos', 'gift', 'line-property', 'cart', 'note'],
    spec: {
      type: 'pos.extension',
      name: 'POS Line Gift Note',
      category: 'ADMIN_UI',
      requires: [],
      config: {
        target: 'pos.cart.line-item-details.action.render',
        label: 'Add gift note',
        blockKind: 'action',
        presentation: 'MENUITEM_ACTION',
        action: 'ADD_CART_PROPERTY',
        binding: 'lineItem.title',
        actionConfig: {
          propertyKey: 'Gift note',
          propertyValue: 'Gift — please omit price on receipt.',
        },
      },
    },
  },
  {
    id: 'POS-CUST-19',
    name: 'POS Line Add Recommended Add-On',
    description: 'Cart line-item action that adds a recommended cross-sell add-on line for the selected product at POS.',
    category: 'ADMIN_UI',
    type: 'pos.extension',
    icon: 'pos',
    tags: ['pos', 'cross-sell', 'add-on', 'cart', 'line-item'],
    spec: {
      type: 'pos.extension',
      name: 'POS Line Add Recommended Add-On',
      category: 'ADMIN_UI',
      requires: [],
      config: {
        target: 'pos.cart.line-item-details.action.render',
        label: 'Add recommended add-on',
        blockKind: 'action',
        presentation: 'MENUITEM_ACTION',
        action: 'ADD_LINE_ITEM',
        binding: 'lineItem.title',
        actionConfig: {
          productVariantId: 'gid://shopify/ProductVariant/40000000000001',
        },
      },
    },
  },
  {
    id: 'POS-CUST-20',
    name: 'POS Line Discount Menu Item',
    description: 'Cart line-item menu-item entry that opens the line-discount action sheet for the selected line at POS.',
    category: 'ADMIN_UI',
    type: 'pos.extension',
    icon: 'pos',
    tags: ['pos', 'line-discount', 'menu-item', 'cart', 'bold-discounts'],
    spec: {
      type: 'pos.extension',
      name: 'POS Line Discount Menu Item',
      category: 'ADMIN_UI',
      requires: [],
      config: {
        target: 'pos.cart.line-item-details.action.menu-item.render',
        label: 'Discount this line',
        blockKind: 'action',
        presentation: 'MENUITEM_ACTION',
        action: 'PRESENT_MODAL',
        binding: 'lineItem.title',
      },
    },
  },
];
