import type { TemplateEntry } from '../types.js';
import { THEME_PLACEABLE_TEMPLATES } from '../../allowed-values.js';

/**
 * proxy.widget module templates — app-proxy served, shopper-scoped storefront + order
 * surfaces. Every entry compiles the `proxy.widget` RecipeSpec member (recipe.ts):
 * an app-proxy fragment (`surface: 'embed'`) or a standalone routed page
 * (`surface: 'full_page'`, layout:false) served under `/apps/<proxySubpath>`.
 *
 * These reflect the REAL surfaces the corpus apps route through an app proxy —
 * dynamic, per-shopper content that pure Liquid cannot render:
 *  - Swym Wishlist Plus  → the hosted wishlist page / pop-up (regid/email-scoped list).
 *  - Recharge / Loop     → the standalone customer subscription portal (magic-link).
 *  - Rebuy / Selleasy    → client-hydrated recommendation carousels served from a backend.
 *  - LoyaltyLion / Okendo→ the floating loyalty/points hub + rewards portal.
 *  - Loox                → dynamic review data (fetch/sort/filter/paginate) + submission.
 *  - ProveSource         → live-visitor / recent-order social-proof toast.
 *  - order-tracking      → a self-serve "where is my order" lookup page.
 *
 * HONESTY: the app-proxy loader is the strongest evaluation site (authenticated
 * customer + cart), but shopper-scoped balances/lists/contracts only populate once
 * the proxy backend for that domain is provisioned. These templates ship the
 * declarative widget + placement + display rules; they do NOT imply guaranteed-live
 * per-shopper data before the proxy endpoint exists — the widget renders its
 * empty/sign-in state until then. No fabricated data.
 */
export const PROXY_WIDGET_STOREFRONT_AND_ORDER_TEMPLATES: TemplateEntry[] = [
  // ── Wishlist (Swym Wishlist Plus) ──────────────────────────────────────────
  {
    id: 'PXY-MOD-01',
    name: 'Wishlist Page (Hosted)',
    description: 'Standalone wishlist page served under /apps/wishlist — a shopper-scoped product grid with remove + add-to-cart, rendered from the app proxy so guest and logged-in lists sync across devices.',
    category: 'STOREFRONT_UI',
    type: 'proxy.widget',
    icon: 'wishlist',
    tags: ['swym', 'wishlist', 'full-page', 'proxy', 'account', 'save-for-later'],
    spec: {
      type: 'proxy.widget',
      name: 'Wishlist Page (Hosted)',
      category: 'STOREFRONT_UI',
      requires: ['APP_PROXY'],
      config: {
        widgetId: 'swym-wishlist-page',
        mode: 'HTML',
        surface: 'full_page',
        proxySubpath: 'wishlist',
        title: 'My Wishlist',
        message: 'Everything you have saved, in one place. Sign in to sync your list across every device.',
      },
      placement: { enabled_on: { templates: ['page', 'index'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: 'LG', weight: 'bold', lineHeight: 'normal', align: 'left' },
        colors: { text: '#111827', background: '#ffffff', buttonBg: '#111827', buttonText: '#ffffff', overlayBackdropOpacity: 0.45, seed: '#e11d48' },
        shape: { radius: 'lg', borderWidth: 'thin', shadow: 'sm', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
      },
    },
  },
  {
    id: 'PXY-MOD-02',
    name: 'Wishlist Drawer Pop-up',
    description: 'Embeddable wishlist pop-up fragment the floating heart launcher opens — a shopper-scoped saved-items drawer with live counter, served from the app proxy so it hydrates the current shopper list without a page reload.',
    category: 'STOREFRONT_UI',
    type: 'proxy.widget',
    icon: 'wishlist',
    tags: ['swym', 'wishlist', 'popup', 'proxy', 'drawer', 'overlay'],
    spec: {
      type: 'proxy.widget',
      name: 'Wishlist Drawer Pop-up',
      category: 'STOREFRONT_UI',
      requires: ['APP_PROXY'],
      config: {
        widgetId: 'swym-wishlist-drawer',
        mode: 'HTML',
        surface: 'embed',
        title: 'Saved items',
        message: 'Tap the heart to save products for later.',
      },
      placement: { enabled_on: { templates: ['product', 'collection', 'index'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'overlay', anchor: 'right', offsetX: 0, offsetY: 0, width: 'narrow', zIndex: 'modal' },
        spacing: { padding: 'medium', margin: 'none', gap: 'tight', density: 'comfortable' },
        typography: { size: 'MD', weight: 'medium', lineHeight: 'normal', align: 'left' },
        colors: { text: '#111827', background: '#ffffff', buttonBg: '#e11d48', buttonText: '#ffffff', overlayBackdrop: '#000000', overlayBackdropOpacity: 0.5, seed: '#e11d48' },
        shape: { radius: 'md', borderWidth: 'none', shadow: 'lg', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
      },
    },
  },
  {
    id: 'PXY-MOD-03',
    name: 'Shared Wishlist / Registry Page',
    description: 'Public shareable wishlist page under /apps/wishlist-shared — renders a read-only registry list from a share token so gifters can view and buy, served from the app proxy so the list resolves per share link.',
    category: 'STOREFRONT_UI',
    type: 'proxy.widget',
    icon: 'wishlist',
    tags: ['swym', 'wishlist', 'registry', 'full-page', 'proxy', 'share'],
    spec: {
      type: 'proxy.widget',
      name: 'Shared Wishlist / Registry Page',
      category: 'STOREFRONT_UI',
      requires: ['APP_PROXY'],
      config: {
        widgetId: 'swym-wishlist-shared',
        mode: 'HTML',
        surface: 'full_page',
        proxySubpath: 'wishlist-shared',
        title: 'A wishlist shared with you',
        message: 'Pick something from their saved items — purchases update the list automatically.',
      },
      placement: { enabled_on: { templates: ['page'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: 'LG', weight: 'bold', lineHeight: 'normal', align: 'center' },
        colors: { text: '#111827', background: '#fdf2f8', buttonBg: '#e11d48', buttonText: '#ffffff', overlayBackdropOpacity: 0.45, seed: '#e11d48' },
        shape: { radius: 'lg', borderWidth: 'none', shadow: 'sm', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
      },
    },
  },

  // ── Order tracking ─────────────────────────────────────────────────────────
  {
    id: 'PXY-MOD-04',
    name: 'Order Tracking Page',
    description: 'Self-serve "where is my order" page under /apps/track — shopper enters order number + email and the app-proxy loader returns fulfillment status and tracking, rendered without the theme layout as a first-class store page.',
    category: 'STOREFRONT_UI',
    type: 'proxy.widget',
    icon: 'shipping',
    tags: ['order-tracking', 'full-page', 'proxy', 'fulfillment', 'wismo', 'support'],
    spec: {
      type: 'proxy.widget',
      name: 'Order Tracking Page',
      category: 'STOREFRONT_UI',
      requires: ['APP_PROXY'],
      config: {
        widgetId: 'order-tracking-page',
        mode: 'HTML',
        surface: 'full_page',
        proxySubpath: 'track',
        title: 'Track your order',
        message: 'Enter your order number and email to see the latest shipping status.',
      },
      placement: { enabled_on: { templates: ['page'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'narrow', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: 'LG', weight: 'bold', lineHeight: 'normal', align: 'left' },
        colors: { text: '#0f172a', background: '#ffffff', buttonBg: '#2563eb', buttonText: '#ffffff', overlayBackdropOpacity: 0.45, seed: '#2563eb' },
        shape: { radius: 'md', borderWidth: 'thin', shadow: 'sm', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
      },
    },
  },
  {
    id: 'PXY-MOD-05',
    name: 'Order Status Tracker (JSON)',
    description: 'JSON app-proxy endpoint a storefront tracker fetches for live fulfillment + tracking-number data, returning shopper-scoped order status the theme renders into a progress timeline.',
    category: 'STOREFRONT_UI',
    type: 'proxy.widget',
    icon: 'shipping',
    tags: ['order-tracking', 'json', 'proxy', 'fulfillment', 'timeline', 'wismo'],
    spec: {
      type: 'proxy.widget',
      name: 'Order Status Tracker (JSON)',
      category: 'STOREFRONT_UI',
      requires: ['APP_PROXY'],
      config: {
        widgetId: 'order-status-json',
        mode: 'JSON',
        surface: 'embed',
        title: 'Order status feed',
        message: 'Serves order fulfillment + tracking status as JSON to a storefront tracker component.',
      },
      placement: { enabled_on: { templates: ['page', 'index'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'auto', zIndex: 'base' },
        spacing: { padding: 'none', margin: 'none', gap: 'none' },
        typography: { size: 'SM', weight: 'normal', lineHeight: 'normal', align: 'left' },
        colors: { text: '#0f172a', background: '#ffffff', overlayBackdropOpacity: 0.45 },
        shape: { radius: 'none', borderWidth: 'none', shadow: 'none' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
      },
    },
  },
  {
    id: 'PXY-MOD-06',
    name: 'Returns & Exchange Portal',
    description: 'Standalone returns page under /apps/returns — the shopper looks up an order and starts a return/exchange, served from the app proxy so it renders per-order eligibility as its own store page.',
    category: 'STOREFRONT_UI',
    type: 'proxy.widget',
    icon: 'shipping',
    tags: ['order-tracking', 'returns', 'full-page', 'proxy', 'exchange', 'support'],
    spec: {
      type: 'proxy.widget',
      name: 'Returns & Exchange Portal',
      category: 'STOREFRONT_UI',
      requires: ['APP_PROXY'],
      config: {
        widgetId: 'returns-portal',
        mode: 'HTML',
        surface: 'full_page',
        proxySubpath: 'returns',
        title: 'Start a return or exchange',
        message: 'Find your order to see what is eligible and choose a refund or exchange.',
      },
      placement: { enabled_on: { templates: ['page'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'narrow', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: 'LG', weight: 'bold', lineHeight: 'normal', align: 'left' },
        colors: { text: '#0f172a', background: '#ffffff', buttonBg: '#111827', buttonText: '#ffffff', overlayBackdropOpacity: 0.45, seed: '#0ea5e9' },
        shape: { radius: 'md', borderWidth: 'thin', shadow: 'sm', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
      },
    },
  },

  // ── Recommendations portal (Rebuy / Selleasy) ──────────────────────────────
  {
    id: 'PXY-MOD-07',
    name: 'PDP Cross-Sell Carousel (Rebuy)',
    description: 'Embeddable "you may also like" carousel on the product page — client-hydrated from the app proxy so the recommended set resolves per product and shopper, matching Rebuy\'s Data Source-driven cross-sell widget.',
    category: 'STOREFRONT_UI',
    type: 'proxy.widget',
    icon: 'upsell',
    tags: ['rebuy', 'recommendations', 'cross-sell', 'proxy', 'product', 'carousel'],
    spec: {
      type: 'proxy.widget',
      name: 'PDP Cross-Sell Carousel (Rebuy)',
      category: 'STOREFRONT_UI',
      requires: ['APP_PROXY'],
      config: {
        widgetId: 'rebuy-pdp-crosssell',
        mode: 'HTML',
        surface: 'embed',
        title: 'You may also like',
        message: 'Personalized picks based on this product and the current cart.',
        ruleEngine: {
          enabled: true,
          logic: 'AND',
          matchAction: 'SHOW',
          onUnresolved: 'defer',
          groups: [
            { logic: 'AND', conditions: [{ object: 'product', attribute: 'available', operator: 'equal_to', value: true }] },
          ],
        },
      },
      placement: { enabled_on: { templates: ['product'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'medium', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: 'LG', weight: 'bold', lineHeight: 'normal', align: 'left' },
        colors: { text: '#111827', background: '#ffffff', buttonBg: '#111827', buttonText: '#ffffff', overlayBackdropOpacity: 0.45, seed: '#7c3aed' },
        shape: { radius: 'lg', borderWidth: 'none', shadow: 'sm', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'base', easing: 'standard' },
      },
    },
  },
  {
    id: 'PXY-MOD-08',
    name: 'Cart Cross-Sell Recommendations (JSON)',
    description: 'JSON app-proxy feed a Smart-Cart drawer fetches for cart-derived cross-sell products, returning shopper- and cart-scoped recommendations the drawer renders inline — Rebuy\'s cart cross-sell pattern.',
    category: 'STOREFRONT_UI',
    type: 'proxy.widget',
    icon: 'upsell',
    tags: ['rebuy', 'recommendations', 'cart', 'json', 'proxy', 'cross-sell'],
    spec: {
      type: 'proxy.widget',
      name: 'Cart Cross-Sell Recommendations (JSON)',
      category: 'STOREFRONT_UI',
      requires: ['APP_PROXY'],
      config: {
        widgetId: 'rebuy-cart-recs-json',
        mode: 'JSON',
        surface: 'embed',
        title: 'Cart recommendations feed',
        message: 'Returns cart-derived cross-sell products as JSON for the cart drawer.',
      },
      placement: { enabled_on: { templates: ['cart', 'product', 'index'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'auto', zIndex: 'base' },
        spacing: { padding: 'none', margin: 'none', gap: 'none' },
        typography: { size: 'SM', weight: 'normal', lineHeight: 'normal', align: 'left' },
        colors: { text: '#111827', background: '#ffffff', overlayBackdropOpacity: 0.45 },
        shape: { radius: 'none', borderWidth: 'none', shadow: 'none' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
      },
    },
  },
  {
    id: 'PXY-MOD-09',
    name: 'Frequently Bought Together (Selleasy)',
    description: 'Embeddable Amazon-style "frequently bought together" row on the product page — served from the app proxy so the bundle set (manual, automatic, or metafield-sourced) resolves per product, matching Selleasy\'s FBT widget.',
    category: 'STOREFRONT_UI',
    type: 'proxy.widget',
    icon: 'upsell',
    tags: ['selleasy', 'recommendations', 'bundle', 'proxy', 'product', 'fbt'],
    spec: {
      type: 'proxy.widget',
      name: 'Frequently Bought Together (Selleasy)',
      category: 'STOREFRONT_UI',
      requires: ['APP_PROXY'],
      config: {
        widgetId: 'selleasy-fbt',
        mode: 'HTML',
        surface: 'embed',
        title: 'Frequently bought together',
        message: 'Add the set in one tap and save on the combined total.',
      },
      placement: { enabled_on: { templates: ['product'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'medium', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: 'MD', weight: 'bold', lineHeight: 'normal', align: 'left' },
        colors: { text: '#111827', background: '#f8fafc', buttonBg: '#f97316', buttonText: '#ffffff', overlayBackdropOpacity: 0.45, seed: '#f97316' },
        shape: { radius: 'md', borderWidth: 'thin', shadow: 'sm', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
      },
    },
  },
  {
    id: 'PXY-MOD-10',
    name: 'Recommendations Portal Page',
    description: 'Standalone "recommended for you" page under /apps/for-you — a full-page personalized product feed served from the app proxy, resolving per-shopper picks (recently viewed, buy-it-again) as a first-class store page.',
    category: 'STOREFRONT_UI',
    type: 'proxy.widget',
    icon: 'upsell',
    tags: ['rebuy', 'recommendations', 'full-page', 'proxy', 'personalized', 'portal'],
    spec: {
      type: 'proxy.widget',
      name: 'Recommendations Portal Page',
      category: 'STOREFRONT_UI',
      requires: ['APP_PROXY'],
      config: {
        widgetId: 'recs-portal-page',
        mode: 'HTML',
        surface: 'full_page',
        proxySubpath: 'for-you',
        title: 'Recommended for you',
        message: 'A personalized feed built from what you have viewed and bought before.',
        ruleEngine: {
          enabled: true,
          logic: 'AND',
          matchAction: 'SHOW',
          onUnresolved: 'defer',
          groups: [
            { logic: 'AND', conditions: [{ object: 'customer', attribute: 'loggedIn', operator: 'equal_to', value: true }] },
          ],
        },
      },
      placement: { enabled_on: { templates: ['page'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: 'XL', weight: 'bold', lineHeight: 'normal', align: 'left' },
        colors: { text: '#111827', background: '#ffffff', buttonBg: '#111827', buttonText: '#ffffff', overlayBackdropOpacity: 0.45, seed: '#7c3aed' },
        shape: { radius: 'lg', borderWidth: 'none', shadow: 'sm', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
      },
    },
  },

  // ── Reviews (Loox / Okendo) ────────────────────────────────────────────────
  {
    id: 'PXY-MOD-11',
    name: 'Product Reviews Widget (Loox)',
    description: 'Embeddable product-page reviews widget — server-hydrated from the app proxy so ratings, photos, sort, filter, and pagination load per product, matching Loox\'s dynamic review data surface.',
    category: 'STOREFRONT_UI',
    type: 'proxy.widget',
    icon: 'reviews',
    tags: ['loox', 'reviews', 'proxy', 'product', 'social-proof', 'ugc'],
    spec: {
      type: 'proxy.widget',
      name: 'Product Reviews Widget (Loox)',
      category: 'STOREFRONT_UI',
      requires: ['APP_PROXY'],
      config: {
        widgetId: 'loox-reviews-widget',
        mode: 'HTML',
        surface: 'embed',
        title: 'Customer reviews',
        message: 'Verified photo reviews, sortable and filterable, loaded for this product.',
      },
      placement: { enabled_on: { templates: ['product'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'medium', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: 'MD', weight: 'normal', lineHeight: 'normal', align: 'left' },
        colors: { text: '#111827', background: '#ffffff', buttonBg: '#111827', buttonText: '#ffffff', overlayBackdropOpacity: 0.45, seed: '#f5a623' },
        shape: { radius: 'md', borderWidth: 'thin', shadow: 'sm', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
      },
    },
  },
  {
    id: 'PXY-MOD-12',
    name: 'Review Submission Form (Loox)',
    description: 'Embeddable review-submission pop-up with photo/video upload — served from the app proxy so the form posts back to the reviews backend, matching Loox\'s write-a-review flow.',
    category: 'STOREFRONT_UI',
    type: 'proxy.widget',
    icon: 'reviews',
    tags: ['loox', 'reviews', 'proxy', 'popup', 'ugc', 'form'],
    spec: {
      type: 'proxy.widget',
      name: 'Review Submission Form (Loox)',
      category: 'STOREFRONT_UI',
      requires: ['APP_PROXY'],
      config: {
        widgetId: 'loox-review-form',
        mode: 'HTML',
        surface: 'embed',
        title: 'Write a review',
        message: 'Share your rating and add a photo or video of your purchase.',
      },
      placement: { enabled_on: { templates: ['product', 'page'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'overlay', anchor: 'center', offsetX: 0, offsetY: 0, width: 'narrow', zIndex: 'modal' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: 'MD', weight: 'medium', lineHeight: 'normal', align: 'left' },
        colors: { text: '#111827', background: '#ffffff', buttonBg: '#f5a623', buttonText: '#111827', overlayBackdrop: '#000000', overlayBackdropOpacity: 0.5, seed: '#f5a623' },
        shape: { radius: 'lg', borderWidth: 'none', shadow: 'lg', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
      },
    },
  },

  // ── Loyalty portal (LoyaltyLion / Okendo) ──────────────────────────────────
  {
    id: 'PXY-MOD-13',
    name: 'Loyalty Points Launcher',
    description: 'Floating loyalty launcher that opens the points hub — served from the app proxy so the logged-in shopper\'s balance and claimable rewards hydrate, matching LoyaltyLion\'s widget launcher.',
    category: 'STOREFRONT_UI',
    type: 'proxy.widget',
    icon: 'loyalty',
    tags: ['loyaltylion', 'loyalty', 'proxy', 'rewards', 'floating', 'points'],
    spec: {
      type: 'proxy.widget',
      name: 'Loyalty Points Launcher',
      category: 'STOREFRONT_UI',
      requires: ['APP_PROXY'],
      config: {
        widgetId: 'loyalty-launcher',
        mode: 'HTML',
        surface: 'embed',
        title: 'Rewards',
        message: 'See your points balance and the rewards you can claim.',
      },
      placement: { enabled_on: { templates: ['index', 'product', 'collection', 'cart', 'page'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'floating', anchor: 'bottom', offsetX: 24, offsetY: 24, width: 'auto', zIndex: 'sticky' },
        spacing: { padding: 'medium', margin: 'none', gap: 'tight', density: 'comfortable' },
        typography: { size: 'SM', weight: 'bold', lineHeight: 'normal', align: 'center' },
        colors: { text: '#ffffff', background: '#7c3aed', buttonBg: '#ffffff', buttonText: '#7c3aed', overlayBackdropOpacity: 0.45, seed: '#7c3aed' },
        shape: { radius: 'full', borderWidth: 'none', shadow: 'lg', elevation: 'glow' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'fast', easing: 'standard' },
      },
    },
  },
  {
    id: 'PXY-MOD-14',
    name: 'Rewards Portal Page',
    description: 'Full-page loyalty landing under /apps/rewards — ways-to-earn, rewards catalog, tier progress, and referral share, served from the app proxy so the member\'s ledger renders as its own store page.',
    category: 'STOREFRONT_UI',
    type: 'proxy.widget',
    icon: 'loyalty',
    tags: ['loyaltylion', 'loyalty', 'full-page', 'proxy', 'rewards', 'referral'],
    spec: {
      type: 'proxy.widget',
      name: 'Rewards Portal Page',
      category: 'STOREFRONT_UI',
      requires: ['APP_PROXY'],
      config: {
        widgetId: 'loyalty-portal-page',
        mode: 'HTML',
        surface: 'full_page',
        proxySubpath: 'rewards',
        title: 'Rewards program',
        message: 'Earn points, unlock tiers, and redeem rewards. Sign in to see your balance.',
      },
      placement: { enabled_on: { templates: ['page'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: 'XL', weight: 'bold', lineHeight: 'normal', align: 'center' },
        colors: { text: '#1e1b4b', background: '#faf5ff', buttonBg: '#7c3aed', buttonText: '#ffffff', overlayBackdropOpacity: 0.45, seed: '#7c3aed' },
        shape: { radius: 'lg', borderWidth: 'none', shadow: 'sm', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
      },
    },
  },
  {
    id: 'PXY-MOD-15',
    name: 'Points Balance Feed (JSON)',
    description: 'JSON app-proxy endpoint the storefront reads for the logged-in shopper\'s points balance and tier, returning per-member loyalty state a theme snippet renders inline. Degrades to a sign-in prompt for guests.',
    category: 'STOREFRONT_UI',
    type: 'proxy.widget',
    icon: 'loyalty',
    tags: ['loyaltylion', 'loyalty', 'json', 'proxy', 'points', 'balance'],
    spec: {
      type: 'proxy.widget',
      name: 'Points Balance Feed (JSON)',
      category: 'STOREFRONT_UI',
      requires: ['APP_PROXY'],
      config: {
        widgetId: 'loyalty-balance-json',
        mode: 'JSON',
        surface: 'embed',
        title: 'Points balance feed',
        message: 'Returns the shopper points balance and tier as JSON.',
      },
      placement: { enabled_on: { templates: ['index', 'product', 'page'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'auto', zIndex: 'base' },
        spacing: { padding: 'none', margin: 'none', gap: 'none' },
        typography: { size: 'SM', weight: 'normal', lineHeight: 'normal', align: 'left' },
        colors: { text: '#1e1b4b', background: '#ffffff', overlayBackdropOpacity: 0.45 },
        shape: { radius: 'none', borderWidth: 'none', shadow: 'none' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
      },
    },
  },

  // ── Subscription portal (Recharge / Loop) ──────────────────────────────────
  {
    id: 'PXY-MOD-16',
    name: 'Subscription Customer Portal',
    description: 'Standalone subscription portal under /apps/subscriptions — entered via magic link, listing active subscriptions with skip / swap / reschedule / pause actions, served from the app proxy as its own store page (Recharge / Loop pattern).',
    category: 'STOREFRONT_UI',
    type: 'proxy.widget',
    icon: 'subscriptions',
    tags: ['recharge', 'subscriptions', 'full-page', 'proxy', 'portal', 'loop'],
    spec: {
      type: 'proxy.widget',
      name: 'Subscription Customer Portal',
      category: 'STOREFRONT_UI',
      requires: ['APP_PROXY'],
      config: {
        widgetId: 'subscription-portal',
        mode: 'HTML',
        surface: 'full_page',
        proxySubpath: 'subscriptions',
        title: 'Manage your subscriptions',
        message: 'Skip, swap, reschedule, or pause upcoming deliveries. Open the link from your email to sign in.',
      },
      placement: { enabled_on: { templates: ['page'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'loose', margin: 'none', gap: 'medium', density: 'comfortable' },
        typography: { size: 'LG', weight: 'bold', lineHeight: 'normal', align: 'left' },
        colors: { text: '#0f172a', background: '#ffffff', buttonBg: '#0f766e', buttonText: '#ffffff', overlayBackdropOpacity: 0.45, seed: '#0f766e' },
        shape: { radius: 'lg', borderWidth: 'thin', shadow: 'sm', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
      },
    },
  },
  {
    id: 'PXY-MOD-17',
    name: 'Upcoming Deliveries Feed (JSON)',
    description: 'JSON app-proxy feed the storefront reads for a subscriber\'s next charge date and upcoming line items, returning per-shopper subscription schedule data a theme snippet renders. Degrades to sign-in for non-subscribers.',
    category: 'STOREFRONT_UI',
    type: 'proxy.widget',
    icon: 'subscriptions',
    tags: ['recharge', 'subscriptions', 'json', 'proxy', 'schedule', 'deliveries'],
    spec: {
      type: 'proxy.widget',
      name: 'Upcoming Deliveries Feed (JSON)',
      category: 'STOREFRONT_UI',
      requires: ['APP_PROXY'],
      config: {
        widgetId: 'subscription-schedule-json',
        mode: 'JSON',
        surface: 'embed',
        title: 'Upcoming deliveries feed',
        message: 'Returns the subscriber next-charge date and upcoming items as JSON.',
      },
      placement: { enabled_on: { templates: ['page', 'index'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'auto', zIndex: 'base' },
        spacing: { padding: 'none', margin: 'none', gap: 'none' },
        typography: { size: 'SM', weight: 'normal', lineHeight: 'normal', align: 'left' },
        colors: { text: '#0f172a', background: '#ffffff', overlayBackdropOpacity: 0.45 },
        shape: { radius: 'none', borderWidth: 'none', shadow: 'none' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
      },
    },
  },

  // ── Social proof (ProveSource) + back-in-stock (Appikon) ────────────────────
  {
    id: 'PXY-MOD-18',
    name: 'Live Social-Proof Toast (ProveSource)',
    description: 'Floating recent-order / live-visitor social-proof toast — served from the app proxy so it streams real recent-purchase and visitor-count events, matching ProveSource\'s corner popup.',
    category: 'STOREFRONT_UI',
    type: 'proxy.widget',
    icon: 'social-proof',
    tags: ['provesource', 'social-proof', 'proxy', 'toast', 'floating', 'urgency'],
    spec: {
      type: 'proxy.widget',
      name: 'Live Social-Proof Toast (ProveSource)',
      category: 'STOREFRONT_UI',
      requires: ['APP_PROXY'],
      config: {
        widgetId: 'provesource-toast',
        mode: 'HTML',
        surface: 'embed',
        title: 'Recent activity',
        message: 'Streams recent orders and live-visitor counts from the store event feed.',
      },
      placement: { enabled_on: { templates: ['index', 'product', 'collection'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'floating', anchor: 'bottom', offsetX: 20, offsetY: 20, width: 'narrow', zIndex: 'sticky' },
        spacing: { padding: 'medium', margin: 'none', gap: 'tight', density: 'compact' },
        typography: { size: 'SM', weight: 'medium', lineHeight: 'normal', align: 'left' },
        colors: { text: '#111827', background: '#ffffff', overlayBackdropOpacity: 0.45, seed: '#22c55e' },
        shape: { radius: 'lg', borderWidth: 'thin', shadow: 'lg', elevation: 'soft' },
        responsive: { hideOnMobile: true, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
        motion: { duration: 'base', easing: 'standard' },
      },
    },
  },
  {
    id: 'PXY-MOD-19',
    name: 'Back-in-Stock Signup Widget (Appikon)',
    description: 'Embeddable back-in-stock notify-me widget on out-of-stock products — served from the app proxy so it captures the shopper email against the variant waitlist, matching Appikon Notify Me.',
    category: 'STOREFRONT_UI',
    type: 'proxy.widget',
    icon: 'back-in-stock',
    tags: ['appikon', 'back-in-stock', 'proxy', 'product', 'waitlist', 'notify-me'],
    spec: {
      type: 'proxy.widget',
      name: 'Back-in-Stock Signup Widget (Appikon)',
      category: 'STOREFRONT_UI',
      requires: ['APP_PROXY'],
      config: {
        widgetId: 'appikon-back-in-stock',
        mode: 'HTML',
        surface: 'embed',
        title: 'Notify me when available',
        message: 'Leave your email and we will alert you the moment this is back in stock.',
        ruleEngine: {
          enabled: true,
          logic: 'AND',
          matchAction: 'SHOW',
          onUnresolved: 'defer',
          groups: [
            { logic: 'AND', conditions: [{ object: 'product', attribute: 'available', operator: 'equal_to', value: false }] },
          ],
        },
      },
      placement: { enabled_on: { templates: ['product'] as (typeof THEME_PLACEABLE_TEMPLATES)[number][] } },
      style: {
        layout: { mode: 'inline', anchor: 'top', offsetX: 0, offsetY: 0, width: 'container', zIndex: 'base' },
        spacing: { padding: 'medium', margin: 'none', gap: 'tight', density: 'comfortable' },
        typography: { size: 'MD', weight: 'medium', lineHeight: 'normal', align: 'left' },
        colors: { text: '#111827', background: '#f8fafc', buttonBg: '#111827', buttonText: '#ffffff', overlayBackdropOpacity: 0.45, seed: '#0ea5e9' },
        shape: { radius: 'md', borderWidth: 'thin', shadow: 'sm', elevation: 'soft' },
        responsive: { hideOnMobile: false, hideOnDesktop: false },
        accessibility: { focusVisible: true, reducedMotion: true },
      },
    },
  },
];
