api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "superapp-payment-customization"
type = "function"
uid = "ec4cf2f9-69a4-9c83-fa5d-e4f9d1fb8921cc5d8141"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.payment-methods.transform.run"
  input_query = "src/cart_payment_methods_transform_run.graphql"
  export = "cart_payment_methods_transform_run"

  [extensions.build]
  command = "cargo build --target=wasm32-unknown-unknown --release"
  path = "target/wasm32-unknown-unknown/release/superapp-payment-customization.wasm"
  watch = [ "src/**/*.rs" ]

  [extensions.ui.paths]
  create = "/"
  details = "/"
