api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "superapp-delivery-customization"
type = "function"
uid = "f5c921aa-2d58-2263-addd-f043e98ce541a3715018"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.delivery-options.transform.run"
  input_query = "src/cart_delivery_options_transform_run.graphql"
  export = "cart_delivery_options_transform_run"

  [extensions.build]
  command = "cargo build --target=wasm32-unknown-unknown --release"
  path = "target/wasm32-unknown-unknown/release/superapp-delivery-customization.wasm"
  watch = [ "src/**/*.rs" ]

  [extensions.ui.paths]
  create = "/"
  details = "/"
