/**
 * Zod schema for the hydrate step response envelope.
 * Matches the skill prompt output shape (HydrateEnvelopeV1).
 */
import { z } from 'zod';

const ValidationCheckSchema = z.object({
  id: z.string(),
  severity: z.enum(['blocker', 'high', 'medium', 'low']),
  status: z.enum(['PASS', 'WARN', 'FAIL']),
  description: z.string(),
  howToFix: z.string().optional(),
});

export const ValidationReportSchema = z.object({
  overall: z.enum(['PASS', 'WARN']),
  checks: z.array(ValidationCheckSchema),
  notes: z.array(z.string()).optional(),
});

const ThemeEditorFieldSchema = z.object({
  id: z.string(),
  type: z.string(),
  label: z.string(),
  default: z.unknown().optional(),
  options: z.array(z.object({ value: z.string(), label: z.string() })).optional(),
  notes: z.string().optional(),
});

export const ThemeEditorSettingsSchema = z.object({
  fields: z.array(ThemeEditorFieldSchema),
  limitsNotes: z.array(z.string()).optional(),
});

const UiTokenItemSchema = z.object({
  token: z.string(),
  default: z.union([z.string(), z.number()]),
  themeAware: z.boolean().optional(),
});

export const UiTokensSchema = z.object({
  colors: z.array(UiTokenItemSchema).optional(),
  typography: z.array(UiTokenItemSchema).optional(),
  spacing: z.array(UiTokenItemSchema).optional(),
  radius: z.array(UiTokenItemSchema).optional(),
  shadow: z.array(UiTokenItemSchema).optional(),
});

export const AdminConfigSchemaSchema = z.object({
  schemaVersion: z.string(),
  jsonSchema: z.record(z.unknown()),
  uiSchema: z.record(z.unknown()).optional(),
  defaults: z.record(z.unknown()),
});

const SurfaceCompatSchema = z.object({
  surface: z.string(),
  status: z.enum(['SUPPORTED', 'LIMITED', 'NOT_SUPPORTED']),
  notes: z.array(z.string()).optional(),
});

const SurfacePlanSchema = z.object({
  selectedSurfaces: z.array(z.string()).optional(),
  compatibility: z.array(SurfaceCompatSchema).optional(),
});

const DataNeedSchema = z.object({
  key: z.string(),
  source: z.string(),
  notes: z.string().optional(),
});

const RenderContractSchema = z.object({
  runtimeInputs: z.array(z.string()).optional(),
  runtimeOutputs: z.array(z.string()).optional(),
  dataNeeds: z.array(DataNeedSchema).optional(),
});

const AnalyticsEventSchema = z.object({
  name: z.string(),
  when: z.string().optional(),
  properties: z.array(z.string()).optional(),
});

const AnalyticsSchema = z.object({
  eventSchema: z.record(z.unknown()).optional(),
  events: z.array(AnalyticsEventSchema).optional(),
});

const RecipeRefSchema = z.object({
  type: z.string(),
  name: z.string(),
  category: z.string().optional(),
});

export const HydrateEnvelopeSchema = z.object({
  version: z.literal('1.0'),
  moduleKey: z.string().optional(),
  recipeRef: RecipeRefSchema.optional(),
  summary: z.string().optional(),
  assumptions: z.array(z.string()).optional(),

  surfacePlan: SurfacePlanSchema.optional(),

  themeEditorSettings: ThemeEditorSettingsSchema,

  adminConfig: AdminConfigSchemaSchema,

  uiTokens: UiTokensSchema.optional(),

  renderContract: RenderContractSchema.optional(),

  analytics: AnalyticsSchema.optional(),

  /**
   * Self-contained HTML preview of the module, generated by AI.
   * Full HTML document (with <!doctype>, <head>, <body>) that can be rendered in an iframe.
   * Includes all necessary CSS and JS inline.
   */
  previewHtml: z.string().optional(),

  implementationPlan: z
    .object({
      runtimeHooks: z.array(z.record(z.unknown())).optional(),
      fileByFile: z.array(z.object({ path: z.string(), changeType: z.string(), details: z.string() })).optional(),
    })
    .optional(),

  validationReport: ValidationReportSchema,
});

export type HydrateEnvelope = z.infer<typeof HydrateEnvelopeSchema>;
export type ValidationReport = z.infer<typeof ValidationReportSchema>;
export type ThemeEditorSettings = z.infer<typeof ThemeEditorSettingsSchema>;
export type UiTokens = z.infer<typeof UiTokensSchema>;
export type AdminConfigSchema = z.infer<typeof AdminConfigSchemaSchema>;

/** Required property groups for "perfect config" guarantees; used by validatePerfectConfig. */
export const REQUIRED_ADMIN_GROUPS = [
  'content',
  'layout',
  'style',
  'behavior',
  'animation',
  'visibility_targeting',
  'rules_scheduling',
  'localization',
  'accessibility',
  'performance',
  'analytics',
] as const;

export type RequiredAdminGroup = (typeof REQUIRED_ADMIN_GROUPS)[number];

export interface PerfectConfigResult {
  valid: boolean;
  warnings: string[];
  /** Envelope to use (original or with auto-added defaults + WARN); always set when we patch. */
  envelope?: HydrateEnvelope;
}

/**
 * Post-parse checker: ensure adminConfig defaults contain all required groups.
 * If defaults are missing keys, auto-add empty object and add WARN (do not fail hydrate).
 */
export function validatePerfectConfig(envelope: HydrateEnvelope): PerfectConfigResult {
  const warnings: string[] = [];
  const schema = envelope.adminConfig;
  const props = (schema.jsonSchema as Record<string, unknown>)?.properties as Record<string, unknown> | undefined;
  const defaults = schema.defaults as Record<string, unknown>;

  if (props) {
    for (const group of REQUIRED_ADMIN_GROUPS) {
      if (!(group in props)) {
        warnings.push(`adminConfig.jsonSchema.properties missing group: ${group}`);
      }
    }
  }

  const defaultsCopy = defaults ? { ...defaults } : {};
  let defaultsPatched = false;
  for (const group of REQUIRED_ADMIN_GROUPS) {
    if (!(group in defaultsCopy)) {
      (defaultsCopy as Record<string, unknown>)[group] = {};
      defaultsPatched = true;
    }
  }
  if (defaultsPatched) {
    warnings.push('Defaults missing required groups; auto-added empty objects. Consider regenerating with explicit defaults.');
  }

  if (defaultsPatched) {
    const envelopePatched: HydrateEnvelope = {
      ...envelope,
      adminConfig: { ...schema, defaults: defaultsCopy },
      validationReport: {
        ...envelope.validationReport,
        overall: envelope.validationReport.overall === 'PASS' ? 'WARN' : envelope.validationReport.overall,
        checks: [
          ...envelope.validationReport.checks,
          {
            id: 'perfect_config_defaults',
            severity: 'medium',
            status: 'WARN',
            description: 'Defaults were missing required groups; empty defaults were added.',
            howToFix: 'Re-run hydrate to get explicit defaults for all 11 groups.',
          },
        ],
      },
    };
    return { valid: true, warnings, envelope: envelopePatched };
  }
  return { valid: warnings.length === 0, warnings };
}
