import { describe, expect, it, vi } from 'vitest';
import { JobTypeSchema } from '@superapp/platform-contracts';
import { createProcessorRegistry } from '../processors.js';
import type { AiGenerationAdapter, AiWorkerResult } from '../ai-generation.js';

/**
 * WS-C Task 17: the built-in stub AI adapter is gone — real generation runs in
 * apps/web (Task 5's `ai-generation.processor.server.ts`). This local double
 * stands in for "some real adapter was wired" wherever a test needs the
 * registry to actually build (every `createProcessorRegistry` call touches
 * AI_GENERATE/AI_HYDRATE/AI_MODIFY, whether or not the test cares about AI).
 */
function localTestAiAdapter(): AiGenerationAdapter {
  return {
    async generate(input): Promise<AiWorkerResult> {
      return {
        recipeSpec: {
          type: 'theme.section',
          name: 'Generated banner',
          category: 'STOREFRONT_UI',
          requires: ['THEME_ASSETS'],
          config: {
            kind: 'banner',
            activation: 'section',
            title: input.prompt.slice(0, 60) || 'Store announcement',
            subtitle: 'Generated by the local test double.',
            fields: { ctaText: 'Shop now', ctaUrl: 'https://example.com/collections/all' },
            blocks: [],
          },
        },
        options: [],
        model: 'local-test-double',
      };
    },
    async hydrate(input): Promise<AiWorkerResult> {
      return {
        recipeSpec: input.sourceSpec,
        validationReport: { overall: 'PASS', checks: [] },
        hydratedAt: new Date().toISOString(),
        model: 'local-test-double',
      };
    },
    async modify(input): Promise<AiWorkerResult> {
      return {
        recipeSpec: {
          type: 'theme.section',
          name: `Modified ${input.moduleId}`,
          category: 'STOREFRONT_UI',
          requires: ['THEME_ASSETS'],
          config: {
            kind: 'banner',
            activation: 'section',
            title: input.instruction.slice(0, 60) || 'Updated announcement',
            subtitle: 'Modified by the local test double.',
            fields: { ctaText: 'Learn more', ctaUrl: 'https://example.com/collections/all' },
            blocks: [],
          },
        },
        model: 'local-test-double',
      };
    },
  };
}

describe('worker processors', () => {
  it('registers a contract-validating processor for every planned job type', async () => {
    const logger = { info: vi.fn(), warn: vi.fn(), error: vi.fn() };
    const registry = createProcessorRegistry({ logger, aiAdapter: localTestAiAdapter() });

    expect(Object.keys(registry).sort()).toEqual([...JobTypeSchema.options].sort());

    const result = await registry.AI_GENERATE({
      id: 'job-1',
      type: 'AI_GENERATE',
      queueName: 'ai-generation',
      payload: { prompt: 'Create a banner' },
      trace: { correlationId: 'corr-processor-1' },
    });

    expect(result.status).toBe('SUCCESS');
    expect(result.events.map((event) => event.type)).toEqual(['JOB_STARTED', 'JOB_PROGRESS', 'JOB_COMPLETED']);
    expect(result.events[1]?.message).toContain('RecipeSpec');

    const internalResult = await registry.INTERNAL_TOOL_RUN({
      id: 'job-internal-1',
      type: 'INTERNAL_TOOL_RUN',
      queueName: 'internal-tool-run',
      payload: { sessionId: 'sess-1', message: 'Summarize failed jobs' },
      trace: { correlationId: 'corr-internal-processor-1' },
    });
    expect(internalResult.status).toBe('SUCCESS');
  });

  it('runs publish via runPublishJob when PUBLISH_WORKER_ENABLED and queue mode are on', async () => {
    const previousPublish = process.env.PUBLISH_WORKER_ENABLED;
    const previousMode = process.env.JOB_EXECUTION_MODE;
    process.env.PUBLISH_WORKER_ENABLED = 'true';
    process.env.JOB_EXECUTION_MODE = 'queue';
    try {
      const registry = createProcessorRegistry({
        logger: { info: vi.fn(), warn: vi.fn(), error: vi.fn() },
        aiAdapter: localTestAiAdapter(),
      });
      const result = await registry.PUBLISH({
        id: 'job-publish-enabled',
        type: 'PUBLISH',
        queueName: 'publish-execution',
        payload: { moduleId: 'mod_enabled', versionId: 'ver_enabled' },
        trace: { correlationId: 'corr-publish-enabled' },
      });
      expect(result.status).toBe('SUCCESS');
      expect(result.events.some((event) => event.type === 'JOB_COMPLETED')).toBe(true);
    } finally {
      if (previousPublish === undefined) delete process.env.PUBLISH_WORKER_ENABLED;
      else process.env.PUBLISH_WORKER_ENABLED = previousPublish;
      if (previousMode === undefined) delete process.env.JOB_EXECUTION_MODE;
      else process.env.JOB_EXECUTION_MODE = previousMode;
    }
  });

  it('rejects invalid job payloads through shared schemas', async () => {
    const registry = createProcessorRegistry({
      logger: { info: vi.fn(), warn: vi.fn(), error: vi.fn() },
      aiAdapter: localTestAiAdapter(),
    });
    await expect(registry.PUBLISH({
      id: 'job-2',
      type: 'PUBLISH',
      queueName: 'publish-execution',
      payload: {},
      trace: { correlationId: 'corr-processor-2' },
    })).rejects.toThrow();
  });

  it('WS-C Task 17: constructing processors without an AI adapter throws (the stub was removed)', () => {
    const logger = { info: vi.fn(), warn: vi.fn(), error: vi.fn() };
    expect(() => createProcessorRegistry(logger)).toThrow(/stub was removed/);
    // `aiAdapter` is a required field at the type level now — this exercises
    // the runtime guard for a caller that bypasses that (e.g. plain JS, or a
    // spread that dropped the field), so the cast is deliberate.
    expect(() => createProcessorRegistry({ logger } as never)).toThrow(/stub was removed/);
  });
});
