api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "cart-transform-function"
type = "function"
uid = "5cc370ef-8645-3624-75a8-41ea95d2a29800b5d0c7"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart_transform_run"

  [extensions.build]
  command = "cargo build --target=wasm32-unknown-unknown --release"
  path = "target/wasm32-unknown-unknown/release/superapp-cart-transform.wasm"
  watch = [ "src/**/*.rs" ]

  [extensions.ui.paths]
  create = "/"
  details = "/"
